### PR TITLE
[AnimatedIcon] Fix issue where setting source property would not resize AnimatedIcon properly

### LINKED ISSUE #6659: AnimatedIcon does not dirty layout when Source changes.
AnimatedIcon does not dirty its layout when the source property changes which can cause icons to be rendered at very wrong sizes if you change the source property while the icon is in the tree, until something else dirties the layout.  The fix is to Invalidate measure when the source property changes.

image

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Issue was that the layout was not invalidated when setting the source property.

## Motivation and Context

Closes #6659 
## How Has This Been Tested?

Added new API test

### CODE REVIEW

**Review by StephenLPeters — APPROVED** [review]

**Review by StephenLPeters — APPROVED** [review]

File: dev/AnimatedIcon/APITests/AnimatedIconTests.cs [hunk 1]
```diff
@@ -427,5 +427,36 @@ void AnimatedIcon_LayoutUpdated(object sender, object e)
...
+                Verify.IsTrue(Math.Abs(icon.ActualSize.Y) < 0.1);
+                icon.Source = new AnimatedChevronDownSmallVisualSource();
+            });
+
+            IdleSynchronizer.Wait();
+
+            RunOnUIThread.Execute(() =>
+            {
+                // Icon will have a width if the AnimatedIcon also updated the visual tree to rerender.
+                Verify.IsTrue(Math.Abs(icon.ActualSize.Y) > 10);
```
Comment (StephenLPeters) [inline dev/AnimatedIcon/APITests/AnimatedIconTests.cs:458]: @chingucoding UIElement.ActualSize isn't available downlevel which is why your test is failing. Can we change this to ActualHeight instead?

**Review by StephenLPeters — APPROVED** [review]

File: dev/AnimatedIcon/APITests/AnimatedIconTests.cs (hunk 1 above)
Comment (chingucoding) [reply dev/AnimatedIcon/APITests/AnimatedIconTests.cs]: Always forget about, thanks for pointing it out. Should be fixed now.
