### PR TITLE
Fix crash with UniformGridLayout trying to scroll to first item

### LINKED ISSUE #535: Scrolling down a collection of nested ItemsRepeater with UniformGridLayout as inner layout causes layout cycle hang
**Describe the bug**

See title

**Steps to reproduce the bug**

1. Build and run the attached repro.  It's using nested repeaters.  The outer is using a StackLayout and the inner for the items uses a UniformGridLayout.
2. Scroll down a few pages.  The app will seem to hang.

[App10.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3049946/App10.zip)

**Expected behavior**

No hangs

**Version Info**

NuGet package version: 

Latest Microsoft.UI.Xaml

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2018 Update (17763)   | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |

### LINKED ISSUE #2834: ItemsRepeater crashes when scrolling back and forth
**Describe the bug**
The following sample causes ItemsRepeater to fail internally and crash the app.

**Steps to reproduce the bug**

1. Run the following sample:

```C#
public sealed class ItemsRepeaterPage : Page
{
    public ItemsRepeaterPage()
    {
        var repeater = new ItemsRepeater
        {
            ItemsSource = Enumerable.Range(0, 1000).Select(i => new Border
            {
                Background = new SolidColorBrush(Colors.Blue),
                Child = new TextBlock { Text = "#" + i }
            }).ToArray(),
            Layout = new UniformGridLayout
            {
                MinItemWidth = 100, MinItemHeight = 40,
                MinRowSpacing = 10, MinColumnSpacing = 10
            }
        };
        Content = new ScrollViewer { Content = repeater };
    }
}
```
2. When you scroll to the end then scroll back to the start, Item #0 is not visible.
3. Then, trying to scroll to the end again causes COMException: "ItemsRepeater's child not found in its Children collection."

**Expected behavior**
The app should not crash.

**Version Info**
Tested with version 2.4.2 and 2.5.0.prerelease on Windows 10 1909.

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

The issue is that we didn't managed to properly recycle the first item, even though the UniformGridLayout was the owner. That resulted in the ElementManager trying to move ownership to realize that it isn't the actual owner, which resulted in the crash.

The behavior changed to only cache the item's desired size (which is the only information we needed), and let the ElementManager take care of managing.
## Motivation and Context

Closes #535 and closes #2834
## How Has This Been Tested?

Add API test for #2834, tested #535 manually (code not included in this PR)

### CODE REVIEW

**Comment by chingucoding** [comment]
Also, does #2812 have the green light? During this PR, I wish there was some form of documentation on how those areas work together as the stacktrace can be quite long and go through different areas of the ItemsRepeater control.

File: dev/Repeater/UniformGridLayoutState.cpp [hunk 1]
```diff
@@ -50,32 +45,32 @@ void UniformGridLayoutState::EnsureElementSize(
...
-            if (!m_cachedFirstElement)
+            if (!hasCachedSize)
             {
                 // we only cache if we aren't realizing it
-                m_cachedFirstElement = context.GetOrCreateElementAt(0, winrt::ElementRealizationOptions::ForceCreate | winrt::ElementRealizationOptions::SuppressAutoRecycle); // expensive
+                // expensive
+                if (const auto firstElement = context.GetOrCreateElementAt(0, winrt::ElementRealizationOptions::ForceCreate))
+                {
+                    firstElement.Measure(availableSize);
+                    hasCachedSize = true;
```
Comment (ranjeshj) [inline dev/Repeater/UniformGridLayoutState.cpp:61]: >hasCachedSize [](start = 20, length = 13)

If size change after the first measure, we will not update the size of all the items. This is a change in behavior with this change because of the caching here.

Comment (chingucoding) [reply dev/Repeater/UniformGridLayoutState.cpp]: I've changed the code now to always realize if FlowLayout did not do that. Is there anything else we need to consider here?

**Comment by KanniyappanP** [comment]
We used items repeater control with a uniform grid layout and face the same issue above. (We also using the winui 3 preview 3).

1. Item 0 disappeared when scroll up and scroll down the items.
2. When using column spacing and row spacing in uniform grid layout, below crash occurred

"**itemsrepeater's child not found in its children collection.**"

 Is this fix reflected in the Winui 3 preview 3 release?
