### PR TITLE
NavigationView: Fix SelectedItem not being unset when no NavigationViewItem is selected

### LINKED ISSUE #957: NavigationView not resetting its SelectedItem if all items are unselected
**Describe the bug**
Setting the `NavigationViewItem.IsSelected` property to `false` for all the items in `NavigationView.MenuItems` is not resetting `NavigationView.SelectedItem`

**Steps to reproduce the bug**
1. Create a new app with the following XAML code:
```xml
<mux:NavigationView
    x:Name="navView"
    IsBackEnabled="True"
    PaneDisplayMode="Top">
    <mux:NavigationView.MenuItems>
        <mux:NavigationViewItem x:Name="navViewItemA" Content="Item A" />
        <mux:NavigationViewItem x:Name="navViewItemB" Content="Item B" />
    </mux:NavigationView.MenuItems>

    <StackPanel>
        <Button Click="SelectItemAClicked" Content="Select item A" />
        <Button Click="SelectItemBCliked" Content="Select item B" />
        <Button Click="SelectNoneBCliked" Content="Select None" />
    </StackPanel>
</mux:NavigationView>
```
2. Add the following code behind:
```csharp
private void SelectItemAClicked(object sender, RoutedEventArgs e)
{
    navViewItemB.IsSelected = false;
    navViewItemA.IsSelected = true;
}

private void SelectItemBCliked(object sender, RoutedEventArgs e)
{
    navViewItemA.IsSelected = false;
    navViewItemB.IsSelected = true;
}

private void SelectNoneBCliked(object sender, RoutedEventArgs e)
{
    navViewItemA.IsSelected = false;
    navViewItemB.IsSelected = false;
}
```
3. Run the application and click on the three buttons in the following order : *Select Item A*, *Select Item B*, *Select None*
3.1. Notice that *Item A* and *Item B* are properly selected when clicking on the first two buttons
3.2. Notice that *Item B* remains selected when clicking on *None*

**Expected behavior**
When setting all the items to `IsSelected = false`, the `SelectedItem` of `NavigationView` should revert to `null`

**Screenshots**

image

**Version Info**
NuGet package version:
Microsoft.UI.Xaml 2.1.190606001
Microsoft.UI.Xaml 2.2.190611001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Additional context**
If we manually set the `SelectedItem` from the code behind, the `NavigationView` is properly deselecting all its items. I'm using this as a workaround for now but it would be great if toggling the `NavigationViewItem.IsSelected` works. It simplifies a lot the binding.

**Proposed fix**
[proposed by Yulikl]
NavigationViewItem has a boolean IsSelected property. When all of NavigationView's MenuItems set IsSelected to false, NavigationView should return null as its SelectedItem.

### PR DESCRIPTION
**Pull request by Felix-Dev**
## Description
Fix issue where NavView's SelectedItem property was not set to null when all navigation view items are no longer selected.

## Motivation and Context
Fixes #957 

## How Has This Been Tested?
Added API test.

### CODE REVIEW

File: dev/Repeater/SelectionModel.cpp [hunk 1]
```diff
@@ -647,7 +647,11 @@ void SelectionModel::SelectWithPathImpl(const winrt::IndexPath& index, bool sele
         // If we unselect something, raise event any way, otherwise changedSelection is false
         bool changedSelection = false;
 
-        if (m_singleSelect)
+        // We only need to clear selection by walking the data structure from the beginning when we are in single selection mode
+        // and want to select something.
```
Comment (chingucoding) [inline dev/Repeater/SelectionModel.cpp:651]: Nit: layout. Something you could do:

```suggestion
        // We only need to clear selection by walking the data structure from the beginning when:
        // - we are in single selection mode and 
        // - want to select something.
```

File: dev/Repeater/SelectionModel.cpp [hunk 2]
```diff
@@ -647,7 +647,11 @@ void SelectionModel::SelectWithPathImpl(const winrt::IndexPath& index, bool sele
...
+        // If we want to unselect something we unselect it directly in TraverseIndexPath below and raise the SelectionChanged event
+        // if required.
+        if (m_singleSelect && select)
```
Comment (chingucoding) [inline dev/Repeater/SelectionModel.cpp:654]: So the root cause of the issue was that deselecting an item did not work correctly?

It might be good to also add an API test for this, since the issue is only manifesting in NavigationView but is caused by SelectionModel.

Comment (Felix-Dev) [reply dev/Repeater/SelectionModel.cpp:654]: Yes. Here's a longer explanation: 

The issue was that unselecting an item in the SelectionModel was not reported back to the NavigationView: In case of item unselection, we first cleared the selection (ClearSelection()) which does not raise the SelectionChanged event. Inside of the TraverseIndexPath() code block we prepare for raising the event by setting the flag `changedSelection` to true in case we updated a node selection state. However, as we already cleared the selection above, all nodes are already unselected and that flag is not set. This causes the event (SelectionChanged) not being raised in case of item deselection, thus the NavigationView, which listens to this event, won't notice the selection of its SelectionModel changed and will not update its SelectedItem property (set it to null).

I will add a test for the SelectionModel tomorrow.

**Comment by Felix-Dev** [comment]
@ranjeshj VS seems to suggest you worked on this test so I'll ask you: Is the `ValidateSelection` call [here](https://github.com/microsoft/microsoft-ui-xaml/blob/462eeeaaea50419e0160c03b53a52a85db56cc1d/dev/Repeater/APITests/SelectionModelTests.cs#L98) really necessary? (That method is the previous ``ValidateSelectionChangedEvent` just renamed.) It seems to me we are validating whether item 4 has been selected *two* times. Do we need both checks?

**Comment by chingucoding** [comment]
> @ranjeshj VS seems to suggest you worked on this test so I'll ask you: Is the ValidateSelection call here really necessary? (That method is the previous ValidateSelectionChangedEvent() just renamed.) It seems to me we are validating whether item 4 has been selected two times. Do we need both checks?

I think the idea is that we verify that the selection is also correct when selectionchanged got raised.

**Comment by Felix-Dev** [comment]
@Chingucoding I just don't think we need to check that *twice*. If oen check is already correct, why would the other one fail? We are only changing the selection state once, before we validate the selection.

**Comment by chingucoding** [comment]
> @chingucoding I just don't think we need to check whether the selection is correct twice. If we keep the check in the SelectionChanged event handler I don't think we need the other check (as we fail if event was not raised).

We check if the selection is correct after we changed it and we also check if the selection is correct inside the SelectionChanged event. Techincally there could be a missmatch for example when we raise SelectionChanged to early.

**Comment by ranjeshj** [comment]
> hat method is

That does look redundant. One thing this might be checking is that the timing is correct - that the selection state has been updated before raising the event and checking the state in the event handler gives us the expected values. If that is not covered by any of the other tests, then a comment might be useful. If that is being covered elsewhere, we can remove the check. Thanks.

**Comment by Felix-Dev** [comment]
I kept the SelectionChanged event handler ValidateSelection checks and removed the specific `Select` checks as they are covered in their own tests (`ValidateOneLevelSingleSelection()` and `ValidateOneLevelMultipleSelection()`).

File: dev/Repeater/APITests/SelectionModelTests.cs [hunk 3]
```diff
@@ -72,11 +113,12 @@ public void ValidateSelectionChangedEvent()
                 selectionModel.SelectionChanged += delegate (SelectionModel sender, SelectionModelSelectionChangedEventArgs args) 
                 {
                     selectionChangedFiredCount++;
+
+                    // Verify SelectionChanged was raised after selection state was changed in the SelectionModel
                     ValidateSelection(selectionModel, new List<IndexPath>() { Path(4) }, new List<IndexPath>() { Path() });
                 };
 
                 Select(selectionModel, 4, true);
-                ValidateSelection(selectionModel, new List<IndexPath>() { Path(4) }, new List<IndexPath>() { Path() });
```
Comment (StephenLPeters) [inline dev/Repeater/APITests/SelectionModelTests.cs:79]: >ValidateSelection(selectionModel, new List<IndexPath>() { Path(4) }, new List<IndexPath>() { Path() }); [](start = 16, length = 103)

Why are we removing this?

Comment (chingucoding) [reply dev/Repeater/APITests/SelectionModelTests.cs:79]: That check is redundant and does not cover anything that wouldn't be not covered otherwise.
