### PR TITLE
Fix issue where an originally-collapsed WebView2 can't be interacted with

### LINKED ISSUE #6256: Unable to interact with initially hidden WebView2 on UWP
### Describe the bug

Suppose there's a WebView2 written in Xaml. It is hidden at first, then it is changed to visible and navigated to an uri after user's action. After the WebView2 is shown, it can't be interacted with mouse, but if you use Tab to move focus within it, you can use keyboard, such as up or down arrow key, to interact with it. It seems like something transparent is overlapping on it.

There is no problem if WebView2 isn't initially hidden.

Only UWP project has the problem. The same code on WinUI 3 works OK.

Sample projects:

UWP (has problem):
[HiddenWebView2UWP.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7496980/HiddenWebView2UWP.zip)

WinUI 3 (works fine):
[HiddenWebView2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7496982/HiddenWebView2.zip)

### NuGet package version

2.8 preview

### Windows app type

- [X] UWP
- [ ] Win32

### PR DESCRIPTION
**Pull request by krschau**
The main fix here is to add a Grid as Content for the WebView2. This allows WUX hit testing code to find the WebView2, but doesn't get in its way. The size of the Grid is kept in sync with the WebView2 control.

## Description
Other changes are:
* In CheckAndUpdateWebViewPosition(), we were updating the CoreWebView2 Controller's position/size every time. Changed that to only when something has changed.
* Removed unnecessary Wait.ForIdle()s, removing unnecessary Ignore tags, changing "RTB" header to "Focus"
* Pulled code to remove the WebView2 that tests start with into its own RemoveExistingWebViewControl() method

## Motivation and Context
Fixes #6256

## How Has This Been Tested?
Added two tests, HiddenThenVisibleTest and ParentHiddenThenVisibleTest. These tests can also be executed manually.

### CODE REVIEW

File: dev/WebView2/InteractionTests/WebView2Tests.cs [hunk 1]
```diff
@@ -2149,10 +2144,68 @@ public void HtmlDropdownTest()
...
+                Log.Comment("Bounds = X:{0}, Y:{1}, Width:{2}, Height:{3}", bounds.X, bounds.Y, bounds.Width, bounds.Height);
+                var point = new Point(bounds.X + 20, bounds.Y + 20);
+                Log.Comment("Move mouse to ({0}, {1})", bounds.X + 20, bounds.Y + 20);
+                PointerInput.Move(point);
+
+                PointerInput.Press(PointerButtons.Primary);
+                PointerInput.Release(PointerButtons.Primary);
+                Wait.ForIdle();
+
+                WaitForWebMessageResult("HiddenThenVisibleTest");
```
Comment (DmitriyKomin) [inline dev/WebView2/InteractionTests/WebView2Tests.cs:2172]: Looks like this tests is doing two types of validation - one via CompleteTestAndWaitForResult(), another via WaitForMessageResult(). Just want to make sure - if the 1st part fails, will the test overall still report failure?

File: dev/WebView2/WebView2.cpp [hunk 2]
```diff
@@ -1763,7 +1792,8 @@ void WebView2::CheckAndUpdateWebViewPosition()
         return;
     }
 
-    // Check if the position of the WebView within the window has changed
+    // Check if the position of the WebView2 within the window has changed
+    bool changed = false;
```
Comment (DmitriyKomin) [inline dev/WebView2/WebView2.cpp:1796]: Great to see this change!

File: dev/WebView2/WebView2.cpp [hunk 3]
```diff
@@ -1505,6 +1505,38 @@ void WebView2::TryCompleteInitialization()
...
     }
 
+    AddChildPanel();
+    CreateAndSetVisual();
+
+    // If we were recreating the webview after a core process failure, indicate that we have now recovered
+    m_isCoreFailure_BrowserExited_State = false;
+}
+
+void WebView2::AddChildPanel()
```
Comment (DmitriyKomin) [inline dev/WebView2/WebView2.cpp:1515]: Can you add a comment why this is necessary?

File: dev/WebView2/WebView2.cpp [hunk 4]
```diff
@@ -1505,6 +1505,38 @@ void WebView2::TryCompleteInitialization()
             [this](auto&&, auto&&) { UpdateDefaultBackgroundColor(); });
     }
 
+    AddChildPanel();
+    CreateAndSetVisual();
+
```
Comment (DmitriyKomin) [inline dev/WebView2/WebView2.cpp:1510]: This should be under #ifdef WINUI2 I think?

File: dev/WebView2/WebView2.cpp (hunk 2 above)
Comment (DmitriyKomin) [reply dev/WebView2/WebView2.cpp:1796]: Also to clarify - this change is a cleanup/performance improvement, not strictly necessary to address the bug with WV2 starting invisible, right?

**Review by DmitriyKomin — CHANGES_REQUESTED** [review]
:clock1:

File: dev/WebView2/InteractionTests/WebView2Tests.cs (hunk 1 above)
Comment (krschau) [reply dev/WebView2/InteractionTests/WebView2Tests.cs:2172]: Yes, the test should fail and bail on the first time a Verify comes back false, whichever WaitFor... that's inside (or not inside).

File: dev/WebView2/WebView2.cpp (hunk 4 above)
Comment (krschau) [reply dev/WebView2/WebView2.cpp:1510]: We have plenty of code in WinUI 2 that's not in WinUI 3 that we don't #ifdef. If anything, we should just remove the WinUI 3 bits we left in. If we want to go the other way and start adding ifdefs for everything, I think that should be its own effort.

File: dev/WebView2/WebView2.cpp (hunk 2 above)
Comment (krschau) [reply dev/WebView2/WebView2.cpp:1802]: Yes, it's a separate thing I noticed while working on this.

File: dev/WebView2/WebView2.cpp [hunk 5]
```diff
@@ -1505,6 +1505,44 @@ void WebView2::TryCompleteInitialization()
...
+    if (content)
+    {
+        auto panelContent = content.as<winrt::Grid>();
+        if (panelContent)
+        {
+            panelContent.Height(this->ActualHeight());
+            panelContent.Width(this->ActualWidth());
+        }
+    }
+}
```
Comment (DmitriyKomin) [inline dev/WebView2/WebView2.cpp:1542]: Looking at this again, can resizing of the Content be handled by MeasureOverride/ArrangeOverride? (Then the Grid will not need to Width/Height specified)

It looks like there was already some code for this in MeasureOverride/ArrangeOverride, but got commented out...

File: dev/WebView2/WebView2.cpp [hunk 6]
```diff
@@ -1505,6 +1505,44 @@ void WebView2::TryCompleteInitialization()
...
+    // If we were recreating the webview after a core process failure, indicate that we have now recovered
+    m_isCoreFailure_BrowserExited_State = false;
+}
+
+void WebView2::AddChildPanel()
+{
+    auto panelContent = winrt::Grid();
+    panelContent.Background(winrt::SolidColorBrush(winrt::Colors::Transparent()));
+    panelContent.Height(this->ActualHeight());
+    panelContent.Width(this->ActualWidth());
```
Comment (codendone) [inline dev/WebView2/WebView2.cpp:1526]: Is hardcoding the size required? I'd hope it isn't. If it doesn't get the size without this, then we should try using ArrangeOverride() instead to set the size (similar to the commented-out code in there). Setting Width/Height here will affect the DesiredSize, which could prevent the WV2 getting smaller if its container panel gets smaller.

File: dev/WebView2/WebView2.cpp [hunk 7]
```diff
@@ -833,24 +833,28 @@ void WebView2::CreateMissingAnaheimWarning()
...
+// Make sure it is visited by the Measure pass.
 winrt::Size WebView2::MeasureOverride(winrt::Size const& availableSize)
 {
-    //if (auto child = Content().try_as<winrt::FrameworkElement>())
-    //{
-    //    Content().Measure(availableSize);
-    //}
+    if (auto child = Content().try_as<winrt::FrameworkElement>())
+    {
+        child.Measure(availableSize);
```
Comment (codendone) [inline dev/WebView2/WebView2.cpp:842]: Is this override needed? I'd expect the default implementation inherited from Control to take care of this.

File: dev/WebView2/WebView2.cpp [hunk 8]
```diff
@@ -833,24 +833,28 @@ void WebView2::CreateMissingAnaheimWarning()
...
+        return availableSize;
```
Comment (codendone) [inline dev/WebView2/WebView2.cpp:843]: >availableSize [](http://example.com/codeflow?start=15&length=13)

I think this should be child.DesiredSize.

**Review by codendone — APPROVED** [review]
:shipit:
