### PR TITLE
Fix a Teaching Tip Crash in unpackaged apps

### LINKED ISSUE #742: TeachingTip on Xaml Islands requires an package identity.
**Describe the bug**
Trying to use the TeachingTip on a Xaml Island context requires a package identity.

**Steps to reproduce the bug**
Have a custom xaml island element, and the moment you call ToggleThemeTeachingTip1.IsOpen = true; it will throw an exception:
{"The process has no package identity. (0x80073D54)"}

**Expected behavior**
This should not be required by such a simple control. It should work without an app id.

NuGet package version: 
Microsoft.UI.Xaml 2.2.190430003-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18898)              | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

### PR DESCRIPTION
**Pull request by StephenLPeters**
Move Package::Current() to a try block. Fixes #742

### CODE REVIEW

**Comment by jevansaks** [comment]
@StephenLPeters can you add the "Fixes #NNN" thing to the PR description?

File: dev/TeachingTip/TeachingTip.cpp [hunk 1]
```diff
@@ -1123,17 +1123,22 @@ void TeachingTip::OnPopupOpened(const winrt::IInspectable&, const winrt::IInspec
...
-            return winrt::hstring{};
-        }();
+                try
+                {
+                    if (auto&& package = winrt::ApplicationModel::Package::Current())
+                    {
+                        return package.DisplayName();
+                    }
+                }
+                catch (...) {}
```
Comment (chrisglein) [inline dev/TeachingTip/TeachingTip.cpp]: Totally down with this fix to unblock things, but we should follow up about having an API that doesn't require a caught exception here.
1) Add a comment here
2) Open a bug on whoever owns the app model API to add a no exception version of this query (and link the bug in the comment)
