### PR TITLE
Collapse header if AlwaysShowHeader is false and  PaneDisplayMode is Top

### LINKED ISSUE #757: NavigationView Header is being shown in PaneDisplayMode Top despite AlwaysShowHeader to false
**Describe the bug**

If the `Header` property of NavigationView is set, despite setting AlwaysShowHeader is set to false, the header stays in all mode (all non-compact)

**Steps to reproduce the bug**

1. Create a page, put `NavigationView` controls in with something for the `Content` 
2. Set the header property with a control, like a textbox or something.
3. Set `AlwaysShowHeader` to `false`
4. Observe the content region. it always have a 40px reserved space on top for the header that is not supposed to be shown

**Expected behavior**

Expected the header to be hidden while the `PaneDisplayMode = "Top"` 

**Screenshots**

Header being shown in `PaneDisplayMode = "Top"`
image

But not when the pane is switch to the side.
image

**Version Info**

NuGet package version: 

2.1.190405004.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

Setting the header content to `Visibility="Collapsed"` or setting the header template to be collapsed doesn't work. The reserved space seems to always be there.

## Proposed fix
[Edited by YuliKl]
When AlwaysShowHeader = False, the header should be collapsed in all display modes **except** Minimal.

### PR DESCRIPTION
**Pull request by brunasilvalopes**
When updating the header visibility, we were ignoring the AlwaysShowHeader property if the DisplayMode was minimal.  The problem is that when the PaneDisplayMode is Top, the DisplayMode is automatically Minimal, therefore we were also ignoring AlwaysShowHeader property in this scenario. This commit fixes it by checking also if the navigation is Top in addition to checking if DisplayMode is Minimal.

Fix #757

### CODE REVIEW

**Comment by brunasilvalopes** [comment]
I haven't written any tests so far, but i just wanted some feedback on the way I resolved this bug.
When the PaneDisplayMode is Top, the DisplayMode is automatically Minimal - you can se us setting it to minimal on the method UpdatePaneDisplayMode, line 2846. This assumption is what was causing the bug.

**Comment by jevansaks** [comment]
I think you're in the right vicinity but I defer to @licanhua .

File: dev/NavigationView/NavigationView.cpp [hunk 1]
```diff
@@ -2970,7 +2970,9 @@ void NavigationView::UpdateHeaderVisibility()
 
 void NavigationView::UpdateHeaderVisibility(winrt::NavigationViewDisplayMode displayMode)
 {
-    bool showHeader = AlwaysShowHeader() || displayMode == winrt::NavigationViewDisplayMode::Minimal;
+    // Ignore AlwaysShowHeader property in case DisplayMode is minimum and we're not a Top NavigationView
```
Comment (licanhua) [inline dev/NavigationView/NavigationView.cpp]:
```suggestion
    // Ignore AlwaysShowHeader property in case DisplayMode is Minimal and it's not Top NavigationView
```

Comment (licanhua) [reply dev/NavigationView/NavigationView.cpp]: Fix looks good to me.

Comment (licanhua) [reply dev/NavigationView/NavigationView.cpp]: @YuliKl  Can you confirm if the fix is reasonable? Without the fix, In top navigationview, it always show header not matter AlwaysShowHeader is true or false.

**Comment by brunasilvalopes** [comment]
**Test Run - MUXControls.Test**
Here's the result of the test run:
image

The CommandBarFlyoutTests seems to have failed, but when I expanded the test group, all the 8 tests inside have succeeded. So I ran them again and now I got a green icon on the task group:
image

For the NavigationViewTests, 2 tests failed with the same error message: LeftNavigationWithAccessKeysTest and TopNavigationWithAccessKeysTest
Error Message: Assert.IsNotNull failed. keytip
image

I ran them again and got the same error. I'll investigate why this is happening and if it's related to my changes.

**Comment by jevansaks** [comment]
I'll also kick a test build to see how the official run feels about it.
/azp run

File: dev/NavigationView/NavigationView.cpp (hunk 1 above)
Comment (YuliKl) [reply dev/NavigationView/NavigationView.cpp]: Yes, this looks good. Top NavigationView should respect the AlwaysShowHeader property.

File: dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs [hunk 2]
```diff
@@ -558,6 +558,23 @@ public void AlwaysShowHeaderTest()
                     headerVisibilityCheckbox.Check();
                     Wait.ForIdle();
                     VerifyElement.Found("Home as header", FindBy.Name);
+
+                    // PaneDisplayMode and Top option were added on RS5, so just run the next tests if we are not using RS4 Style
+                    if (!testScenario.IsUsingRS4Style)
```
Comment (brunasilvalopes) [inline dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs]: Not sure if this if the best place to add this test. Please let me know if you have suggestions of better places.

**Comment by brunasilvalopes** [comment]
**Test Run - IXMPTestApp**
image

**Test Run - MUXControlsTestApp**
image

Test VerifyCurrentAnchor failed during the test run, but when I ran it by itself, it suceeded. I don't think this test was affected by this bug fix.
image
