### PR TITLE
Bug fixes to AnimatedVisualPlayer, and some test cleanup.

### LINKED ISSUE #1480: ~AnimatedVisualPlayer should not tank the process if a visual is still animating
Isn't there a way to gracefully recover from this within ~AnimatedVisualPlayer?  How about just stopping the player?  That's what I have to do in my dtor to work around this.

AnimatedVisualPlayer::~AnimatedVisualPlayer()
{
    if (m_nowPlaying != nullptr)
    {
        MUX_FAIL_FAST_MSG("Owner AnimatedVisualPlayer is destroyed, current playing AnimationPlay is not empty!");
    }
}

### LINKED ISSUE #1510: AnimatedVisualPlayer.PlayAsync often completes before the animation is actually finished rendering/animating
One of our animations is performed in 3 phases: 1. Play the 'inrto', 2. Loop in the middle, 3. Play the 'outro'.

It often works fine, but other times the 'intro' phase completes almost immediately.

Phase 1: Play from 0.0->43.333
Phase 2: Once phase 1 completes, loop from frames ~43.333->80.00
Phase 3: Upon an external trigger, animate from ~80.00->100.0

The problem is that we're often seeing 'phase 1' complete almost immediately, so our animation just 'jumps' to the middle looping phase.

### PR DESCRIPTION
**Pull request by simeoncran**
Bug fixes to AnimatedVisualPlayer, and some test cleanup.

## Description
Replaces assert in AVP destructor that would fire if an animation was playing. Now we just stop the animation.

Fixes inability to react to IsAnimatedVisualLoaded DP to start playing. This was caused by reentrancy from setting a DP which made the client think they could start playing because an IAnimatedVisual had been loaded when in fact we were not yet ready to start playing.

Add more commenting to help explain reentrancy in AVP. This was to help me reason about what was going on. Reentrancy from DPs is hard and I know there are going to be cases where you'll see torn state in a DP callback from AVP, but at least with the comments it's a bit easier for the reader to find these and decide whether they're acceptable.

Simplify the test code. The UI page for testing the AVP was impossible to use manually without referring to the code, so I added a bunch of labels to the buttons. And I found the UI code to be very difficult to follow, so I refactored it for readability.

## Motivation and Context
Fixes #1480 
Fixes #1510 

## How Has This Been Tested?
Manual testing.

### CODE REVIEW

**Comment by simeoncran** [comment]
@improbabilityphysics is added to the review. #Closed

File: dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp [hunk 1]
```diff
@@ -33,6 +33,7 @@ float AnimatedVisualPlayer::AnimationPlay::FromProgress()
     return m_fromProgress;
 }
 
+// REENTRANCE SIDE EFFECT: IsPlaying DP.
```
Comment (StephenLPeters) [inline dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp]: These reentrancy tracking issues seems like it might easier to nail down if this control included Tracing.  You can see Scroller, SwipeControl, or PullToRefresh as examples of controls which already have tracing built it.

File: dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp [hunk 2]
```diff
@@ -393,12 +405,14 @@ void AnimatedVisualPlayer::OnUnhiding()
     }
 }
 
+// Public API.
```
Comment (StephenLPeters) [inline dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp]: Are the public API comments useful?

File: dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp (hunk 1 above)
Comment (StephenLPeters) [reply dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp]: If you wanted/needed additional tools, I'm not saying you need to do that for this check in.

---
In reply to: [343379771](https://github.com/microsoft/microsoft-ui-xaml/pull/1558#discussion_r343379771) [](ancestors = 343379771)

Comment (simeoncran) [reply dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp]: Can you expand on this... are you saying to add tracing into the code, and then what do we do with the result?

---
In reply to: [343381461](https://github.com/microsoft/microsoft-ui-xaml/pull/1558#discussion_r343381461) [](ancestors = 343381461,343379771)

Comment (StephenLPeters) [reply dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp]: if you replaced comments in the code with tracing statements, when you hit a dependency reentrency crash the tracing output will tell you which potential causes you hit for that repro, instead of having to look at every call in the stack trace.

File: dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp (hunk 2 above)
Comment (simeoncran) [reply dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp]: They save the reader from having the read the header file in order to understand that these are public. The problem they solve for me is to make is easier to reason about reentrance. At each DP setter I need to consider that code could reenter from any of the public methods. Being able to easily identify the public methods makes it faster to do that reasoning.

---
In reply to: [343380321](https://github.com/microsoft/microsoft-ui-xaml/pull/1558#discussion_r343380321) [](ancestors = 343380321)

File: dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp (hunk 1 above)
Comment (simeoncran) [reply dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp]: I see. That could be useful but we still wouldn't know that the behavior the caller is seeing isn't what they expect. 

---
In reply to: [343775739](https://github.com/microsoft/microsoft-ui-xaml/pull/1558#discussion_r343775739) [](ancestors = 343775739)

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs [hunk 3]
```diff
@@ -12,45 +13,70 @@
...
+        {
+            var count = VisualTreeHelper.GetChildrenCount(root);
+            for (var i = 0; i < count; i++)
+            {
+                var child = VisualTreeHelper.GetChild(root, i);
+                if (child is FrameworkElement element)
+                {
+                    // Copy the x:Name into the AutomationPeer name.
+                    var name = element.Name;
+                    if (!string.IsNullOrEmpty(name))
```
Comment (kmahone) [inline dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs]: Optional: consider adding a check for an existing AutomationPeer Name before over-writing.

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs [hunk 4]
```diff
@@ -12,45 +13,70 @@
...
-
         public AnimatedVisualPlayerPage()
         {
             this.InitializeComponent();
+            SetAutomationPeerNames(this);
+        }
+
+        // Set the AutomationPeer name to be the same as the x:Name on each FrameworkElement.
+        // This is so we don't need to set both properties on the elements in XAML.
+        void SetAutomationPeerNames(FrameworkElement root)
```
Comment (kmahone) [inline dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs]: Normally, VisualTreeHelper would drill down into the control template parts of the controls that are on the page, which would not be what is desired. However, because the templates are expanded asynchronously after being loaded and this function is called directly from the Page's .ctor, you get the correct behavior. It is probably worth calling this out in a comment, that it should only be called from the .ctor.

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs [hunk 5]
```diff
@@ -269,7 +279,7 @@ void OnFrameArrived(Direct3D11CaptureFramePool sender, object args)
             return await tcs.Task;
         }
 
-        private bool IsRS5OrHigher()
+        static bool IsRS5OrHigher()
         {
```
Comment (kmahone) [inline dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs]: Consider using the helper functions in:
dev\CommonManaged\PlatformConfiguration.cs

PlatformConfiguration.IsOsVersionGreaterThanOrEqual(OSVersion.Redstone5)

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs [hunk 6]
```diff
@@ -12,45 +13,70 @@
...
+        internal static readonly Color RectangleColor = Colors.Red;
+        // Gets the most recently created FallbackGrid
+        internal static FallbackGrid Latest;
+
         public FallbackGrid()
         {
-            _fallbackGrid = this;
-
+            Latest = this;
+            //Background = new SolidColorBrush(Colors.Red);
```
Comment (kmahone) [inline dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs]: Removed commented out code.

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml [hunk 7]
```diff
@@ -15,87 +15,66 @@
...
-                RelativePanel.Below="HittestingTextBox"/>
-            <TextBox x:Name="FallenBackTextBox"
-                IsEnabled="False"
-                AutomationProperties.Name="FallenBackTextBox"
-                Text="None"
-                RelativePanel.Below="FallenBackButton"/>
-            <controls:AnimatedVisualPlayer
+        <Grid.Resources>
+            <Style TargetType="TextBox">
+                <Setter Property="IsEnabled" Value="False" />
```
Comment (kmahone) [inline dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml]: If you want a read-only TextBox, you can use IsReadOnly. Alternatively, use a TextBlock instead of a TextBox.

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs (hunk 4 above)
Comment (kmahone) [reply dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs]: An alternative would be to recursively traverse Panel.Children. This would be less general purpose, but it would mean you avoid walking into the parts of an expanded ControlTemplate.

---
In reply to: [343822102](https://github.com/microsoft/microsoft-ui-xaml/pull/1558#discussion_r343822102) [](ancestors = 343822102)

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml (hunk 7 above)
Comment (simeoncran) [reply dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml]: The TextBoxes are used by the automation tests to indicate state changes. TextBlocks don't fire state changes. By setting IsEnabled=False I get something that looks like a TextBlock (i.e. you can't select it or attempt to edit it) but with the automation behavior that we need. A TextBox that is IsReadOnly looks like a regular text block, and if IsEnabled=False the IsReadOnly is redundant. I'll add a comment.


---
In reply to: [343825146](https://github.com/microsoft/microsoft-ui-xaml/pull/1558#discussion_r343825146) [](ancestors = 343825146)

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs (hunk 6 above)
Comment (simeoncran) [reply dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs]: Done.

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml (hunk 7 above)
Comment (simeoncran) [reply dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml]: Comments added to the code to explain this choice.

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs (hunk 5 above)
Comment (simeoncran) [reply dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs]: Done.

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs (hunk 3 above)
Comment (simeoncran) [reply dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs]: Done.

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs (hunk 4 above)
Comment (simeoncran) [reply dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs]: Done.

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml (hunk 7 above)
Comment (kmahone) [reply dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml]: Thanks for the explanation. That makes sense. I didn't think of the change notifications.

---
In reply to: [344318126](https://github.com/microsoft/microsoft-ui-xaml/pull/1558#discussion_r344318126) [](ancestors = 344318126,343825146)

**Comment by kmahone** [comment]
@simeoncran I have approved this PR. But I am not entirely familiar with the AnimatedVisualPlayer code, so we should wait until @improbabilityphysics has approved before merging.

**Comment by jevansaks** [comment]
@simeoncran was there anything else to do here or should we merge this in?

**Comment by StephenLPeters** [comment]
@jevansaks I think @kmahone and I were hoping that @improbabilityphysics would take a look at the change.

**Comment by improbabilityphysics** [comment]
approved.

**Comment by StephenLPeters** [comment]
> @kmahone and @StephenLPeters, reviewed and approved. Some nit comments should be fine. For test part, the refactoring is a lot, but it looks good. The test design for each scene is invariant. For the pausing animation playing change in AVP destructor to make it more friendly than throwing exception. This change is good. What I can figure out of this scene is that a user forces to click the close button on AVP dialog or page even it is playing. It means this is a reasonable user case that the AVP is still playing even when the running program hits destructor of AVP control.

Thanks @improbabilityphysics !  @simeoncran will you be able to respond to the new feedback?

File: dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (simeoncran) [reply dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp]: DependencyProperty.

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs [hunk 8]
```diff
@@ -12,45 +13,70 @@
...
+            //this.HorizontalAlignment = HorizontalAlignment.Stretch;
+            //this.VerticalAlignment = VerticalAlignment.Stretch;
```
[the remark this answers is not in the document]
Comment (simeoncran) [reply dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs]: Already done on the latest commit.

File: dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs [hunk 9]
```diff
@@ -12,45 +13,70 @@
...
 using Windows.UI.Xaml.Media;
+using Windows.UI.Xaml.Tests.MUXControls.ApiTests;
 
 namespace MUXControlsTestApp
 {
-    public class FallbackGrid : Windows.UI.Xaml.Controls.Grid
+    public sealed class FallbackGrid : Grid
     {
+        internal const int RectangleWidth = 100;
+        internal const int RectangleHeight = 100;
```
[the remark this answers is not in the document]
Comment (simeoncran) [reply dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs]: They would imply the width and height of the FallbackGrid that they are members of, not of the rectangle that is contained in the FallbackGrid.

**Comment by simeoncran** [comment]
@StephenLPeters - this is ready as far as I'm concerned.
