### PR TITLE
Fix issue with cancelled touch pointers not resetting state correctly

### LINKED ISSUE #6863: Long-touching navigation view item would cause the pressed backplate to stay
### Describe the bug

Long touching navigation view item would cause the pressed backplate to stay. Only reproducible with touch. Cannot reproduce with right click.

### Steps to reproduce the bug

1. Launch Xaml Control Gallery
2. Long touch any item until context menu shows up
3. Dismiss the menu.
4. Observe the backplate of the item pressed in (2) remained visible.

### Expected behavior

The backplate disappear after user had lifted his finger from the navigation view item at (3).

### Screenshots
https://user-images.githubusercontent.com/16918354/159270069-6114b012-22f6-481e-b019-5607d3ec1d4d.mp4

### NuGet package version

_No response_

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (22579.1)

### Additional context

XCG version is 1.2.22.0. WinUI version is 2.8.0-prerelease.220118001 (The combo box in the bug report template doesn't have this release yet)

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

When a touch pointer gets cancelled, we expect that there still would be a pointer exited event, however that does not occur. Because of that, when we get pointer cancelled for touch pointers, we should treat this also as a pointer-exited event.
## Motivation and Context

Fixes #6863 
## How Has This Been Tested?

Tested manually.

### CODE REVIEW

File: dev/NavigationView/NavigationViewItem.cpp [hunk 1]
```diff
@@ -1070,7 +1070,8 @@ void NavigationViewItem::ProcessPointerCanceled(const winrt::PointerRoutedEventA
     // What this flag tracks is complicated because of the NavigationView sub items and the m_capturedPointers that are being tracked..
     // We do this check because PointerCaptureLost can sometimes take the place of PointerReleased events.
     // In these cases we need to test if the pointer is over the item to maintain the proper state.
-    if (IsOutOfControlBounds(args.GetCurrentPoint(*this).Position()))
+    // In the case of touch input, we want to cancel anyway since there is not pointer exited for touch events.
```
Comment (roxk) [inline dev/NavigationView/NavigationViewItem.cpp:1073]: From the [doc](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.pointerexited?view=winrt-22000#pointerexited-for-touch-input), pointer exited should have been fired for touch as well. Maybe we should just say "we want to cancel anyway".

Or are there 2 code paths that we need to handle, one for cancelling, one for existing?

Comment (chingucoding) [reply dev/NavigationView/NavigationViewItem.cpp]: Fair point, my comment was not worded entirely correct. So if a pointer is cancelled, in my testing atleast, there won't be a pointer exited. So in the case of touch, we just assume it's gone and we should not stay in the pointer-over mode.

**Review by bpulliam — APPROVED** [review]
