### PR TITLE
Fix issue with flyouts created in CommandBarFlyout not closing when commandbar closes

### LINKED ISSUE #1792: CommandBarFlyout: Submenu persists when CommandBar closes
**Describe the bug**

When closing a CommandBarFlyout while a submenu is open that belongs the the CommandBarFlyout, the SubMenu is still visible.
**Steps to reproduce the bug**

1. Open MUXControlsTestApp
2. Go to "Base CommandBarFlyout Tests"
3. Press "Show CommandBarFlyout with sub-menu" and open the Submenu
4. Click outside the COmmandBarFlyout and submenu 

**Expected behavior**

The submenu disappears with the CommandBarFlyout.
**Screenshots**

commandbarflyout-submenu-bug

**Version Info**

NuGet package version: 

Latest commit on master.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19536)              | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

The code that closed the flyouts was only run when there were animations, which is a bug if animations are disabled as we leave flyouts open while the CommandBarFlyout is not open anymore.

Thanks @llongley for the pointer in that area!

## Motivation and Context

Fixes #1792 
## How Has This Been Tested?

Add new interaction test.

### CODE REVIEW

File: dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs [hunk 1]
```diff
@@ -620,5 +620,48 @@ public void VerifyFlowsToAndFromIsNotSetWithoutPrimaryCommands()
...
+                if (PlatformConfiguration.IsOsVersionGreaterThanOrEqual(OSVersion.Redstone5))
+                {
+                    Log.Comment("Expanding the CommandBar by invoking the more button.");
+                    FindElement.ById<Button>("MoreButton").InvokeAndWait();
+                }
+
+                // Move around over item to open flyout
+                PointerInput.Move(FindElement.ById("ProofingButton"), 5, 5);
+                PointerInput.Move(FindElement.ById("ProofingButton"), 6, 5);
+                PointerInput.Move(FindElement.ById("ProofingButton"), 5, 6);
```
Comment (StephenLPeters) [inline dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs:651]: I made a change yesterday that would allow you to replace this with a click if you wanted to

Comment (chingucoding) [reply dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs:651]: Oh right, yes. I don't think there is much benefit in updating this, but I'll use it next time when I write a test in this area.

**Comment by chingucoding** [comment]
There was a test failure, hopefully it is fixed with the latest changes.
