### PR TITLE
StackLayout incorrect sizing bug

### LINKED ISSUE #2071: StackLayout incorrect sizing
**Describe the bug**
Calling Measure on StackLayout multiple times before Arrange causes it to size itself based on the largest element size it sees across the multiple Measure calls. This can result in it getting sized incorrectly when the available size differs across the measure calls.

**Steps to reproduce the bug**
Place a repeater with children using a default StackLayout into a limited size parent. Call measure on the repeater with an AvailableSize of something larger than the parent's width. Trigger a layout update. Observe that the width of the repeater will be sized to what was passed in using the manual measure call, not it's parents max width.

**Expected behavior**
Repeater should be sized to the available size that is provided by the last measure call.

### PR DESCRIPTION
**Pull request by ojhad**
Fixes #2071 

## Description
Calling Measure on StackLayout multiple times before Arrange causes it to size itself based on the largest element size it sees across the multiple Measure calls. Made a change so that this max size is calculated for every individual measure call.

## Motivation and Context
This bug can results in items getting sized incorrectly when the available size differs across the measure calls.

## How Has This Been Tested?
Added an API test

### CODE REVIEW

File: dev/Repeater/APITests/LayoutTests.cs [hunk 1]
```diff
@@ -192,6 +192,33 @@ public void ValidateNonVirtualLayoutDoesNotGetMeasuredForViewportChanges()
...
         }
 
+        [TestMethod]
+        public void ValidateStackLayoutDoesNotRetainIncorrectMinorWidth()
+        {
+            RunOnUIThread.Execute(() =>
+            {
+                var repeater = new ItemsRepeater();
+                var stackLayout = new StackLayout();
+                repeater.Layout = stackLayout;
```
Comment (ranjeshj) [inline dev/Repeater/APITests/LayoutTests.cs]: This is the default, so not needed

File: dev/Repeater/APITests/LayoutTests.cs [hunk 2]
```diff
@@ -192,6 +192,33 @@ public void ValidateNonVirtualLayoutDoesNotGetMeasuredForViewportChanges()
             });
         }
 
+        [TestMethod]
+        public void ValidateStackLayoutDoesNotRetainIncorrectMinorWidth()
+        {
+            RunOnUIThread.Execute(() =>
+            {
+                var repeater = new ItemsRepeater();
```
Comment (ranjeshj) [inline dev/Repeater/APITests/LayoutTests.cs]: Can simplify this a little bit using initializer syntax, and removing the layout part since that is the default. You likely do not need the ScrollViewer for this either.

var repeater = new ItemsRepeater()
{
    ItemsSource = Enumerable.Range(0,1),
    ItemTemplate = ...
};

Content = repeater;
Content.UpdateLayout();

repeater.Measure(new Size(600, 100));
Verify.AreEqual(repeater.ActualSize.X, 600);
repeater.Measure(new Size(300, 100));
Verify.AreEqual(repeater.DesiredSize.X, 300);
repeater.Arrange(new Size(300, 100));
Verify.AreEqual(repeater.ActualSize.X, 300);

The check is also reversed, you want to measure with large size and then a smaller size before the arrange pass.

File: dev/Repeater/APITests/LayoutTests.cs [hunk 3]
```diff
@@ -192,6 +192,33 @@ public void ValidateNonVirtualLayoutDoesNotGetMeasuredForViewportChanges()
...
+                         <Button Content='{Binding}' Height='100' />
+                    </DataTemplate>");
+                var scrollViewer = new ScrollViewer() {
+                    Content = repeater
+                };
+                scrollViewer.Width = 300;
+                Content = scrollViewer;
+                Content.UpdateLayout();
+
+                repeater.Measure(new Size(600, 100));
```
Comment (StephenLPeters) [inline dev/Repeater/APITests/LayoutTests.cs]: I think you need to perform multiple measure's before calling UpdateLayout to reproduce the issue.

Comment (ojhad) [reply dev/Repeater/APITests/LayoutTests.cs]: UpdateLayout results in another Measure call (with the proper sizing). When running this test without the fix, the repeater was being sized to 600 erroneously as a result.

File: dev/Repeater/APITests/LayoutTests.cs [hunk 4]
```diff
@@ -192,6 +192,33 @@ public void ValidateNonVirtualLayoutDoesNotGetMeasuredForViewportChanges()
...
+                Content.UpdateLayout();
+
+                Verify.AreEqual(repeater.ActualSize.X, 300);
```
Comment (StephenLPeters) [inline dev/Repeater/APITests/LayoutTests.cs]: UIElement.ActualSize was added in 19h1, it actually a facade to the underlying visual's size. You should be using FrameworkElements.ActualWidth as what you have will crash on earlier OS versions.

Comment (ranjeshj) [reply dev/Repeater/APITests/LayoutTests.cs]: Good catch.

File: dev/Repeater/APITests/LayoutTests.cs (hunk 3 above)
Comment (ranjeshj) [reply dev/Repeater/APITests/LayoutTests.cs]: UpdateLayout will run measure/arrange - It might be best to avoid calling UpdateLayout and instead just call measure/arrange directly on the element. DesiredSize should reflect changes after Measure and ActualWidth should get updated after Arrange call.

Comment (ojhad) [reply dev/Repeater/APITests/LayoutTests.cs]: Manually calling Measure and Arrange for some reason does not update the ActualWidth property. Only by calling UpdateLayout I managed to get the ActualWidth property updated.

File: dev/Repeater/APITests/LayoutTests.cs (hunk 2 above)
Comment (ojhad) [reply dev/Repeater/APITests/LayoutTests.cs]: Updated. I kept the scrollviewer for now in order to substitute for the second smaller size measure call before the arrange pass happens (due to the reason I mention [here](https://github.com/microsoft/microsoft-ui-xaml/pull/2072#discussion_r389901958)).
