### PR TITLE
Fix issue with TabView crashing in a NavigationCacheMode=Required page

### LINKED ISSUE #1245: TabView crashed on second Loaded event
**Describe the bug**
TabView crashed on second Loaded event if databound, duplicates count of tab items if not databound.

**Steps to reproduce the bug**

[TabViewCrash.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3559853/TabViewCrash.zip)
1. Unzip, build and run attached TabViewCrash project
2. Click on 'Navigate Forward from MainPage to TestPage' button.
There would be databound TabView with "Tab 1" and "Tab 2" tabs,
and another not databound one with "Tab 11" and "Tab 12" tabs.
Note that width of tabs is not equal - separate issue.
3. Click on 'Navigate Backward from TestPage to MainPage' button.
4. Click on 'Navigate Forward from MainPage to TestPage' button again
Crash in TabView::OnListViewLoaded for databound TabView.
If first databound TabView would be commented out - there would be no crash, but tab count of second TabView would be duplicated.

**Expected behavior**
Results of second navigation to TestPage results should be the same as results of first navigation, i.e.
there should be databound TabView with "Tab 1" and "Tab 2" tabs,
and another not databound one with "Tab 11" and "Tab 12" tabs.

**Screenshots**
TabViewCrashScreenshot

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.2.190822001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes  |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
Note, that page with TabView had NavigationCacheMode=Required, that caused unloading and reloading without destruction.

### PR DESCRIPTION
**Pull request by MuziburRahman**
## Description

When the `TabView` is in a `Page` which has `NavigationCacheMode = "Required"`, it'd cause the app to crash. Because, in the `Loaded`  event of the `ListView`, the previous code would always add the current `TabItems` of the `TabView`, but it is necessary to check whether the `Items` being added have already been added before. As it didn't check that, it would crash in the second loaded event.

Fixes #1245 

## How Has This Been Tested?
I used the MUXControlTestApp to test the changes. I set the `NavigationCacheMode="Required"` of the *TabViewPage* and navigated back and forth to ensure it doesn't crash anymore, as it would before.

### CODE REVIEW

File: dev/TabView/TabView.cpp [hunk 1]
```diff
@@ -233,14 +233,42 @@ void TabView::OnListViewLoaded(const winrt::IInspectable&, const winrt::RoutedEv
         // Now that ListView exists, we can start using its Items collection.
         auto items = TabItems();
         auto numItemsToCopy = static_cast<int>(items.Size());
-        if (auto lvItems = listView.Items())
+        bool itemsSourceDoesNotExists = listView.ItemsSource() == nullptr;
```
Comment (jevansaks) [inline dev/TabView/TabView.cpp]: [Don't add unnecessary "== nullptr"](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es87-dont-add-redundant--or--to-conditions):

```suggestion
        bool itemsSourceDoesNotExists = !listView.ItemsSource();
```

But also I'd avoid the local and just put this check in the if condition below.

Comment (StephenLPeters) [reply dev/TabView/TabView.cpp]:
```
if(!listView.ItemsSource())
```

---
In reply to: [338187053](https://github.com/microsoft/microsoft-ui-xaml/pull/1482#discussion_r338187053) [](ancestors = 338187053)

Comment (StephenLPeters) [inline dev/TabView/TabView.cpp]: move these local definitions into the if block

File: dev/TabView/TabView.cpp [hunk 2]
```diff
@@ -233,14 +233,42 @@ void TabView::OnListViewLoaded(const winrt::IInspectable&, const winrt::RoutedEv
...
+
+        if (itemsSourceDoesNotExists)
+        {
+            if (auto lvItems = listView.Items())
+            {
+                // copy the list, because clearing lvItems may also clear items
+                winrt::IVector<winrt::IInspectable> item_list{ winrt::single_threaded_vector<winrt::IInspectable>() };
+
+                for (auto itm : items)
```
Comment (StephenLPeters) [inline dev/TabView/TabView.cpp]: >auto itm [](start = 21, length = 8)

prefer defining locals as const when possible.

File: dev/TabView/TabView.cpp [hunk 3]
```diff
@@ -233,14 +233,42 @@ void TabView::OnListViewLoaded(const winrt::IInspectable&, const winrt::RoutedEv
...
+                {
+                    item_list.Append(itm);
+                }
+
+                lvItems.Clear();
+
+                for (int i = 0; i < numItemsToCopy; i++)
```
Comment (StephenLPeters) [inline dev/TabView/TabView.cpp]: >for (int i = 0; i < numItemsToCopy; i++) [](start = 16, length = 40)

for (auto const item : item_list)
{
    if(item)
    {
        lvItems.Append(item);
    }
}

File: dev/TabView/TabView.cpp [hunk 4]
```diff
@@ -233,14 +233,42 @@ void TabView::OnListViewLoaded(const winrt::IInspectable&, const winrt::RoutedEv
...
         auto numItemsToCopy = static_cast<int>(items.Size());
-        if (auto lvItems = listView.Items())
+        bool itemsSourceDoesNotExists = listView.ItemsSource() == nullptr;
+
+        if (itemsSourceDoesNotExists)
+        {
+            if (auto lvItems = listView.Items())
+            {
+                // copy the list, because clearing lvItems may also clear items
+                winrt::IVector<winrt::IInspectable> item_list{ winrt::single_threaded_vector<winrt::IInspectable>() };
```
Comment (StephenLPeters) [inline dev/TabView/TabView.cpp]: >item_list [](start = 52, length = 9)

I suggest the name itemList, which more closely matches how we name our locals in this project.

File: dev/TabView/TabView.cpp [hunk 5]
```diff
@@ -233,14 +233,42 @@ void TabView::OnListViewLoaded(const winrt::IInspectable&, const winrt::RoutedEv
...
+
+            for (auto itm : itemsSource)
             {
-                // App put items in our Items collection; copy them over to ListView.Items
-                lvItems.Append(items.GetAt(i));
+                item_list.Append(itm);
             }
-            TabItems(lvItems);
+            TabItems(item_list);
         }
```
Comment (StephenLPeters) [inline dev/TabView/TabView.cpp]: Why is this needed? can't we just do `TabItems(listView.ItemsSource())` since at this point we are sure that the items source exists

File: dev/TabView/TabView.cpp [hunk 6]
```diff
@@ -233,14 +233,42 @@ void TabView::OnListViewLoaded(const winrt::IInspectable&, const winrt::RoutedEv
...
+            winrt::IVector<winrt::IInspectable> item_list{ winrt::single_threaded_vector<winrt::IInspectable>() };
+
+            for (auto itm : itemsSource)
             {
-                // App put items in our Items collection; copy them over to ListView.Items
-                lvItems.Append(items.GetAt(i));
+                item_list.Append(itm);
             }
-            TabItems(lvItems);
+            TabItems(item_list);
```
Comment (teaP) [inline dev/TabView/TabView.cpp]: I'm not quite understanding this "else if" block. If there is an ItemsSource, why are we copying those items into TabItems? TabItems is no longer the same as ListView.Items?

File: dev/TabView/TabView.cpp (hunk 5 above)
Comment (MuziburRahman) [reply dev/TabView/TabView.cpp]: I wish I could do that, but apparently it creates an error since the `TabItems` property only accepts `IVector<>` and Idon't know what type of object is that `ItemsSource` . So I had to make sure it's iterable , then make an `IVector<>` from it and pass it as the parameter.

File: dev/TabView/TabView.cpp (hunk 6 above)
Comment (MuziburRahman) [reply dev/TabView/TabView.cpp]: You are right, actually the else part is unnecessary. Thanks.

File: dev/TabView/TabView.cpp (hunk 5 above)
Comment (MuziburRahman) [reply dev/TabView/TabView.cpp]: I have deleted the else block, since it's unnecessary.

File: dev/TabView/TabView.cpp [hunk 7]
```diff
@@ -231,16 +231,32 @@ void TabView::OnListViewLoaded(const winrt::IInspectable&, const winrt::RoutedEv
...
+                    itemList.Append(item);
+                }
+
+                lvItems.Clear();
+
+                for (auto const item : itemList)
+                {
+                    // App put items in our Items collection; copy them over to ListView.Items
+                    if (item)
+                        lvItems.Append(item);
```
Comment (StephenLPeters) [inline dev/TabView/TabView.cpp]:
```
if (item)
{
    lvItems.Append(item);
}
```

by rule we don't allow if blocks without braces

File: dev/TabView/TabView.cpp [hunk 8]
```diff
@@ -231,16 +231,32 @@ void TabView::OnListViewLoaded(const winrt::IInspectable&, const winrt::RoutedEv
...
+        
+        if (!listView.ItemsSource())
         {
-            for (int i = 0; i < numItemsToCopy; i++)
+            if (auto const lvItems = listView.Items())
             {
-                // App put items in our Items collection; copy them over to ListView.Items
-                lvItems.Append(items.GetAt(i));
+                auto items = TabItems();
+                auto numItemsToCopy = static_cast<int>(items.Size());
```
Comment (StephenLPeters) [inline dev/TabView/TabView.cpp]: >auto numItemsToCopy = static_cast<int>(items.Size()); [](start = 16, length = 53)

This isn't used anymore, please delete it

File: dev/TabView/TabView.cpp [hunk 9]
```diff
@@ -231,16 +231,32 @@ void TabView::OnListViewLoaded(const winrt::IInspectable&, const winrt::RoutedEv
...
-        if (auto lvItems = listView.Items())
+        
+        if (!listView.ItemsSource())
         {
-            for (int i = 0; i < numItemsToCopy; i++)
+            if (auto const lvItems = listView.Items())
             {
-                // App put items in our Items collection; copy them over to ListView.Items
-                lvItems.Append(items.GetAt(i));
+                auto items = TabItems();
```
Comment (StephenLPeters) [inline dev/TabView/TabView.cpp]: Since this local is only ever used in the for loop declaration can we delete it and change the declaration to `for (auto const item : TabItems())`

File: dev/TabView/TabView.cpp [hunk 10]
```diff
@@ -231,16 +231,32 @@ void TabView::OnListViewLoaded(const winrt::IInspectable&, const winrt::RoutedEv
     if (auto listView = m_listView.get())
     {
         // Now that ListView exists, we can start using its Items collection.
-        auto items = TabItems();
-        auto numItemsToCopy = static_cast<int>(items.Size());
-        if (auto lvItems = listView.Items())
+        
+        if (!listView.ItemsSource())
```
Comment (teaP) [inline dev/TabView/TabView.cpp]: I am concerned about this not happening if there is an ItemsSource. In that case, there shouldn't be an TabViewItems to copy over, but we would still want TabItems to be set to lvItems so that the app has access to those items.

Comment (MuziburRahman) [reply dev/TabView/TabView.cpp]: That's why the else block was necessary, right? I was confused by your earlier review. 😃

File: dev/TabView/TabView.cpp (hunk 6 above)
Comment (MuziburRahman) [reply dev/TabView/TabView.cpp]: https://github.com/microsoft/microsoft-ui-xaml/pull/1482#discussion_r338765792

File: dev/TabView/TabView.cpp [hunk 11]
```diff
@@ -231,16 +231,43 @@ void TabView::OnListViewLoaded(const winrt::IInspectable&, const winrt::RoutedEv
...
+                    {
+                        lvItems.Append(item);
+                    }
+                }
+                TabItems(lvItems);
+            }
+        }
+
+        // if there is an itemsSource, we need to copy the values to TabItems, so that they are also accessible by TabItems property
+        else if (auto itemsSource = listView.ItemsSource().try_as<winrt::IIterable<winrt::IInspectable>>())
```
Comment (StephenLPeters) [inline dev/TabView/TabView.cpp]: >auto [](start = 17, length = 4)

const

File: dev/TabView/TabView.cpp (hunk 10 above)
Comment (teaP) [reply dev/TabView/TabView.cpp]: Sorry if I wasn't clear! I think an else block is necessary, but I think it should do something different. :) The TabView.TabItemsSource is bound directly to ListView.ItemsSource, so the owner of TabView already has access to those items (and was the one who provided them) -- TabView.TabItems should be a list of the realized TabViewItems, not the data items. So in the case where there's an ItemsSource, probably we just need to set TabView.TabItems = ListView.Items so that the owner can access the realized TabViewItems that ListView generates. Does that make sense?

Comment (MuziburRahman) [reply dev/TabView/TabView.cpp]: Understood.
So the `TabItems(lvItems)` part should be executed in both case. Then, how about this code: 
```
if (auto const lvItems = listView.Items())
{
	if (!listView.ItemsSource())
	{
		winrt::IVector<winrt::IInspectable> const itemList{ winrt::single_threaded_vector<winrt::IInspectable>() };

		for (auto const item : TabItems())
		{
			itemList.Append(item);
		}

		lvItems.Clear();

		for (auto const item : itemList)
		{
			if (item)
			{
				lvItems.Append(item);
			}
		}
	}

	TabItems(lvItems);
}
```

Comment (teaP) [reply dev/TabView/TabView.cpp]: I like it!!

**Comment by jevansaks** [comment]
Nit: I edited the title of this PR to be more descriptive.
