### PR TITLE
ProgressRing Automation Peer 

### LINKED ISSUE #2049: ProgressRing get's announced as image
**Describe the bug**

Using narrator, the ProgressRing get's announced as image, not as ProgressRing with a percentage.

**Steps to reproduce the bug**

1. Start Narrator
2. Open MUXControlsTestApp
3. Navigate to ProgressRing page
4. Tab to the ProgressRing, oberserve that it gets anounced as image.

**Expected behavior**

When the progressring is indeterminate, it should get announced as "busy progressring", otherwise it should announce it's progress like the ProgressBar 

**Screenshots**

**Version Info**

NuGet package version: 

Latest commit on master

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19596)              | Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

When opening the XAML Controls Gallery, the ProgressRing gets announced correctly.

### PR DESCRIPTION
**Pull request by karenbtlai**
## Description

Implement AutomationPeer for ProgressRing so that it announces the progress percentage.

## Motivation and Context

Fixes #2049 

## How Has This Been Tested?

Manually checks behaviour with Narrator

### CODE REVIEW

File: dev/ProgressRing/ProgressRingAutomationPeer.h [hunk 1]
```diff
@@ -0,0 +1,32 @@
+﻿// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT License. See LICENSE in the project root for license information.
+
+#pragma once
+
+#include "ProgressRing.h"
+#include "ProgressRingAutomationPeer.g.h"
+
+class ProgressRingAutomationPeer :
+    public ReferenceTracker<ProgressRingAutomationPeer, winrt::implementation::ProgressRingAutomationPeerT, winrt::IRangeValueProvider>
```
Comment (ranjeshj) [inline dev/ProgressRing/ProgressRingAutomationPeer.h]: Do we not get IRangeValueProvider from RangeBaseAutomationPeer ?

**Comment by chingucoding** [comment]
When setting the ProgressRing IsIndeterminate to true, it get's announced as "x %, ProgressBar". We currently have the same behavior for the ProgressBar, however that is also a bug as discussed by #1746 .

A way to fix this would be to override `GetNameCore` in ProgressRingAutomationPeer, however in that case we need to add a resource to localize that correctly.

**Comment by ranjeshj** [comment]
> When setting the ProgressRing IsIndeterminate to true, it get's announced as "x %, ProgressBar". We currently have the same behavior for the ProgressBar, however that is also a bug as discussed by #1746 .
> 
> A way to fix this would be to override `GetNameCore` in ProgressRingAutomationPeer, however in that case we need to add a resource to localize that correctly.

@YuliKl as FYI. I believe this is the default behavior for the windows progress bar as well, but this sounds like a good time to fix this.

**Comment by karenbtlai** [comment]
> > When setting the ProgressRing IsIndeterminate to true, it get's announced as "x %, ProgressBar". We currently have the same behavior for the ProgressBar, however that is also a bug as discussed by #1746 .
> > A way to fix this would be to override `GetNameCore` in ProgressRingAutomationPeer, however in that case we need to add a resource to localize that correctly.
> 
> @YuliKl as FYI. I believe this is the default behavior for the windows progress bar as well, but this sounds like a good time to fix this. What should it say ? Something like "Busy" ?

I believe we established it to say "Busy [ControlType]". I think it's a good time to fix it thus will start on that.

**Comment by chingucoding** [comment]
The behavior of the WUXC ProgressRing was to announce "Busy ProgressRing, x% percent". Would it be better leave it that way and still make use of IValueRangeProvider, as it might be better for screenreaders?

**Comment by chingucoding** [comment]
From what I could observe, it seems implementing IValueRangeProvider and GetNameCore result in the Indeterminate ProgressRing/Bar being announced as "Busy ProgressBar, 0% progress".

File: dev/ProgressBar/ProgressBarAutomationPeer.cpp [hunk 2]
```diff
@@ -18,6 +18,14 @@ ProgressBarAutomationPeer::ProgressBarAutomationPeer(winrt::ProgressBar const& o
 // IAutomationPeerOverrides
 winrt::IInspectable ProgressBarAutomationPeer::GetPatternCore(winrt::PatternInterface const& patternInterface)
 {
+    if (auto progressBar = Owner().try_as<winrt::ProgressBar>())
+    {
+        if (progressBar.IsIndeterminate())
+        {
+            return nullptr;
```
Comment (ranjeshj) [inline dev/ProgressBar/ProgressBarAutomationPeer.cpp]: For indeternminate progress bar, we will end up not supporting any other patterns with this return. I think what we need is to make the check inside the if block below for RangeValue pattern and not return *this if it is an indeterminate progressbar.

File: dev/ProgressBar/ProgressBarAutomationPeer.cpp [hunk 3]
```diff
@@ -31,6 +39,29 @@ hstring ProgressBarAutomationPeer::GetClassNameCore()
     return winrt::hstring_name_of<winrt::ProgressBar>();
 }
 
+winrt::hstring ProgressBarAutomationPeer::GetNameCore()
+{
+    //Check to see if the item has a defined AutomationProperties.Name
+    winrt::hstring name = __super::GetNameCore();
```
Comment (ranjeshj) [inline dev/ProgressBar/ProgressBarAutomationPeer.cpp]: what do we get as name if AutomationProperties.Name is not set ?

File: dev/ProgressBar/ProgressBarAutomationPeer.cpp [hunk 4]
```diff
@@ -31,6 +39,29 @@ hstring ProgressBarAutomationPeer::GetClassNameCore()
...
+
+    if (auto progressRing = Owner().try_as<winrt::ProgressBar>())
```
Comment (ranjeshj) [inline dev/ProgressBar/ProgressBarAutomationPeer.cpp]: >progressRing [](start = 13, length = 12)

progressBar

**Comment by ranjeshj** [comment]
>     void SetValue(double value);

don't need these if we remove IRangeValueProvider...

---
Refers to: dev/ProgressBar/ProgressBarAutomationPeer.h:28 in 24f6283. [](commit_id = 24f628325fb7196a108db6ff0fdf590457b25b9e, deletion_comment = False)

File: dev/ProgressRing/ProgressRingAutomationPeer.h [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+    winrt::hstring GetNameCore();
+    winrt::AutomationControlType GetAutomationControlTypeCore();
+
+    bool IsReadOnly() { return true; }
+    double Value();
+    double SmallChange();
+    double LargeChange();
+    double Minimum();
+    double Maximum();
+    void SetValue(double value);
```
Comment (ranjeshj) [inline dev/ProgressRing/ProgressRingAutomationPeer.h]: can remove these

File: dev/ProgressRing/ProgressRingAutomationPeer.cpp [hunk 6]
```diff
@@ -0,0 +1,103 @@
...
+}
+
+// IAutomationPeerOverrides
+winrt::IInspectable ProgressRingAutomationPeer::GetPatternCore(winrt::PatternInterface const& patternInterface)
+{
+    if (auto progressRing = Owner().try_as<winrt::ProgressRing>())
+    {
+        if (progressRing.IsIndeterminate())
+        {
+            return nullptr;
```
Comment (ranjeshj) [inline dev/ProgressRing/ProgressRingAutomationPeer.cpp]: same issue as ProgressBar

File: dev/ProgressBar/ProgressBarAutomationPeer.cpp (hunk 3 above)
Comment (chingucoding) [reply dev/ProgressBar/ProgressBarAutomationPeer.cpp]: We get an `winrt::hstring` whose` m_handle` is `0x0`. This results in no problems when using/returning.

File: dev/ProgressRing/ProgressRingAutomationPeer.h (hunk 1 above)
Comment (karenbtlai) [reply dev/ProgressRing/ProgressRingAutomationPeer.h]: removed

**Comment by StephenLPeters** [comment]
>     return __super::GetPatternCore(patternInterface);

```
    if (patternInterface == winrt::PatternInterface::RangeValue)
    {
        if (auto progressBar = Owner().try_as<winrt::ProgressBar>())
        {
            if (progressBar.IsIndeterminate())
            {
                return __super::GetPatternCore(patternInterface);
            }
        }
        return *this;
    }

    return __super::GetPatternCore(patternInterface);
```

---
Refers to: dev/ProgressBar/ProgressBarAutomationPeer.cpp:34 in 24f6283. [](commit_id = 24f628325fb7196a108db6ff0fdf590457b25b9e, deletion_comment = False)

**Comment by StephenLPeters** [comment]
>     void SetValue(double value);

really? we still report as an IRangeValueProvider while in the determinate state

---
In reply to: [595800728](https://github.com/microsoft/microsoft-ui-xaml/pull/2065#issuecomment-595800728) [](ancestors = 595800728)

---
Refers to: dev/ProgressBar/ProgressBarAutomationPeer.h:28 in 24f6283. [](commit_id = 24f628325fb7196a108db6ff0fdf590457b25b9e, deletion_comment = False)

File: dev/ProgressRing/ProgressRingAutomationPeer.cpp [hunk 7]
```diff
@@ -0,0 +1,103 @@
...
+com_ptr<ProgressRing> ProgressRingAutomationPeer::GetImpl()
+{
+    com_ptr<ProgressRing> impl = nullptr;
+
+    if (auto progressRing = Owner().try_as<winrt::ProgressRing>())
+    {
+        impl = winrt::get_self<ProgressRing>(progressRing)->get_strong();
+    }
+
+    return impl;
```
Comment (StephenLPeters) [inline dev/ProgressRing/ProgressRingAutomationPeer.cpp]:
```
    if (auto progressRing = Owner().try_as<winrt::ProgressRing>())
    {
        return winrt::get_self<ProgressRing>(progressRing)->get_strong();
    }

    return nullptr;
```

File: dev/ProgressRing/ProgressRingAutomationPeer.cpp [hunk 8]
```diff
@@ -0,0 +1,103 @@
...
+        {
+            return winrt::hstring{ ResourceAccessor::GetLocalizedStringResource(SR_ProgressRingIndeterminateStatus) + name };
+        }
+    }
+    return name;
+}
+
+winrt::AutomationControlType ProgressRingAutomationPeer::GetAutomationControlTypeCore()
+{
+    return winrt::AutomationControlType::ProgressBar;
```
Comment (StephenLPeters) [inline dev/ProgressRing/ProgressRingAutomationPeer.cpp]: >ProgressBar [](start = 41, length = 11)

Is there a Ring option for this?

Comment (karenbtlai) [reply dev/ProgressRing/ProgressRingAutomationPeer.cpp]: There isn't a ProgressRing option it seems. In the WUXC version, the AutomationControlType returns ProgressBar, as well.

File: dev/ProgressRing/ProgressRingAutomationPeer.cpp [hunk 9]
```diff
@@ -0,0 +1,60 @@
...
+        if (auto progressRing = Owner().try_as<winrt::ProgressRing>())
+        {
+            if (progressRing.IsIndeterminate())
+            {
+                return nullptr;
+            }
+        }
+
+        return *this;
+    }
```
Comment (ranjeshj) [inline dev/ProgressRing/ProgressRingAutomationPeer.cpp]: Lets not try to make this change since there is an issue with Narrator reacting to changing this pattern at runtime. (Spec bug filed on Narrator). You can add a comment here about the issue. The problem is that Narrator caches the patterns and does not react to the list of patterns changing at runtime. Which means if we start in indeterminate state and then switch to determinate, we will end up not reading the percentages which sounds worse than reading the 0% in indeterminate case. (which we have lived with all along)

File: dev/ProgressRing/ProgressRingAutomationPeer.h [hunk 10]
```diff
@@ -0,0 +1,26 @@
...
+public:
+    ProgressRingAutomationPeer(winrt::ProgressRing const& owner);
+
+    // IAutomationPeerOverrides
+    winrt::IInspectable GetPatternCore(winrt::PatternInterface const& patternInterface);
+    hstring GetClassNameCore();
+    winrt::hstring GetNameCore();
+    winrt::AutomationControlType GetAutomationControlTypeCore();
+
+    bool IsReadOnly() { return true; }
```
Comment (ranjeshj) [inline dev/ProgressRing/ProgressRingAutomationPeer.h]: I dont see this used anywhere.

Comment (chingucoding) [reply dev/ProgressRing/ProgressRingAutomationPeer.h]: Maybe this is/was needed for the IValueRangeProvider to indicate that users can not change that progress?

File: dev/ProgressRing/ProgressRingAutomationPeer.cpp (hunk 8 above)
Comment (chingucoding) [reply dev/ProgressRing/ProgressRingAutomationPeer.cpp]: Than I think that's an acceptable solution. From a UIA perspective they are essentially the same. The only real difference is the shape/visuals.

For semantic understanding of the control, users need to know that it indicates progress, and that is what we achieve.

File: dev/ProgressRing/ProgressRingAutomationPeer.h (hunk 10 above)
Comment (karenbtlai) [reply dev/ProgressRing/ProgressRingAutomationPeer.h]: @chingucoding You are right! Turns out `IRangeValueProvider` was necessary to override `IsReadOnly()` to `true`. `IRanveValueProvider` has been re-added.

File: dev/ProgressBar/Resources.resw [hunk 11]
```diff
@@ -0,0 +1,132 @@
...
+  <!-- 
+    Microsoft ResX Schema 
+    
+    Version 2.0
+    
+    The primary goals of this format is to allow a simple XML format 
+    that is mostly human readable. The generation and parsing of the 
+    various data types are done through the TypeConverter classes 
+    associated with the data types.
+
```
Comment (ranjeshj) [inline dev/ProgressBar/Resources.resw]: The resw file needs to be under String\en-us folder. Please see TabView as an example.

**Comment by chingucoding** [comment]
:shipit:
