### PR TITLE
Fix element already in tree crash in nested repeater scenario

### LINKED ISSUE #428: ’Element is already the child of another element' exception when navigating pages
**Describe the bug**
When navigating back and forth from a page hosing a repeater, we seem to hit an exception saying 'Element is already the child of another element'. 

**Steps to reproduce the bug**
Try navigating back and forth in the ItemsView sample. This is not a consistent repro.
TBD: partner has hit this as well- I'm trying to get a more consistent repro.

**Expected behavior**
No crash

### PR DESCRIPTION
**Pull request by ranjeshj**
An incorrect usage of assert caused release builds to remove the wrong element from the children collection. I added a unit and integration test as well.

Fixes #428

### CODE REVIEW

File: dev/Repeater/RecyclePool.cpp [hunk 1]
```diff
@@ -104,7 +104,12 @@ winrt::UIElement RecyclePool::TryGetElementCore(
                 if (panel)
                 {
                     unsigned int childIndex = 0;
-                    MUX_ASSERT(panel.Children().IndexOf(elementInfo.Element(), childIndex));
+                    bool found = panel.Children().IndexOf(elementInfo.Element(), childIndex);
+                    if (!found)
+                    {
+                        throw winrt::hresult_error(E_FAIL, L"Repeater's child not found in its Children collection.");
```
Comment (RBrid) [inline dev/Repeater/RecyclePool.cpp]: Repeater's ==> ItemRepeater's

File: dev/Repeater/APITests/RepeaterTests.cs [hunk 2]
```diff
@@ -168,5 +170,72 @@ public void ValidateGetSetBackground()
                 Verify.AreSame(blueBrush, repeater.Background);
             });
         }
+
+        [TestMethod]
+        public void NestedRepeaterWithDataTemplateScenario()
```
Comment (chrisglein) [inline dev/Repeater/APITests/RepeaterTests.cs]: There aren't any comments in this function and the name is pretty generic sounding. I wasn't sure what it was supposed to... do.

File: dev/Repeater/APITests/RepeaterTests.cs [hunk 3]
```diff
@@ -168,5 +170,72 @@ public void ValidateGetSetBackground()
...
+                rootRepeater.ItemsSource = itemsSource;
+                Content = anchorProvider;
+            });
+
+            for (int i = 1; i < 10; i++)
+            {
+                IdleSynchronizer.Wait();
+                RunOnUIThread.Execute(() =>
+                {
+                    scrollViewer.ChangeView(null, i * 200, null);
```
Comment (chrisglein) [inline dev/Repeater/APITests/RepeaterTests.cs]: Maybe give (i * 200) a friendly variable name so it's more obvious what this is doing/validating.
