### PR TITLE
Fixed NavigationView on launch pane state

### LINKED ISSUE #1430: NavigationView in Compact mode launches with pane opened
**Describe the bug**

Related to #1186, NavigationView shows incorrect behavior on app launch in Compact (and LeftCompact) mode.

**Steps to reproduce the bug**

1. Create a test app with this code snippet
```xaml
<mux:NavigationView>
    <mux:NavigationView.MenuItems>
        <mux:NavigationViewItem Icon="Play" Content="Menu Item1" Tag="SamplePage1" />
        <mux:NavigationViewItem Icon="Save" Content="Menu Item2" Tag="SamplePage2" />
    </mux:NavigationView.MenuItems>
    <Frame x:Name="contentFrame"/>
</mux:NavigationView>
```
2. Launch the app and resize its window to a medium width so a narrow sliver of NavigationView is showing.
3. Restart the app.
4. Alternatively, force NavigationView into LeftCompact mode.
```xaml
<mux:NavigationView PaneDisplayMode="LeftCompact">
```
5. Or make NavigationView LeftMinimal.
```xaml
<mux:NavigationView PaneDisplayMode="LeftMinimal">
```

**Expected behavior**

The Pane remains closed until user presses the hamburger button (or resizes the app into Expanded DisplayMode).

### PR DESCRIPTION
**Pull request by ojhad**
## Description
When an app with NavigationView launches straight into LeftCompact and LeftMinimal mode, the pane is open by default. The expected behavior is for it to be initially closed, made changes to reflect this.

## Motivation and Context
Fixes #1430 

## How Has This Been Tested?
Added validation for LeftCompact and LeftMinimal scenarios to an existing relevant test.
Verified that an app launching into these pane states no longer have the pane open by default.

### CODE REVIEW

File: dev/NavigationView/NavigationView.cpp [hunk 1]
```diff
@@ -585,7 +585,8 @@ void NavigationView::UpdateAdaptiveLayout(double width, bool forceSetDisplayMode
         MUX_FAIL_FAST();
     }
     if (!forceSetDisplayMode && m_InitialNonForcedModeUpdate) {
```
Comment (kmahone) [inline dev/NavigationView/NavigationView.cpp]: nit: add a blank line between this if statement and the else block above it so that the two blocks are visually separated.

File: dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs [hunk 2]
```diff
@@ -457,6 +457,14 @@ public void PaneClosedWhenAutoAndNarrow()
                     Log.Comment("Checking that a NavigationView with displaymode set to 'Auto' and a narrow width does not display pane");
                     Wait.ForIdle();
                     Verify.IsTrue(isPaneOpenCheckBox.ToggleState == ToggleState.Off);
+
+                    isPaneOpenCheckBox = new CheckBox(FindElement.ById("IsLeftMinimalPaneOpenCheckBox"));
```
Comment (kmahone) [inline dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs]: I don't understand what this test is doing. It seems to be validating the same thing over and over without changing anything.

Comment (kmahone) [inline dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs]: Don't re-use a variable for a new control. It is confusing. Name this variable something like 'isLeftMinimalPaneOpenCheckBox'

Comment (ojhad) [reply dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs]: Its validating separate controls. The naming made it confusing (as per your comment below). Updated naming to make this more clear.

File: dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs [hunk 3]
```diff
@@ -445,18 +445,27 @@ public void PaneOpenForceCloseTest()
...
                 using (var setup = new TestSetupHelper(new[] { "NavigationView Tests", "Navigation Minimal Test" }))
                 {
+                    Log.Comment("Verify that NavigationView with DisplayMode set to 'Auto' and a narrow width does not display pane on load.");
+                    CheckBox isAutoPaneOpenCheckBox = new CheckBox(FindElement.ById("IsAutoPaneOpenCheckBox"));
+                    Wait.ForIdle();
+                    Verify.IsTrue(isAutoPaneOpenCheckBox.ToggleState == ToggleState.Off);
+
+                    Log.Comment("Verify that NavigationView with DisplayMode set to 'LeftMinimal' does not display pane on load.");
+                    CheckBox isLeftMinimalPaneOpenCheckBox = new CheckBox(FindElement.ById("IsLeftMinimalPaneOpenCheckBox"));
+                    Wait.ForIdle();
```
Comment (kmahone) [inline dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs]: Since the state of the app is not changing, there is no need for the multiple WaitForIdle calls. Just one should suffice.
