### PR TITLE
NumberBox: Forward information to the inner TextBox for better UIA experience

### LINKED ISSUE #3505: Narrator fails to read the name for all the editable number boxes in "Number Box" page.
**Steps to reproduce the bug**

Pre-requisite: 
- Turn on Narrator.

1. Launch XAML Controls Gallery.
2. Activate "number box" from home page.
3. Navigate to all the editable number boxes in the page.
4. Observe narrator's description for the same.

**Expected behavior**

Narrator should read unique name, role for the all the respective number boxes.

**Screenshots**

image

image

**Version Info**

Xaml Controls Gallery version: 1.2.13.0

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/25441108/)

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

NumberBox now forwards header if its a string or the AutomationProperties.Name property if no header is present.
## Motivation and Context

Closes #3505
## How Has This Been Tested?

Add new API test

### CODE REVIEW

File: dev/NumberBox/NumberBox.cpp [hunk 1]
```diff
@@ -46,6 +46,8 @@ NumberBox::NumberBox()
 
     SetDefaultStyleKey(this);
     SetDefaultInputScope();
+
+    this->RegisterPropertyChangedCallback(winrt::AutomationProperties::NameProperty(), { this , &NumberBox::OnAutomationPropertiesNamePropertyChanged });
```
Comment (StephenLPeters) [inline dev/NumberBox/NumberBox.cpp:50]: It doesn't look like this is ever unregistered, which would lead to memory leaks.  Please use [RegisterPropertyChanged](https://github.com/microsoft/microsoft-ui-xaml/blob/513ed8267007c8e0b3055c6b924e2c2c58601503/dev/inc/CppWinRTHelpers.h#L216) to get a revoker object for this registration.

File: dev/NumberBox/NumberBox.h [hunk 2]
```diff
@@ -70,6 +70,7 @@ class NumberBox :
     void OnNumberBoxScroll(winrt::IInspectable const& sender, winrt::PointerRoutedEventArgs const& args);
     void OnCornerRadiusPropertyChanged(const winrt::DependencyObject&, const winrt::DependencyProperty&);
     void OnIsEnabledChanged(const winrt::IInspectable&, const winrt::DependencyPropertyChangedEventArgs&);
+    void OnAutomationPropertiesNamePropertyChanged(const winrt::DependencyObject& /* sender */, const winrt::DependencyProperty& prop);
```
Comment (StephenLPeters) [inline dev/NumberBox/NumberBox.h:73]: Both of these parameters are unused and their names can be deleted.

File: dev/NumberBox/APITests/NumberBoxTests.cs [hunk 3]
```diff
@@ -49,7 +52,7 @@ public void VerifyTextAlignmentPropogates()
         [TestMethod]
         public void VerifyNumberBoxCornerRadius()
         {
-            if (PlatformConfiguration.IsOSVersionLessThan(OSVersion.Redstone5))
+            if (Common.PlatformConfiguration.IsOSVersionLessThan(Common.OSVersion.Redstone5))
```
Comment (StephenLPeters) [inline dev/NumberBox/APITests/NumberBoxTests.cs:55]: Why is `Common` needed here?

**Review by StephenLPeters — CHANGES_REQUESTED** [review]

File: dev/NumberBox/NumberBox.cpp (hunk 1 above)
Comment (chingucoding) [reply dev/NumberBox/NumberBox.cpp:50]: I though since we are registered to the NumberBox itsself, this wouldn't be necessary as both should have the same lifecycle.

Comment (StephenLPeters) [reply dev/NumberBox/NumberBox.cpp:50]: Ah.. hmm. I think you're right. @jevansaks or @ranjeshj could you confirm please :)

File: dev/NumberBox/NumberBox.cpp [hunk 4]
```diff
@@ -361,6 +363,30 @@ void NumberBox::OnIsEnabledChanged(const winrt::IInspectable&, const winrt::Depe
     UpdateVisualStateForIsEnabledChange();
 }
 
+void NumberBox::OnAutomationPropertiesNamePropertyChanged(const winrt::DependencyObject& /* sender */, const winrt::DependencyProperty& prop)
```
[the remark this answers is not in the document]
Comment (chingucoding) [reply dev/NumberBox/NumberBox.cpp:366]: The idea is that whatever changed the most recently will have precedence to be able to control what will be forwarded. I'm not sure though if this is relevant or a useful behavior to have. Will happily change this if we decide that consistent behavior is better here.

File: dev/NumberBox/NumberBox.cpp (hunk 1 above)
Comment (jevansaks) [reply dev/NumberBox/NumberBox.cpp:50]: Yes that's technically correct.

Comment (chingucoding) [reply dev/NumberBox/NumberBox.cpp:50]: The best kind of correct?

Jokes aside, I'll add a comment to point that out so this won't cause confusion down the line.

File: dev/NumberBox/APITests/NumberBoxTests.cs (hunk 3 above)
Comment (chingucoding) [reply dev/NumberBox/APITests/NumberBoxTests.cs:55]: This is because the type PlatformConfiguration exists both in the Common namespace and the MUXControls.TestAppUtils namespace. Adding Common as prefix solves this collision.

File: dev/NumberBox/NumberBox.h (hunk 2 above)
Comment (chingucoding) [reply dev/NumberBox/NumberBox.h]: Removed them now.

File: dev/NumberBox/NumberBox.cpp [hunk 5]
```diff
@@ -361,6 +363,30 @@ void NumberBox::OnIsEnabledChanged(const winrt::IInspectable&, const winrt::Depe
...
+{
+    const auto name = winrt::AutomationProperties::GetName(*this);
+    if (!name.empty())
+    {
+        // Header is a string, we can use that as our UIA name.
```
[the remark this answers is not in the document]
Comment (chingucoding) [reply dev/NumberBox/NumberBox.cpp]: Updated all the comments, thanks for providing better comments! :)

File: dev/NumberBox/NumberBox.cpp [hunk 6]
```diff
@@ -361,6 +363,30 @@ void NumberBox::OnIsEnabledChanged(const winrt::IInspectable&, const winrt::Depe
...
+        if (const auto textBox = m_textBox.get())
```
[the remark this answers is not in the document]
Comment (chingucoding) [reply dev/NumberBox/NumberBox.cpp]: Good idea, updated that now.

File: dev/NumberBox/NumberBox.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (StephenLPeters) [reply dev/NumberBox/NumberBox.cpp]: I think a consistent behavior would be better.  Without delving to much into it I think AutomationName should take priority over header value. @YuliKl can you weigh in?

[the remark this answers is not in the document]
Comment (chingucoding) [reply dev/NumberBox/NumberBox.cpp]: Agree, consistent behavior is probably better. I think having the UIA name take precedence is best here as we are setting the UIA name after all. Not having the UIA name precedence here seems weird to me.

[the remark this answers is not in the document]
Comment (YuliKl) [reply dev/NumberBox/NumberBox.cpp]: Sorry for the slow response. Agree that when the UIA name is specified it ought to be used.

**Review by StephenLPeters — APPROVED** [review]
