### PR TITLE
Fix NavView VisualState for pane closing

### LINKED ISSUE #726: NavigationView not invalidating layout correctly after resizing
**Describe the bug**

Reported by @joshkoon 

**Steps to reproduce the bug**

See the below images. Left is the bad state, Right is expected. This one is a little trickier to repro and seems like we aren’t invalidating the layout someplace:

a.	With CompactModeThresholdWidth=0, Resize the window to just under the ExpandedMode threshold width. (pane is collapsed)

b.	Click the hamburger to open the pane (opens over content)

c.	Resize the window to OVER the ExpandedMode threshold width (pane collapses before threshold and immediately expands after threshold)

d.	Resize the window the under the ExpandedMode threshold width. Pane collapses but doesn’t seem to update its width for all elements. I can verify IsPaneOpen property changed events are firing correctly and elements are responding, but the phone icon and (custom) separator lines still believe they are rendering at full width.

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

### PR DESCRIPTION
**Pull request by kaiguo**
Fixes #726.

When m_initialListSizeStateSet is set to true, NavView skips list size VisualState updates in NavigationView::UpdateIsClosedCompact, which causes this PaneCustomContent layout updating bug when pane open/closes. Set m_initialListSizeStateSet to false before closing NavView pane to fix the issue.

### CODE REVIEW

File: dev/NavigationView/NavigationView.cpp [hunk 1]
```diff
@@ -596,6 +596,7 @@ void NavigationView::UpdateAdaptiveLayout(double width, bool forceSetDisplayMode
     if (previousMode == winrt::NavigationViewDisplayMode::Expanded
         && displayMode == winrt::NavigationViewDisplayMode::Compact)
     {
+        m_initialListSizeStateSet = false;
```
Comment (ranjeshj) [inline dev/NavigationView/NavigationView.cpp]: can you please add a test ?
