### PR TITLE
Fix bug with TreeView not updating nodes correctly when collection triggers reset event

### LINKED ISSUE #1379: Bug: TreeView - using IObservableVector.ReplaceAll to update ItemsSource does not work
**Describe the bug**
When binding an IObservableVector (like winrt::single_threaded_observable_vector) to the ItemsSource property of a TreeView, updating the vector with ReplaceAll causes the corresponding tree node to drop all children instead of creating/updating its children according to the new items in the vector.

The change notification triggered by ReplaceAll ends up here:
https://github.com/microsoft/microsoft-ui-xaml/blob/803f4797a19ae03a428c8781bef85190e8855f1e/dev/TreeView/TreeViewNode.cpp#L195-L202
which just removes the nodes' children.

**Steps to reproduce the bug**
1. Bind an IObservableVector to the ItemsSource property of a TreeView
2. Update the vector using the ReplaceAll method

**Expected behavior**
The tree node should update its children according to the new contents of the vector.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.2.190917002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes  |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Fixed a bug where the reset event of collection implementin OnCollectionChanged and still having items after reset would result in the TreeView not having any nodes.
## Motivation and Context

Fixes #1379 
## How Has This Been Tested?

Added new API unit test. Also tested using the great test page created by @kaiguo

### CODE REVIEW

File: test/MUXControlsTestApp/Utilities/ExtendedObservableCollection.cs [hunk 1]
```diff
@@ -0,0 +1,25 @@
+﻿// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT License. See LICENSE in the project root for license information.
+
+using System.Collections.Generic;
+using System.Collections.ObjectModel;
+using System.Collections.Specialized;
+
+namespace MUXControlsTestApp.Utilities
+{
+    class ExtendedObservableCollection<T> : ObservableCollection<T>
```
Comment (kaiguo) [inline test/MUXControlsTestApp/Utilities/ExtendedObservableCollection.cs]: Can you add some comments about why this class is created?

Comment (chingucoding) [reply test/MUXControlsTestApp/Utilities/ExtendedObservableCollection.cs]: Sure!
