### PR TITLE
TabView: Fix newly-added items not respecting TabWidthMode [compact] when using an ItemsSource collection

### LINKED ISSUE #3104: TabView throw ArgumentOutOfRange exception when TabItemSource is cleared
**Describe the bug**
If you clear an ObservableCollection attached to TabItemsSource, app will crash with ArgumentOutOfRangeException

**Steps to reproduce the bug**

1. Open XamlControlsGallery project
2. Modify `private void TabViewItemsSourceSample_AddTabButtonClick(TabView sender, object args)` in TabViewPage.xaml.cs as follow:
`myDatas.Clear();`
 `// Add a new MyData item to the collection. TabView automatically generates a TabViewItem.`
 `myDatas.Add(CreateNewMyData(myDatas.Count));`

3. Launch the project and add a tab in the TabView page (third exemple)

**Expected behavior**
Old tabs are removed and the new tab appear

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml.2.5.0-prerelease.200708003]

It was working on [Microsoft.UI.Xaml.2.4.2]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

### LINKED ISSUE #3114: TabView: TabWidthMode set to Compact is ignored from XAML markup and for newly-added items when using data binding
**Describe the bug**
The exact same issues reported in #2711 and #2724 also apply to the TabView when its tab items are supplied va data-binding:

#### XAML Markup issue
```xml
<controls:TabView x:Name="DataBindingTabView" SelectedIndex="2"
                  TabItemsSource="{x:Bind ItemsSource, Mode=OneWay}"
                  TabWidthMode="Compact"
                  AddTabButtonClick="TabViewAddButtonClick">
    <controls:TabView.TabItemTemplate>
        <!-- left out here --> 
    </controls:TabView.TabItemTemplate>
</controls:TabView>
```
image

#### Adding an item to the bound data source:
tabview-databinding-compact-issue

**Expected behavior**
All TabViewItems should be in compact mode when the TabView is loaded or when a new item is added to the TabView.ItemsSource.

**Version Info**

NuGet package version: 
WinUI 2.4 and WinUI 2.5 previews.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
I would like to fix this. The fix for this issue, if accepted, would also fix the bug reported in https://github.com/microsoft/microsoft-ui-xaml/issues/3104.

### PR DESCRIPTION
**Pull request by Felix-Dev**
## Description
This PR fixes the following issues when the TabView is populated via its ItemsSource API and with its TabWidthMode set to [Compact] initially:
* A TabWidthMode of [Compact] is ignored on tab creation and for newly-added items (issue #3114)
* When clearing the ItemsSource collection via the [IList.Clear()](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ilist.clear?view=netcore-3.1) method, the app crashes (issue #3104)

#### Notes

The work done in PR https://github.com/microsoft/microsoft-ui-xaml/pull/2752/ fixed related issues when populating the TabView directly with items of type `TabViewItem` when in [Compact] TabWidthMode: 
https://github.com/microsoft/microsoft-ui-xaml/blob/4468528f4e2089defa921df2cf140ab6c44cbbab/dev/TabView/TabView.cpp#L638

In the code above, we are updating the TabWidthMode of the added item as soon as it was added to the TabView item collection using the [ItemsControl.OnItemsChanged()](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.itemscontrol.onitemschanged?view=winrt-19041#Windows_UI_Xaml_Controls_ItemsControl_OnItemsChanged_System_Object_) overridable method. The condition for success here is that 
* the newly added item is either already a `TabViewItem` or 
* that a TabViewItem already exists as a container for the added item

Unfortunately, when items of a type other than `TabViewItem` are added to the TabView (for example via the TabView.ItemsSource API) no TabViewItem container has yet been prepared for the newly added item at the time this code is run. That TabViewItem container is only created after `TabView.OnItemsChanged` ran so the container will miss out on the TabWidthMode update done there.

The solution chosen in this PR is to move the relevant code shown above out of the TabView.OnItemsChanged method and into the TabView's internal list's [PrepareContainerForItemOverride()](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.itemscontrol.preparecontainerforitemoverride?view=winrt-19041#Windows_UI_Xaml_Controls_ItemsControl_PrepareContainerForItemOverride_Windows_UI_Xaml_DependencyObject_System_Object_) method. And as `PrepareContainerForItemOverride` is called for *every* item added to the TabView, no matter what type it is, we are now updating the TabWidthMode of a TabViewItem *no matter* if it acts as a container or has been directly added to the TabView.

Note: Adding this code to the existing `ContainerContentChanging()` implementation in the TabViewListView class is not an option as the `OnContainerContentChanging` event is not raised when a `TabViewItem` is added directly to the TabView (whereas `PrepareContainerForItemOverride` is).

With this approach we can now remove the TabViewItem TabWidthMode update logic in `TabView.OnItemsChanged`. This fixes issue #3104 which was a regression introduced in PR https://github.com/microsoft/microsoft-ui-xaml/pull/2752/. The bug here is an app crash caused by the added logic in TabView.OnItemsChanged. Here is the added code again:
https://github.com/microsoft/microsoft-ui-xaml/blob/4468528f4e2089defa921df2cf140ab6c44cbbab/dev/TabView/TabView.cpp#L638
The line
```cs
if (const auto newItem = TabItems().GetAt(args.Index()).try_as<TabViewItem>())
```
contains the reason for the crash when it tries to get an item from the item collection with
```cs
TabItems().GetAt(args.Index())
```

Clearing the item collection of a TabView via the [IList.Clear()](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ilist.clear?view=netcore-3.1) method sends a [CollectionChange.Reset](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.collections.collectionchange?view=winrt-19041) notification to grab inside the `TabView.OnItemsChanged` method. Unfortunately, the code highlighted above wil be run when a Reset notification is sent, so we end up with the following call:
```cs
TabItems().GetAt(0)
```
However, the collection returned by TabItems() already no longer contains *any* elements as we just cleared it via TabView.TabItems.Clear(), so we end up accessing an item here which no longer exists - the app crashes.

## Motivation and Context
Fixes #3104, fixes #3114 and fixes https://github.com/microsoft/microsoft-ui-xaml/issues/3351.

## How Has This Been Tested?
Tested visually and added API tests.

## Gif:
The following GIF shows a TabView populated via its ItemsSource API and with its TabWidthMode set to [Compact] in XAML markup:

tabview-databinding-compact-add-item

### CODE REVIEW

File: dev/TabView/TabViewListView.cpp [hunk 1]
```diff
@@ -40,18 +40,40 @@ void TabViewListView::OnItemsChanged(winrt::IInspectable const& item)
...
+{
+    const auto itemContainer = element.as<winrt::TabViewItem>();
+    const auto tvi = winrt::get_self<TabViewItem>(itemContainer);
+
+    // Due to virtualization, a TabViewItem might be recycled to display a different tab data item.
+    // In that case, there is no need to set the TabWidthMode of the TabViewItem or its parent TabView
+    // as they are already set correctly here.
+    //
+    // We know we are currently looking at a TabViewItem being recycled if its parent TabView has already been set.
+    if (!tvi->GetParentTabView())
```
Comment (StephenLPeters) [inline dev/TabView/TabViewListView.cpp:60]: >GetParentTabView [](start = 14, length = 16)

Do we need to call GetAncestorOfType if we have this to get access to the TabView?

Comment (Felix-Dev) [reply dev/TabView/TabViewListView.cpp:60]: @StephenLPeters Observe that the check is `if (tvi->GetParentTabView() == nullptr)`. We need the GetAncestorOfType() call here because we only are interested in the parent TabView when the TabViewItem has been *newly* created (and not recycled). When we are looking at a fresh TabViewItem object, it doesn't yet have its parent TabView set so we need to walk the visual tree upwards here.

**Comment by StephenLPeters** [comment]
@Felix-Dev can you merge master to pick up the CI build fix that just went in?

**Comment by Felix-Dev** [comment]
Merged with master.

**Comment by StephenLPeters** [comment]
Looks like a down level only test failure, I can take a look in a little while

**Comment by chingucoding** [comment]
@Felix-Dev GitHub doesn't support saying "Fixes x and y", it will think it should only close x. Please update your PR to include "Fixes #3104 and fixes #3114" even though it doesn't sound as good.

**Comment by Felix-Dev** [comment]
@chingucoding Done. Thanks for the info.

**Comment by StephenLPeters** [comment]
@Felix-Dev The pipeline fix just went in, could you please merge master into this PR?

**Comment by Felix-Dev** [comment]
@StephenLPeters Merged with master.

**Comment by Felix-Dev** [comment]
@StephenLPeters The test failure seems to be a downlevel issue - I see it failing on RS2 - RS4. I'm not sure exactly why (I am only setting and clearing the TabView ItemsSource). There is issue https://github.com/microsoft/microsoft-ui-xaml/issues/2427 which occurs when using the TabView ItemsSource API to populate the TabView and fails on RS4 and below (works on RS5 apparently). Might there be an underlying relation here? Other than this, perhaps rather desperate guess, I haven't found any additional info for now which could explain the down level failure.

**Comment by DHowett** [comment]
Gentle prod on this. @StephenLPeters how can we determine the nature of the downlevel failure?

**Comment by StephenLPeters** [comment]
The team is very busy with winui 3 work but this is on my radar, I hope to get to it soon.

**Comment by zhuxb711** [comment]
I found that in the recently released preview version, if you only create TabView without adding any tabs to TabItems, it will cause a crash
#3351

**Comment by Felix-Dev** [comment]
@zhuxb711 This PR should fix your reported issue.

**Comment by Felix-Dev** [comment]
Added a new API test to cover the crash scenario reported in issue #3351.

**Comment by zhuxb711** [comment]
Why did this PR take so much time but still not approved?

**Review by StephenLPeters — APPROVED** [review]
:shipit:

**Comment by ranjeshj** [comment]
>             UpdateSelectedIndex();

If there are no items to start with, then this call will try to set ListView's selected index to TabView.Selection index which is 0 (but there are no items).

---
Refers to: dev/TabView/TabView.cpp:427 in 3a061f6. [](commit_id = 3a061f6af00efcbcedc6e79ee2f54d2d0e98f467, deletion_comment = False)

**Comment by ranjeshj** [comment]
Also, I see a crash with rounded corners in older versions (one one I saw was for the add button), perhaps that needs a contract check in the markup. I'm not sure why that is not being hit in other tests.

**Comment by ranjeshj** [comment]
> Also, I see a crash with CornerRadius in older versions (one one I saw was for the add button), perhaps that needs a contract check in the markup. I'm not sure why that is not being hit in other tests.

@Felix-Dev Can you add the contract check for CornerRadius ? Once you make that I can run the pipeline again. Thanks!

**Comment by Felix-Dev** [comment]
@ranjeshj Added the two specific commits in your PR https://github.com/microsoft/microsoft-ui-xaml/pull/3604 here. (Didn't cherry-pick them yet because I didn't want to experiment with VS's git experience regarding cherry-picking this late today and felt copying over your changes was faster for me today.)

**Comment by Felix-Dev** [comment]
Looks like we only have one failure left - on RS3. I might be able to install a VM running RS3 on the weekend (with VS,...) and see if I can get some more info (if the team is unable to take a look at this failure).

**Comment by ranjeshj** [comment]
> Looks like we only have one failure left - on RS3. I might be able to install a VM running RS3 on the weekend (with VS,...) and see if I can get some more info (if the team is unable to take a look at this failure).

I think we are still setting an incorrect index on the listview.selected index. I've made a minor change - lets see if that resolves the issue.

**Comment by Felix-Dev** [comment]
@ranjeshj Looks like your newest fix did it then in combination with the others 👍

**Comment by duke7553** [comment]
@ranjeshj It appears building a sample project for #3597 on WinUI v2.5 is blocked until a preview is released to fix #3351 . I'll upload the working one for WinUI v2.4 which demonstrates the issue.
