### PR TITLE
Fix issue with displaymode minimal shadow missing

### LINKED ISSUE #3117: NavigationView missing shadow when opening the panel in LeftMinimal mode
**Describe the bug**

**Steps to reproduce the bug**

1. Open XAML Control gallary
2. Reduce the width of the application to make NavigationView go into `LeftMinimal` mode
3. Click on the hamburger menu to open the NavigationView panel
4. The panel shows the shadow, but it disappears after the panel is fully open

**Expected behavior**

Shadow to remain when the panel is fully open

**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.4.0]
[Microsoft.UI.Xaml.2.4.0-prerelease.200506001]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |  Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

The code to size the shadowreceiver didn't account for the fact that the popup in case of minimal is sized differently (the negative margin seemed to be an issue).

## Motivation and Context

Closes #3117 
## How Has This Been Tested?

Tested manually:
image

### CODE REVIEW

File: dev/NavigationView/NavigationView.cpp [hunk 1]
```diff
@@ -4521,7 +4521,14 @@ void NavigationView::UpdatePaneShadow()
...
 
         // Ensure shadow is as wide as the pane when it is open
-        shadowReceiver.Width(OpenPaneLength());
+        if (DisplayMode() == winrt::NavigationViewDisplayMode::Compact)
+        {
+            shadowReceiver.Width(OpenPaneLength());
+        }
+        else
+        {
+            shadowReceiver.Width(OpenPaneLength() - shadowReceiverMargin.Right);
```
Comment (StephenLPeters) [inline dev/NavigationView/NavigationView.cpp:4530]: >- shadowReceiverMargin.Right [](start = 50, length = 28)

Why isn't this needed in the Compact case?

Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp:4530]: For some reason in the case of Compact, the sizing seems to be calculated correctly. In the case of Minimal it is not ...

Comment (StephenLPeters) [reply dev/NavigationView/NavigationView.cpp:4530]: hmm any theories why?

Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp:4530]: My guess is that the negative margin is the issue for minimal. This blue area is the shadow receiver (reports itsself as having an actualwidth of 320 which is the same as the pane. The yellow area is the margin (0,**-32**,**-32**,**-32**):

image

This is how it looks without that margin:

image

In both cases it reports the same actual size. So I think the negative margin is just not reacting correctly here.

Comment (StephenLPeters) [reply dev/NavigationView/NavigationView.cpp:4530]: What is the margin from the compact case?

Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp:4530]: Exactly the same.

**Comment by chingucoding** [comment]
Test failures were due to updated visual tree, updated the VTV files now.

**Comment by StephenLPeters** [comment]
@chingucoding can you merge master to pick up the CI build fix that just went in?

**Comment by StephenLPeters** [comment]
Why did this only result in updates to the -8 versions  of the VFF? is this code path not exercised downlevel?

File: dev/NavigationView/NavigationView.cpp (hunk 1 above)
Comment (StephenLPeters) [reply dev/NavigationView/NavigationView.cpp:4544]: I still wish I understood this better. I'm hoping there is some comment we can include in the code explaining why the distinction is needed.

**Comment by chingucoding** [comment]
> Why did this only result in updates to the -8 versions of the VFF? is this code path not exercised downlevel?

No idea, I wish I had an answer to that.

File: dev/NavigationView/NavigationView.cpp (hunk 1 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp:4544]: The only thing I can say with confidence is that in theory, the sizing is actually correct:
The shadow pane receiver has 320px width (actual width!), the same is true for the pane. In theory, having a negative right margin for the shadow receiver would allow the shadow to be visible as the shadow receiver gets extended to the right, but that is not the case for some reason.

**Comment by StephenLPeters** [comment]
>                 const auto translation = winrt::float3{ currentTranslation.x, currentTranslation.y, IsPaneOpen() && isOverlay ? c_paneElevationTranslationZ : 0.0f };

Could this be the cause of the difference? looks like we are conditionally applying a translation to the paneRoot, which is the source of the shadow.

---
Refers to: dev/NavigationView/NavigationView.cpp:3849 in f1d9a5f. [](commit_id = f1d9a5f5a224b1618d975897f31ba1a3164983ad, deletion_comment = False)

**Comment by chingucoding** [comment]
> Could this be the cause of the difference? looks like we are conditionally applying a translation to the paneRoot, which is the source of the shadow.

Unfortunately, this isn't the issue here either. If it returns 0, we have no shadow at all, and if we return c_paneElevationTranslationZ, the shadow is still misplaced.

**Review by StephenLPeters — APPROVED** [review]
