### PR TITLE
Fix issue with NavigationView ShoulderNavigation always not behaving correctly

### LINKED ISSUE #328: NavigationView.ShoulderNavigationEnabled Property with value Always work as WhenSelectionFollowsFocus
**Describe the bug**
When I set value `Always` in the `NavigationView.ShoulderNavigationEnabled` property, it still work as `WhenSelectionFollowsFocus`. This bug related with function [NavigationView::BumperNavigation](https://github.com/Microsoft/microsoft-ui-xaml/blob/master/dev/NavigationView/NavigationView.cpp#L1541). Which have incorrect check in [line](https://github.com/Microsoft/microsoft-ui-xaml/blob/master/dev/NavigationView/NavigationView.cpp#L1552):
```
|| !IsNavigationViewListSingleSelectionFollowsFocus()
```

**Steps to reproduce the bug**
1. Create navigation view with follow params:
```
    <NavigationView x:Name="testNavigation"
                    PaneDisplayMode="Top"
                    ShoulderNavigationEnabled="Always"></NavigationView>
```
2. Run application on xBox and trying to press gamepad bumpers buttons.

**Expected behavior**
Navigation work correct.

**Version Info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes   |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |  Yes   |
| Surface Hub          |     |
| IoT                         |     |

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

The check to determine whether selection should update or not was faulty. Thanks you @pavelshapovalov for pointing that out in your issue!

## Motivation and Context

Closes #328
## How Has This Been Tested?

Add two new interaction tests.

Since those tests rely on gamepad input, maybe we should disable them right away until we have a more reliable gamepad input logic? (See #2202 for more context).

### CODE REVIEW

File: dev/NavigationView/NavigationView.cpp [hunk 1]
```diff
@@ -2671,9 +2671,11 @@ bool NavigationView::BumperNavigation(int offset)
     // that meets the conditions, in the same direction.
     const auto shoulderNavigationEnabledParamValue = ShoulderNavigationEnabled();
     const auto shoulderNavigationForcedDisabled = (shoulderNavigationEnabledParamValue == winrt::NavigationViewShoulderNavigationEnabled::Never);
+    const auto shoulderNavigationOptionalDisabled = (shoulderNavigationEnabledParamValue == winrt::NavigationViewShoulderNavigationEnabled::WhenSelectionFollowsFocus
+        && SelectionFollowsFocus() == winrt::NavigationViewSelectionFollowsFocus::Disabled);
 
     if (!IsTopNavigationView()
-        || !IsNavigationViewListSingleSelectionFollowsFocus()
```
Comment (chingucoding) [inline dev/NavigationView/NavigationView.cpp:2676]: Should we remove this function altogether? This is more or less a relic now since we are not using ListView anymore and the function doesn't do anything we couldn't do elsewhere (and we already do in a few cases).

Comment (StephenLPeters) [reply dev/NavigationView/NavigationView.cpp:2676]: It does seem pretty trivial, I think it would probably be easier to parse the code if we removed it

---
In reply to: [471540013](https://github.com/microsoft/microsoft-ui-xaml/pull/3145#discussion_r471540013) [](ancestors = 471540013)

**Comment by StephenLPeters** [comment]
@chingucoding can you merge master to pick up the CI build fix that just went in?
