### PR TITLE
ProgressBar Accessibility Features & Bug Fixes

### LINKED ISSUE #1621: New ProgressBar doesn't always show the right width
**Describe the bug**

Under certain circumstances, the new ProgressBar disappears, presumably because its width goes to 0.

**Steps to reproduce the bug**

```Xaml
        <Grid Margin="24">
            <Grid.ColumnDefinitions>
                <ColumnDefinition/>
                <ColumnDefinition/>
            </Grid.ColumnDefinitions>
            <StackPanel Orientation="Horizontal">
                <TextBlock>WUX ProgressBar</TextBlock>
                <ProgressBar IsIndeterminate="True"/>
            </StackPanel>
            <StackPanel Grid.Column="1" Orientation="Horizontal">
                <TextBlock>MUX ProgressBar</TextBlock>
                <muxc:ProgressBar IsIndeterminate="True"/>
            </StackPanel>
        </Grid>
```

**Expected behavior**

Both ProgressBar controls are visible on screen.

**Screenshots**

ProgressBarWidth

**Version Info**

NuGet package version: 

2.3.191107001-prerelease

**Additional context**

The problem does not repro in other layout permutations, e.g. when the StackPanels have vertical orientation or when the ProgressBars are placed in the Grid directly.

### LINKED ISSUE #1628: Bugs in ProgressBar style
**Describe the bug**

There are several bugs in the ProgressBar style. This needs to be reviewed in detail by MSFT.

Foreground is set twice in the XAML style of progress bar:

```XML
    <Style TargetType="local:ProgressBar">
        <Setter Property="Foreground" Value="{ThemeResource SystemControlHighlightAccentBrush}" />
        <Setter Property="Background" Value="{ThemeResource SystemControlBackgroundBaseLowBrush}" />
        <Setter Property="BorderThickness" Value="{ThemeResource ProgressBarBorderThemeThickness}" />
        <Setter Property="BorderBrush" Value="{ThemeResource SystemControlHighlightTransparentBrush}" />
        <Setter Property="Foreground" Value="{ThemeResource SystemControlForegroundAccentBrush}" />
```

A brush is being set as thickness

```XML
<Border x:Name="ProgressBarRoot"
              Background="{TemplateBinding Background}"
              BorderBrush="{TemplateBinding BorderBrush}"
              BorderThickness="{TemplateBinding BorderBrush}"
```

Setting a clipping here also seems to be unnecessary but I might be missing something.
```XML
<Border Clip="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=TemplateSettings.ClipRect}">
```

Please, please take care in code reviews!

**Lines of code are here**

https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/ProgressBar/ProgressBar.xaml

https://github.com/microsoft/microsoft-ui-xaml/blob/1a62591f95c4cec7af5360ca271e52dc4eb5443f/dev/ProgressBar/ProgressBar.xaml#L10

https://github.com/microsoft/microsoft-ui-xaml/blob/1a62591f95c4cec7af5360ca271e52dc4eb5443f/dev/ProgressBar/ProgressBar.xaml#L14

https://github.com/microsoft/microsoft-ui-xaml/blob/1a62591f95c4cec7af5360ca271e52dc4eb5443f/dev/ProgressBar/ProgressBar.xaml#L100

### PR DESCRIPTION
**Pull request by karenbtlai**
## Description
ProgressBar Accessibility Features:
* High Contrast Mode
* Narrator

## Motivation and Context

Fixes #1628 and Fixes #1621 

## How Has This Been Tested?

Existing tests

### CODE REVIEW

File: dev/Generated/NumberBox.properties.cpp [hunk 1]
```diff
@@ -372,11 +372,6 @@ winrt::IInspectable NumberBoxProperties::Description()
     return ValueHelper<winrt::IInspectable>::CastOrUnbox(static_cast<NumberBox*>(this)->GetValue(s_DescriptionProperty));
 }
 
-void NumberBoxProperties::Header(winrt::IInspectable const& value)
```
Comment (jevansaks) [inline dev/Generated/NumberBox.properties.cpp]: I'm guessing the NumberBox changes in this PR are from a bad merge?

File: dev/ProgressBar/ProgressBarAutomationPeer.cpp [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+
+// IRangeValueProvider
+double ProgressBarAutomationPeer::Value()
+{
+    return GetImpl()->Value();
+}
+
+double ProgressBarAutomationPeer::SmallChange()
+{
+    return NAN;
```
Comment (jevansaks) [inline dev/ProgressBar/ProgressBarAutomationPeer.cpp]: prefer std library numeric helpers instead of #defines.

```suggestion
    return std::numeric_limits<double>::quiet_NaN();
```

File: dev/ProgressBar/ProgressBarAutomationPeer.cpp [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+}
+
+double ProgressBarAutomationPeer::LargeChange()
+{
+    return NAN;
```
Comment (jevansaks) [inline dev/ProgressBar/ProgressBarAutomationPeer.cpp]:
```suggestion
    return std::numeric_limits<double>::quiet_NaN();
```

File: dev/ProgressBar/ProgressBar.h [hunk 4]
```diff
@@ -19,6 +19,8 @@ class ProgressBar :
 public:
     ProgressBar();
 
+    virtual winrt::AutomationPeer OnCreateAutomationPeer();
+
```
Comment (jevansaks) [inline dev/ProgressBar/ProgressBar.h]:
```suggestion
    winrt::AutomationPeer OnCreateAutomationPeer();
```
