### PR TITLE
Fix Teaching Tip's Rounded Corners

### LINKED ISSUE #1254: With rounded corners, top right of TeachingTip has a gap
**Describe the bug**
Look at the top right corner of TeachingTip with rounded corners:

image

**Steps to reproduce the bug**

1. Install latest Nuget package to Xaml Controls Gallery
2. Run Xaml Controls Gallery and go to TeachingTip page
3. Click on the first button.

**Expected behavior**
All the corners should look rounded and even.

**Version Info**

NuGet package version: 
2.2.1908300001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

### PR DESCRIPTION
**Pull request by StephenLPeters**
Teaching tip has some complicated element layering which doesn't play nicely with the rounded corners change.  This updates the adorners to look correct with the rounded corners change.
Fixes #1254

### CODE REVIEW

File: dev/Common/ThicknessFilterConverter.cpp [hunk 1]
```diff
@@ -0,0 +1,61 @@
+﻿// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT License. See LICENSE in the project root for license information.
+
+#include <pch.h>
+#include <common.h>
+#include "ThicknessFilterConverter.h"
+
+winrt::Thickness ThicknessFilterConverter::Convert(winrt::CornerRadius const& radius, winrt::ThicknessFilterConverterKind const& filterKind)
```
Comment (kaiguo) [inline dev/Common/ThicknessFilterConverter.cpp]: *May be* we can just add a property (like "ThicknessMode") to CornerRadiusFilterConverter and make it return Thickness instead of creating a new converter?
