### PR TITLE
NavView Minimal Pane Sometimes Transparent OnLoad / OnWindowResize

### LINKED ISSUE #5342: Navigation view pane background can appear transparent after resizing window while pane is in overlay state
**Describe the bug**

When the muxc navigation view is open in minimal or compact mode, changing the size of the window then back again will cause  the background to appear transparent.

**Steps to reproduce the bug**

1. Open latest version of Xaml Controls Gallery
2. Shrink window until the nav view goes into minimal state
3. Open the pane
4. maximize, then restore the window to it's previous size
5. Navigation view pane background is transparent, and the content displays wrong as well

**Expected behavior**

The background should remain opaque. 

**Screenshots**

https://user-images.githubusercontent.com/59544401/124203343-5b314200-da91-11eb-8ddb-ef09ad5699d6.mp4

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.51)              | yes    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

### PR DESCRIPTION
**Pull request by karenbtlai**
## Description

NavigationView sometimes appear as transparent when in `NavigationViewDisplayMode::Minimal` OnLoad and OnWindowResize. Turns out this is due to SplitView and NavigationView becoming out of sync, causing SplitView VisualState to evaluate to `OpenOverlayLeft` while NavigationView pane is closed while minimal. 

## Motivation and Context

Fixes #5342

### CODE REVIEW

File: dev/NavigationView/NavigationView.cpp [hunk 1]
```diff
@@ -1656,6 +1661,7 @@ void NavigationView::OpenPane()
             m_isOpenPaneForInteraction = false;
         });
     m_isOpenPaneForInteraction = true;
+
```
Comment (beervoley) [inline dev/NavigationView/NavigationView.cpp:1664]: nit: new line

**Review by beervoley — APPROVED** [review]
