### PR TITLE
NumberBox SpinButton Inline Overlap Fix

### LINKED ISSUE #5278: Numberbox w/inline SpinButtons sometimes overlap the clear button
**Describe the bug**
I just saw on the **XAML Controls Gallery**'s `GridView` section that the `NumberBox` have the inline `SpinButton` overlapped with the X to clear the input button:

image

However this behaviour is not happening `NumberBox` section itself, so it's not a glitch that happens in every scenario.

**Steps to reproduce the bug**

1. Open the XAML Controls Gallery in the  `GridView` section *URL: `xamlcontrolsgallery://item/GridView`*
2. Go to the second example with the three number boxes

**Expected behavior**

The X button to clear the input should not overlap with the `SpinButton`s

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.6.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)        | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

### LINKED ISSUE #5293: `NumberBox` width with inline buttons overlaps text in Version2 styles
**Describe the bug**

After updating to WinUI 2.6, in all `NumberBox` element without explicit width which have `SpinButtonPlacementMode="Inline"` the buttons now overlap the numeric input. See below for screenshot

**Steps to reproduce the bug**

Create a `NumberBox` with `Inline` spin buttons and no explicit width

**Expected behavior**

Buttons should not overlap

**Screenshots**

image

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.6.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

### PR DESCRIPTION
**Pull request by karenbtlai**
## Description

- Add min width to InputBox when `SpinButtonPlacementMode="Inline"`
- Move `UpdateSpinButtonPlacement` to OnLoaded so TextBox visual states can be updated properly

## Motivation and Context

Fixes #5293 
Fixes #5278

### CODE REVIEW

File: dev/NumberBox/NumberBox.cpp [hunk 1]
```diff
@@ -392,6 +399,10 @@ void NumberBox::OnNumberBoxGotFocus(winrt::IInspectable const& sender, winrt::Ro
             popup.IsOpen(true);
         }
     }
+    else if (SpinButtonPlacementMode() == winrt::NumberBoxSpinButtonPlacementMode::Inline)
+    {
+        //UpdateSpinButtonPlacement();
+    }
```
Comment (chingucoding) [inline dev/NumberBox/NumberBox.cpp:405]: I think we can remove this empty case can we?

File: dev/NumberBox/NumberBox.xaml [hunk 2]
```diff
@@ -39,6 +39,7 @@
                                         <Setter Target="DownSpinButton.Visibility" Value="Visible" />
                                         <Setter Target="UpSpinButton.Visibility" Value="Visible" />
                                         <Setter Target="InputEater.Visibility" Value="Visible" />
+                                        <Setter Target="InputBox.MinWidth" Value="{ThemeResource NumberBoxMinWidth}" />
```
Comment (chingucoding) [inline dev/NumberBox/NumberBox.xaml:42]: I think if you create a NumberBox with sufficient height, wouldn't the delete button just get wider and in some edge cases still exhibit the issue with spin buttons being on top of the delete button?

**Review by chingucoding — CHANGES_REQUESTED** [review]

File: dev/NumberBox/NumberBox.cpp (hunk 1 above)
Comment (karenbtlai) [reply dev/NumberBox/NumberBox.cpp]: oops, missed that!

File: dev/NumberBox/NumberBox.xaml (hunk 2 above)
Comment (karenbtlai) [reply dev/NumberBox/NumberBox.xaml:42]: The overlapping issue is fixed by moving UpdateSpinButtonPlacement() to OnLoaded, since previously InputBox wasn't getting the UpdateVisualState calls properly. This change will give deleteButton a right margin of 72 and fix the overlap.

The MinWidth is just to give the numberBox to a clickable input area when in Inline mode.

Comment (chingucoding) [reply dev/NumberBox/NumberBox.xaml:42]: Ah I see, got it.

**Review by chingucoding — APPROVED** [review]

**Review by teaP — APPROVED** [review]
Thank you!

**Comment by StephenLPeters** [comment]
>         winrt::VisualStateManager::GoToState(textbox, state, false);

What is going on here? Why are we telling the textbox to go to a SpinButtons[x] state? does it have that state?

---
Refers to: dev/NumberBox/NumberBox.cpp:648 in 847b3b3. [](commit_id = 847b3b305ebc93bf2b870d625d557a8ecd09eaa2, deletion_comment = False)

File: dev/NumberBox/NumberBox_themeresources.xaml [hunk 3]
```diff
@@ -58,6 +58,7 @@
     <x:Double x:Key="NumberBoxPopupHorizonalOffset">-21</x:Double>
     <x:Double x:Key="NumberBoxPopupVerticalOffset">-27</x:Double>
     <x:Double x:Key="NumberBoxPopupShadowDepth">16</x:Double>
+    <x:Double x:Key="NumberBoxMinWidth">120</x:Double>
```
Comment (StephenLPeters) [inline dev/NumberBox/NumberBox_themeresources.xaml:61]: How did you choose this number? TextControlThemeMinWidth is 64

Comment (karenbtlai) [reply dev/NumberBox/NumberBox_themeresources.xaml:61]: I took the width of SpinButtons and Delete Buttons (40px) and multiplied it by 3. Perhaps we should get some design eyes on this.

File: dev/NumberBox/NumberBox.cpp [hunk 4]
```diff
@@ -228,6 +229,12 @@ void NumberBox::OnApplyTemplate()
     }
 }
 
+void NumberBox::OnLoaded(winrt::IInspectable const&, winrt::RoutedEventArgs const&)
+{
+    // This is done OnLoaded so TextBox VisualStates can be updated properly.
+    UpdateSpinButtonPlacement();
```
Comment (StephenLPeters) [inline dev/NumberBox/NumberBox.cpp:235]: >UpdateSpinButtonPlacement [](http://example.com/codeflow?start=4&length=25)

I'm trying to reason about why this fixes the issue... I think it is probably indicative of us needing to be attached to some layout property on a template child..

**Comment by ArchieCoder** [comment]
I have the latest nuget 2.8.1. I still have the issue.

image

**Comment by ArchieCoder** [comment]
@karkarl Hello, I'm with 2.8.4 and I still have the issue. Can we reopen this bug?

image

**Comment by karkarl** [comment]
> @karkarl Hello, I'm with 2.8.4 and I still have the issue. Can we reopen this bug?
> 
> image

I'm not able to repro with the sample from WinUI Gallery. Can you provide me a repro app so I can investigate?

image

**Comment by ArchieCoder** [comment]
@karkarl I was able to repro in a small solution. The bug happens when the initial visibility of the NumberBox is Collasped! (Thanks for the fast answer).

[
[App2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/11434842/App2.zip)
](url)

**Comment by eugenegff** [comment]
For initially collapsed controls OnLoaded happens earlier than OnApplyTemplate, see https://github.com/microsoft/microsoft-ui-xaml/issues/6052

**Comment by ArchieCoder** [comment]
@eugenegff I'm a bit confused. https://github.com/microsoft/microsoft-ui-xaml/issues/6052 is closed and inside it is marked as fixed in https://github.com/microsoft/microsoft-ui-xaml/pull/6053.

Should we reopen these?

**Comment by eugenegff** [comment]
> @eugenegff I'm a bit confused. #6052 is closed and inside it is marked as fixed in #6053.
> 
> Should we reopen these?

Your bug looks different, buttons are overlapped rather than spin buttons became never visible. I mentioned #6052 as the reason of the #6052 was suspiciously similar - some work was done in OnLoaded, that was called for initially collapsed controls way before template with all parts is applied. Look at phrase in first post of the current thread:
> Move UpdateSpinButtonPlacement to **OnLoaded** so TextBox visual states can be updated properly

**Comment by ArchieCoder** [comment]
@karkarl I can repro with WinUI as well: [App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/11442126/App1.zip)

Let me know if I should create a new bug report.

**Comment by karkarl** [comment]
> 



> > @eugenegff I'm a bit confused. #6052 is closed and inside it is marked as fixed in #6053.
> > Should we reopen these?
> 
> Your bug looks different, buttons are overlapped rather than spin buttons became never visible. I mentioned #6052 as the reason of the #6052 was suspiciously similar - some work was done in OnLoaded, that was called for initially collapsed controls way before template with all parts is applied. Look at phrase in first post of the current thread:
> 
> > Move UpdateSpinButtonPlacement to **OnLoaded** so TextBox visual states can be updated properly
> 
> So, my post is rather a hint to the forthcoming investigator, that maybe OnLoaded - is a bad place to touch or tune parts of the template

@eugenegff Your assessment is incorrect. TextBox element within NumberBox is not yet loaded when OnApplyTemplate is called, so its VisualStates are not set properly, causing the spin buttons to overlap. 

@ArchieCoder I opened a new PR #8477 that fixes this issue. It attaches the Loaded event handler to TextBox instead of NumberBox itself. Thanks for the repro app, I was able use it to verify.
