### PR TITLE
Exclude MoreButton if Not using PrimaryCommands

### LINKED ISSUE #5857: Focus disappears in CommandBarFlyout with SecondaryCommands, no PrimaryCommands
**Describe the bug**

When using the `CommandBarFlyout` with `SecondaryCommands` and without `PrimaryCommands`, the focus can still land on the "See less" button part of the `PrimaryCommands` panel even though it isn't visualized.

Focus isn't really *lost*, since it can be recovered by continuing to arrow through the items. But it is confusing.

**Steps to reproduce the bug**

1. Open a `CommandBarFlyout` instance that uses `SecondaryCommands`, but no `PrimaryCommands`.
2. Use arrow keys to move focus beyond the first or last item.
3. Observe the focus disappears and the "See less" button tooltip is displayed.

```
<Page
    x:Class="CommandBarFlyoutTest.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:CommandBarFlyoutTest"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:winui="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <StackPanel Spacing="4" Margin="48">
        <TextBlock>Invoke the button to show the flyout, then use the arrow keys to navigate up.</TextBlock>
        <TextBlock>You should see the focus visual disappear and a tooltip for the "See less" button, a part of the non-visible primary commands section of the CommandBarFlyout control.</TextBlock>
        <TextBlock>I would expect to not be able to focus on the "See less" button if it is not being visualized.</TextBlock>
        <Button Name="ShowButton" Content="Show flyout">
            <Button.Flyout>
                <winui:CommandBarFlyout Opened="OnFlyoutOpened" Closed="OnFlyoutClosed">
                    <winui:CommandBarFlyout.SecondaryCommands>
                        <AppBarButton Label="Option 1" />
                        <AppBarButton Label="Option 2" />
                    </winui:CommandBarFlyout.SecondaryCommands>
                </winui:CommandBarFlyout>
            </Button.Flyout>
        </Button>
    </StackPanel>
</Page>
```

```
using System.Linq;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;

namespace CommandBarFlyoutTest
{
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();

            Loaded += OnLoaded;
        }

        private void OnLoaded(object sender, RoutedEventArgs e)
        {
            // Set initial focus on load.
            ShowButton.Focus(FocusState.Keyboard);
        }

        private void OnFlyoutOpened(object sender, object e)
        {
            if (sender is Microsoft.UI.Xaml.Controls.CommandBarFlyout flyout)
            {
                var firstItem = flyout.SecondaryCommands.FirstOrDefault();
                if (firstItem is AppBarButton button)
                {
                    // Set focus to the first item.
                    button.Focus(FocusState.Programmatic);
                }
            }
        }

        private void OnFlyoutClosed(object sender, object e)
        {
            // Set focus back to the show button.
            ShowButton.Focus(FocusState.Programmatic);
        }
    }
}
```

**Expected behavior**

I would expect to not be able to focus on the "See less" button if it is not being visualized.

**Screenshots**

Button:
image

Flyout opened:
image

Focus is hidden, "See less" is visible:
image

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.6.2

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000)              | Yes  |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

### PR DESCRIPTION
**Pull request by karenbtlai**
## Description

If no PrimaryCommands is present, the SeeMore button is still visible and focusable, causing keyboard accessibility issues. 

The fix is to check if `PrimaryCommands().Size() > 0` at  `PopulateAccessibleControls()` on `PrimaryCommands().VectorChanged()`. If size is 0, the SeeMore button is excluded from being populated in the horizontally and vertically accessible controls member variable, and is no longer accessible.

## Motivation and Context

Fixes #5857 and internal bug 35345814

### CODE REVIEW

**Review by llongley — APPROVED** [review]

File: dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs [hunk 1]
```diff
@@ -992,5 +992,86 @@ public void VerifyDynamicSecondaryCommandLabel()
...
+                    Button favoriteToggleButton6 = FindElement.ById<Button>("FavoriteToggleButton6");
+                    var favoriteToggleElement = AutomationElement.FocusedElement;
+                    Verify.AreEqual(favoriteToggleElement.Current.AutomationId, favoriteToggleButton6.AutomationId);
+                }
+            }
+        }
+
+        [TestMethod]
+        public void VerifyAddRemovePrimaryCommands()
+        {
```
Comment (StephenLPeters) [inline dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs:1037]: This test doesn't test the removal of a primary command, only the addition of one.

More importantly, I wouldn't expect the behavior to fail when you change the number of commands in the CBF while it is closed.  The bug I called out in the product code would only happen if you change the number of commands while the flyout is open.

**Review by StephenLPeters — CHANGES_REQUESTED** [review]

File: dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs (hunk 1 above)
Comment (karenbtlai) [reply dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs:1037]: I don't think there is a scenario where the number of commands will change while the flyout is open, since CBF is a flyout and transient by design.

Comment (karenbtlai) [reply dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs:1037]: Discussed offline. Test case is updated to be adding PrimaryCommands dynamically.

Comment (StephenLPeters) [reply dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs:1037]: For completeness removing the last primary command could also be tested. It uses what looks like the same code path though so maybe it is fine.

File: dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp [hunk 2]
```diff
@@ -678,7 +678,7 @@ void CommandBarFlyoutCommandBar::UpdateTemplateSettings()
             collapsedWidth = static_cast<float>(expandedWidth);
         }
 
-        flyoutTemplateSettings->WidthExpansionDelta(collapsedWidth - expandedWidth);
+        flyoutTemplateSettings->WidthExpansionDelta(0);
```
Comment (StephenLPeters) [inline dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp:681]: I don't understand this change, but if @llongley or someone else does that is good enough.

**Review by StephenLPeters — APPROVED** [review]
Make sure that the WidthExpansionDelta change makes sense.

File: dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp (hunk 2 above)
Comment (llongley) [reply dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp:681]: I thought there was a need for a nonzero value for this, but Karen said that she tested all of the scenarios and they all continue to look right, so if that's the case it seems OK to me.

Comment (karenbtlai) [reply dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp:681]: When PrimaryCommands are being loaded dynamically, it causes a weird crop issue that is caused by a negative `WidthExpansionDelta`. Setting it to 0 fixes this specific use case. Upon investigation, it seems a non-zero `WidthExpansionDelta` is only for when SecondaryCommands is collapsed, and the width of primaryCommands is less than the width of SecondaryCommands, so the flyout expands to the full width when opening the secondaryCommands. 

However, setting it to 0 doesn't seem to break that scenario. This may be because CBF no longer has the expanding animation. I manually all scenarios with and without the `WidthExpansionDelta` change, and it doesn't change or break anything.

Comment (StephenLPeters) [reply dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp:681]: The CBF does have the expanding animation still though, there is a button for it on the CommandBarFlyout test page labeled "Show expanding CommandBarFlyout"

This is the behavior before this change:


https://user-images.githubusercontent.com/7758786/141835292-2f6c4da9-cf1f-42d2-9a5f-f2c4cec69916.mp4


and this is the behavior after the change

https://user-images.githubusercontent.com/7758786/141831780-7a9e8b14-bb52-47c8-bdaf-7fea2d885109.mp4

Comment (karenbtlai) [reply dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp:681]: Ah I now see a subtle expanding animation that is missing from the update. I think the appropriate action is to revert the hardcoding of ExpansionWidthDelta, and fix the dynamically adding primary buttons in a separate fix. It is beyond the scope of the original accessibility bug to begin with.
