### PR TITLE
Fix TreeView expand

### LINKED ISSUE #1790: TreeViewItem Template IsExpanded ignored when reused
**Describe the bug**
```
        <muxc:TreeView x:Name="SyntaxTree"
                       ItemsSource="{x:Bind RootNodes, Mode=OneWay}">
            <muxc:TreeView.ItemTemplate>
                <DataTemplate x:DataType="local:XmlSyntaxData">
                    <muxc:TreeViewItem ItemsSource="{x:Bind Children}"
                                       IsExpanded="True">
                       <TextBlock Text="{Binding}"/>
                    </muxc:TreeViewItem>
                </DataTemplate>
            </muxc:TreeView.ItemTemplate>
        </muxc:TreeView>
```
I have a dependency property named RootNodes (a List of a hierarchical data type) bound to the TreeView.  When I set this property the first time, the tree view populates items from the data structure and all the nodes are expanded as would be expected.

When I set this property again a 2nd time and change the list, the tree view items are regenerated; however, they are now not in an expanded state.  They should be in an expanded state.

**Steps to reproduce the bug**

1. Use XAML structure above to configure a set of TreeViewItems
2. Replace the itemssource reference

**Expected behavior**
All TreeViewItems should be expanded as specified in the template.

**Screenshots**
First time:
image

Second time:
image

(Sometimes inconsistent results, e.g. first node will be expanded, but only first node, all other nodes still collapsed, unlike initial behavior.)

**Version Info**
NuGet package version: Microsoft.UI.XAML 2.3.191211002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19041.1)              | Yes |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

### PR DESCRIPTION
**Pull request by kaiguo**
## Description

We made changes in previous PR #1917 to update expand state when ItemsSource changes, it doesn't work as expected when ItemsSource is set in an async way. PrepareContainerForItemOverride is a better place to do this, this should keep the property value and actual expand state always in sync.

## Motivation and Context

Fix #1790.

## How Has This Been Tested?

Added more interaction tests.

### CODE REVIEW

File: dev/TreeView/TreeViewList.cpp [hunk 1]
```diff
@@ -320,6 +320,15 @@ void TreeViewList::PrepareContainerForItemOverride(winrt::DependencyObject const
     {
         bool hasChildren = itemContainer.HasUnrealizedChildren() || itemNode->HasChildren();
         itemContainer.GlyphOpacity(hasChildren ? 1.0 : 0.0);
+        if (itemContainer.IsExpanded() != itemNode->IsExpanded()) {
+            auto dispatcher = winrt::Window::Current().Dispatcher();
```
Comment (StephenLPeters) [inline dev/TreeView/TreeViewList.cpp]: >auto dispatcher = winrt::Window::Current().Dispatcher(); [](start = 12, length = 56)

I think this is supposed to come from dispatcher pool, rather than window.current to be islands safe.  @kmahone might be able to confirm?

Comment (StephenLPeters) [inline dev/TreeView/TreeViewList.cpp]: >dispatcher [](start = 17, length = 10)

const

Comment (kmahone) [reply dev/TreeView/TreeViewList.cpp]: Yeah. Use DispatcherHelper (dev\inc\DispatcherHelper.h) to get the correct behavior.

File: dev/TreeView/TreeViewList.cpp [hunk 2]
```diff
@@ -320,6 +320,14 @@ void TreeViewList::PrepareContainerForItemOverride(winrt::DependencyObject const
     {
         bool hasChildren = itemContainer.HasUnrealizedChildren() || itemNode->HasChildren();
         itemContainer.GlyphOpacity(hasChildren ? 1.0 : 0.0);
+        if (itemContainer.IsExpanded() != itemNode->IsExpanded()) {
+            const DispatcherHelper dispatcher{ *this };
```
Comment (ranjeshj) [inline dev/TreeView/TreeViewList.cpp]: I'm curious why you need to run this though the dispatcher async.

File: dev/TreeView/TreeViewItem.cpp [hunk 3]
```diff
@@ -331,7 +331,6 @@ void TreeViewItem::OnPropertyChanged(const winrt::DependencyPropertyChangedEvent
                 // The children have changed, validate and update GlyphOpacity
                 bool hasChildren = HasUnrealizedChildren() || treeViewNode->HasChildren();
                 GlyphOpacity(hasChildren ? 1.0 : 0.0);
-                UpdateNodeIsExpandedAsync(*treeViewNode, IsExpanded());
```
Comment (ranjeshj) [inline dev/TreeView/TreeViewItem.cpp]: Do you still need to do it in the case where the container is already prepared and then the source gets set on the node after that?

File: dev/TreeView/TreeViewList.cpp (hunk 2 above)
Comment (kaiguo) [reply dev/TreeView/TreeViewList.cpp]: > I'm curious why you need to run this though the dispatcher async.
> 
It crashes if we don't use a dispatcher, I think it's still the same reason, changing expand state will change ListView's ItemsSource as we are adding/removing items from ListView, and this can't be done during layout.

> Also, should'nt it be the other way ? we are creating the container based on the data, so I would think we need to set the container's value to what the node has.
>
Yeah this is confusing, in content mode, TreeViewItem (which is the container) holds the truth since we are using data binding, and in node mode it's the opposite, TreeViewNode holds the truth (at line 334 we are updating container based on TreeViewNode's state).

File: dev/TreeView/TreeViewItem.cpp (hunk 3 above)
Comment (kaiguo) [reply dev/TreeView/TreeViewItem.cpp]: I think PrepareContainerForItem will get called every time we change ItemsSource? There were some odd behaviors when keeping them both in place. I guess it caused some race conditions because the operation is async...
