### PR TITLE
Ensure `BringIntoView` request is not skipped for direct content of `ScrollView`

### LINKED ISSUE #6888: `ScrollViewPresenter` BringIntoView handling does not properly handle direct content
### Describe the bug

When `StartBringIntoView` is called on the direct content of `ScrollView`, nothing happens.

### Steps to reproduce the bug

Consider the following:

```xaml
<ScrollViewer x:Name="InnerSV" Height="200" Background="Blue" Margin="0,400,0,0" Padding="20">
    <Border x:Name="Item" Background="Red" Width="100" Height="100" Margin="0,600,0,0" />
</ScrollViewer>
```
When `Item.StartBringIntoView()` is called, nothing happens.

### Expected behavior

Should bring into view.

### Screenshots

_No response_

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

_No response_

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MartinZikmund**
## Description

The logic in `ScrollPresenter` skips `BringIntoView` request if it is called for its direct content (even though it may be relevant if it has high `Margin`.

## Motivation and Context

Fixes #6888 

## How Has This Been Tested?

Manually, added API test

### CODE REVIEW

**Comment by ojhad** [comment]
@RBrid could you take a look?

**Comment by MartinZikmund** [comment]
Seems test is failing - I was not able to run tests locally with WinUI solution yet (only under Uno Platform), I will try again

File: dev/ScrollPresenter/APITests/ScrollPresenterTests.cs [hunk 1]
```diff
@@ -879,6 +879,40 @@ public void ListenToContentEffectiveViewportChanged()
             });
         }
 
+        [TestMethod]
+        [TestProperty("Description", "ScrollPresenter should handle BringIntoView for its direct content.")]
+        public void HandleContentBringIntoView()
```
Comment (RBrid) [inline dev/ScrollPresenter/APITests/ScrollPresenterTests.cs:884]: This test (I renamed and fixed it) should be added to ScrollPresenterBringIntoViewTests.cs where bring-into-view tests are all located:

```
        [TestMethod]
        [TestProperty("Description", "ScrollPresenter must handle BringIntoView request for its direct Content with a large Margin.")]
        public void BringContentWithMarginIntoView()
        {
            ScrollPresenter scrollPresenter = null;
            Shapes.Rectangle rectangleScrollPresenterContent = null;
            AutoResetEvent scrollPresenterViewChangedEvent = new AutoResetEvent(false);
            AutoResetEvent scrollPresenterLoadedEvent = new AutoResetEvent(false);

            RunOnUIThread.Execute(() =>
            {
                rectangleScrollPresenterContent = new Shapes.Rectangle()
                {
                    Margin = new Thickness(0, 500, 0, 0)
                };
                scrollPresenter = new ScrollPresenter();

                SetupDefaultUI(scrollPresenter, rectangleScrollPresenterContent, scrollPresenterLoadedEvent);
            });

            WaitForEvent("Waiting for Loaded event", scrollPresenterLoadedEvent);

            RunOnUIThread.Execute(() =>
            {
                scrollPresenter.ViewChanged += delegate (ScrollPresenter sender, object args)
                {
                    Log.Comment("ViewChanged - HorizontalOffset={0}, VerticalOffset={1}, ZoomFactor={2}",
                        sender.HorizontalOffset, sender.VerticalOffset, sender.ZoomFactor);
                    scrollPresenterViewChangedEvent.Set();
                };

                Log.Comment("Calling ScrollPresenter.Content.StartBringIntoView");
                rectangleScrollPresenterContent.StartBringIntoView(new BringIntoViewOptions() { AnimationDesired = false });
            });

            WaitForEvent("Waiting for ViewChanged event", scrollPresenterViewChangedEvent);

            RunOnUIThread.Execute(() =>
            {
                Verify.IsGreaterThan(scrollPresenter.VerticalOffset, 0.0);
            });
        }

```

File: dev/ScrollPresenter/APITests/ScrollPresenterTests.cs [hunk 2]
```diff
@@ -879,6 +879,40 @@ public void ListenToContentEffectiveViewportChanged()
...
+            RunOnUIThread.Execute(() =>
+            {
+                scrollPresenter.ViewChanged += (s, e) =>
+                {
+                    scrollPresenterViewChangedEvent.Set();
+                };
+
+                rectangleScrollPresenterContent.StartBringIntoView(new BringIntoViewOptions() { AnimationDesired = false });
+
+                WaitForEvent("Waiting for ViewChanged event", scrollPresenterViewChangedEvent);
```
Comment (RBrid) [inline dev/ScrollPresenter/APITests/ScrollPresenterTests.cs:911]: Reason 1 for test failure:
WaitForEvent cannot be used inside a RunOnUIThread.Execute...
It must run off the UI thread.

File: dev/ScrollPresenter/APITests/ScrollPresenterTests.cs [hunk 3]
```diff
@@ -879,6 +879,40 @@ public void ListenToContentEffectiveViewportChanged()
...
+                Verify.IsGreaterThan(scrollPresenter.VerticalOffset, 0);
```
Comment (RBrid) [inline dev/ScrollPresenter/APITests/ScrollPresenterTests.cs:912]: Reason 2 for test failure:
VerticalOffset is a Double and must be compared to a Double: 0.0

**Review by RBrid — CHANGES_REQUESTED** [review]
The ScrollPresenter.cpp changes look good.
Thanks for fixing this!

File: dev/ScrollPresenter/APITests/ScrollPresenterTests.cs (hunk 3 above)
Comment (MartinZikmund) [reply dev/ScrollPresenter/APITests/ScrollPresenterTests.cs]: Fixed

File: dev/ScrollPresenter/APITests/ScrollPresenterTests.cs (hunk 2 above)
Comment (MartinZikmund) [reply dev/ScrollPresenter/APITests/ScrollPresenterTests.cs]: Fixed

File: dev/ScrollPresenter/APITests/ScrollPresenterTests.cs (hunk 1 above)
Comment (MartinZikmund) [reply dev/ScrollPresenter/APITests/ScrollPresenterTests.cs:884]: Ah, didn't notice this and fixed it also 😀  . Anyway, at least fixed local debugging of tests. I will move the tests to the correct location, thanks!

**Review by RBrid — APPROVED** [review]
