### PR TITLE
Switch PersonPicture control to use VSM to change FontFamily/Text for visual states

### LINKED ISSUE #311: There is a bug when PersonPicture in ListView？
**Describe the bug**
There is a bug when `PersonPicture` in `ListView`?  
I tried to bind a **FontFamily** to `PersonPicture`, it works for a single `PersonPicture`, but in `ListView`, the binding does not seem to work.

**Steps to reproduce the bug**

### Result

image

### Code behind

```cs
public sealed partial class TestPage : Page
{
    public TestPage()
    {
        InitializeComponent();
        Fonts = new List<FontFamily>
        {
            new FontFamily("Segoe MDL2 Assets"),
            new FontFamily("Segoe MDL2 Assets"),
            new FontFamily("Segoe MDL2 Assets")
        }
    }

    public List<FontFamily> Fonts { get; }
}
```

### XAML

```xaml
<StackPanel Padding="32" Orientation="Horizontal">
    <ListView ItemsSource="{x:Bind Fonts}">
        <ListView.ItemTemplate>
            <DataTemplate x:DataType="FontFamily">
                <StackPanel Orientation="Horizontal">
                    <PersonPicture DisplayName="Test" Initials="&#xE13D;" FontFamily="Segoe MDL2 Assets"/>
                    <TextBlock Text="&#xE13D;" FontFamily="{x:Bind}"/>
                </StackPanel>
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>

    <ListView ItemsSource="{x:Bind Fonts}">
        <ListView.ItemTemplate>
            <DataTemplate x:DataType="FontFamily">
                <StackPanel Orientation="Horizontal">
                    <PersonPicture DisplayName="Test" Initials="&#xE13D;" FontFamily="{x:Bind}"/>
                    <TextBlock Text="&#xE13D;" FontFamily="{x:Bind}"/>
                </StackPanel>
            </DataTemplate>
        </ListView.ItemTemplate>
    </ListView>
</StackPanel>
```

| Windows 10 version                  | Saw the problem? |
| :-------------------- | :------------------- |
| October 2018 Update (17763)   | Yes |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |

### PR DESCRIPTION
**Pull request by jevansaks**
Fixes #311

This control is doing a bit too much UI manipulation from code-behind and the logic isn't accounting for the user setting the FontFamily of the control to something custom post-initialization. I've switched to a VSM-based approach, which also requires that I add a PersonPictureTemplateSettings type.

I'm going to run the new API through the API process before I check in.

### CODE REVIEW

File: dev/PersonPicture/PersonPicture.cpp [hunk 1]
```diff
@@ -141,64 +138,39 @@ void PersonPicture::UpdateIfReady()
...
-        else
-        {
-            // Change the FontFamily of text block to original setting
-            initialsTextBlock.FontFamily(m_personTextFontFamily.get());
-
-            // Assign the initials of contact to text block 
-            winrt::hstring content = (!ProfilePicture()) ? initials : L"";
-            initialsTextBlock.Text(content);
-        }
+        winrt::ImageBrush imageBrush;
```
Comment (licanhua) [inline dev/PersonPicture/PersonPicture.cpp]: I suggest we check if templateSettings->EffectiveImageBrush.ImageSource == imageSrc. Otherwise we will trig a  lot of propertychanged event since UpdateIfReady is called everywhere

File: dev/PersonPicture/PersonPicture.xaml [hunk 2]
```diff
@@ -19,9 +19,26 @@
...
+                                <VisualState x:Name="NoPhotoOrInitials">
+                                    <VisualState.Setters>
+                                        <Setter Target="InitialsTextBlock.FontFamily" Value="Segoe MDL2 Assets"/>
+                                        <Setter Target="InitialsTextBlock.Text" Value="&#xE77B;"/>
+                                    </VisualState.Setters>
+                                </VisualState>
+                                <!-- Visual State when in Group mode -->
+                                <VisualState x:Name="Group">
+                                    <VisualState.Setters>
+                                        <Setter Target="InitialsTextBlock.FontFamily" Value="Segoe MDL2 Assets"/>
```
Comment (licanhua) [inline dev/PersonPicture/PersonPicture.xaml]: >Segoe MDL2 Assets [](start = 93, length = 17)

Why do we need "Segoe MDL2 Assets" other than "TemplateBinding FontFamily" here?

File: dev/PersonPicture/PersonPicture.cpp (hunk 1 above)
Comment (jevansaks) [reply dev/PersonPicture/PersonPicture.cpp]: I'll fix to avoid recreating the ImageBrush if we don't need to, but I'll leave the image source check to the implementation of ImageBrush.

File: dev/PersonPicture/PersonPicture.xaml (hunk 2 above)
Comment (jevansaks) [reply dev/PersonPicture/PersonPicture.xaml]: Because the default for the control is Segoe UI -- in the case of Group display or no Initials then we need to display a symbol. So in those VSM states we temporarily override the FontFamily and Text display. Otherwise we just use the value inherited from Control.

File: dev/PersonPicture/PersonPicture.xaml [hunk 3]
```diff
@@ -19,9 +19,26 @@
...
+                                    <VisualState.Setters>
+                                        <Setter Target="PersonPictureEllipse.Fill" Value="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=TemplateSettings.EffectiveImageBrush}"/>
+                                    </VisualState.Setters>
+                                </VisualState>
+                                <!-- Visual State when no Photo is available (but there are initials).-->
                                 <VisualState x:Name="Initials" />
+                                <VisualState x:Name="NoPhotoOrInitials">
+                                    <VisualState.Setters>
+                                        <Setter Target="InitialsTextBlock.FontFamily" Value="Segoe MDL2 Assets"/>
+                                        <Setter Target="InitialsTextBlock.Text" Value="&#xE77B;"/>
```
Comment (StephenLPeters) [inline dev/PersonPicture/PersonPicture.xaml]: Maybe a comment saying what this is would be useful.

Comment (jevansaks) [reply dev/PersonPicture/PersonPicture.xaml]: Added a comment.

File: dev/Generated/PersonPicture.properties.cpp [hunk 4]
```diff
@@ -136,6 +137,17 @@ void PersonPictureProperties::EnsureProperties()
                 ValueHelper<winrt::ImageSource>::BoxedDefaultValue(),
                 winrt::PropertyChangedCallback(&OnPropertyChanged));
     }
+    if (!s_TemplateSettingsProperty)
```
Comment (chrisglein) [inline dev/Generated/PersonPicture.properties.cpp]: Didn't you make some generated goop for creating new DPs?

Comment (jevansaks) [reply dev/Generated/PersonPicture.properties.cpp]: Yes, this is all generated code.
