### PR TITLE
Fix crash in RefreshVisualizer when not wrapping a ScrollViewer

### LINKED ISSUE #1277: RefreshVisual Icon is always shown
**Describe the bug**
RefreshVisual Icon is always shown prevent clicking on item behind that icon

**Steps to reproduce the bug**

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

### PR DESCRIPTION
**Pull request by jevansaks**
The last change I made here added a test -- that test is crashing because the RefreshVisualizer doesn't actually wrap a ScrollViewer or something that can be "adapted". We shouldn't crash in this case, however. Adding an if check to fix that failing test.

Fixes #1277

### CODE REVIEW

File: dev/PullToRefresh/RefreshVisualizer/RefreshVisualizer.cpp [hunk 1]
```diff
@@ -298,7 +298,13 @@ void RefreshVisualizer::UpdateContent()
             contentVisual.Opacity(1.0f);
             if (m_root)
             {
-                float translationRatio = (1.0f - (float)(m_refreshInfoProvider.get().ExecutionRatio())) * PARALLAX_POSITION_RATIO;
+                float translationRatio = [this]() {
+                    if (auto&& refreshInfoProvider = m_refreshInfoProvider.get())
+                    {
+                        return (1.0f - (float)(refreshInfoProvider.ExecutionRatio())) * PARALLAX_POSITION_RATIO;
+                    }
+                    return 0.0f;
```
Comment (StephenLPeters) [inline dev/PullToRefresh/RefreshVisualizer/RefreshVisualizer.cpp]: A default translation ratio of 0.0 is probably wrong. It means that a refresh will be triggered when we have pulled 0% of the visualizers height, I'm not sure what the symptoms of this would be but I think a 1.0 default value (triggers a refresh when 100% of the visualizers length has been pulled) would be safer.
