### PR TITLE
Fixed NavView in ContentDialog crash

### LINKED ISSUE #2713: NavigationView inside ContentDialog causes crash in WinUI3 Desktop
**Describe the bug**

The NavigationView inside the ContentDialog causes the application to crash.

We have the NavigationView inside the ContentDialog working in UWP. 

When moved over to WinUI3 Desktop, the application crashes before the NavigationView can load.

**Steps to reproduce the bug**

1. Clone the [WinUI3 Problems DialogWithNavView repository](https://github.com/eleanorleffler/WinUI3_Problems_DialogWithNavView). 
2. Go to the DialogWithNavViewWinUI folder.
3. Open the DialogWithNavViewWinUI solution in Visual Studio 2019 Preview.
4. Build and run with Debug x64.
4. Click the "Click me" button.
5. You should see that the ContentDialog does not appear, and the application crashes with an error. See Screenshot#1.

**Expected behavior**

After clicking on the "Click me" button, we expect to see the NavigationView inside the ContentDialog. See Screenshot#2 below for expected behavior.

We expect to see the same behavior we saw in UWP. Build and run the DialogWithNavViewUWP solution inside the DialogWithNavViewUWP folder to see expected behavior.

**Screenshots**

DialogWithNavViewErrorMessage

Screenshot#1 - Current Behavior (Error Message)

DialogWithNavViewExpectedBehavior

Screenshot#2 - Expected Behavior

**Version Info**

NuGet package version: 
[Microsoft.VCRTForwarders.140 1.0.6]
[Microsoft.WinUI 3.0.0-preview1.200515.3]

Targeting:
Target: Universal Windows
Target version: Windows 10, version 1809 (10.0; Build 17763)
Min version: Windows 10, version 1809 (10.0; Build 17763)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |                       |
| November 2019 Update (18363)  	 |                       |
| May 2019 Update (18362)            |                       |
| October 2018 Update (17763)        | Yes                   |
| April 2018 Update (17134)          |                       |
| Fall Creators Update (16299)       |                       |
| Creators Update (15063)            |                       |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop               | Yes                  |
| Mobile                |                      |
| Xbox                  |                      |
| Surface Hub           |                      |
| IoT                   |                      |

**Additional context**

If the NavigationView is removed or commented out, the application does not crash and the ContentDialog is displayed (without NavigationView).

To demonstrate this, comment out line numbers 16 - 22 in DialogWithNavView.xaml.

### PR DESCRIPTION
**Pull request by ojhad**
## Description

When NavView is shown in a ContentDialog, there is a scenario where the SplitView tries to add children to the popup root while it is being measured (which causes a crash since NavView itself is in the popup root). Due to the fact that this SplitView API call (updating the DisplayMode property) modifies elements in the tree outside of itself, we should defer that call, whenever it comes from OnApplyTemplate, to be executed in the OnLoaded callback.

## Motivation and Context
Fixes #2713 

## How Has This Been Tested?
Added interaction test

### CODE REVIEW

File: dev/NavigationView/NavigationView_InteractionTests/CommonTests.cs [hunk 1]
```diff
@@ -1598,5 +1598,21 @@ public void VerifyExpandCollpaseFunctionality()
...
+        {
+            var testScenarios = RegressionTestScenario.BuildLeftNavRegressionTestScenarios();
+            foreach (var testScenario in testScenarios)
+            {
+                using (var setup = new TestSetupHelper(new[] { "NavigationView Tests", testScenario.TestPageName }))
+                {
+                    Log.Comment("Open a ContentDialog with a NavView inside.");
+                    Button openContentDialogButton = new Button(FindElement.ById("ContentDialogNavViewButton"));
+                    openContentDialogButton.Click();
+                    Wait.ForIdle();
```
Comment (StephenLPeters) [inline dev/NavigationView/NavigationView_InteractionTests/CommonTests.cs:1613]: >ForIdle [](start = 25, length = 7)

Did you verify that this fails without your product changes? I'm concerned there would be a timing issue and this could pass even though it would crash a second later.

**Comment by StephenLPeters** [comment]
@ojhad you have some visual verification failures

File: dev/NavigationView/NavigationView_InteractionTests/CommonTests.cs (hunk 1 above)
Comment (ojhad) [reply dev/NavigationView/NavigationView_InteractionTests/CommonTests.cs:1613]: Yeah, I did verify that test fails without the fix. However you do have a point, I updated the test to close the ContentDialog.

**Comment by StephenLPeters** [comment]
more visual verification issues, as @Felix-Dev noted, i think the pipeline is broken. hopefully @kmahone can take a look when he gets back.

**Comment by kmahone** [comment]
> more visual verification issues, as @Felix-Dev noted, i think the pipeline is broken. hopefully @kmahone can take a look when he gets back.

There was an issue in the processhelixfiles.ps1 script. I have a fix out for PR: #2959

**Comment by kmahone** [comment]
If you merge the latest master to pick up #2959 it should resolve the issue with the PR run.
