### PR TITLE
Fixed SelectionModelChildrenRequestedEventArgs returning incorrect source index

### LINKED ISSUE #1962: SelectionModelChildrenRequestedEventArgs returning incorrect source index
**Describe the bug**
The incorrect `IndexPath` is being returned when retrieving the `SourceIndex` parameter from `SelectionModelChildrenRequestedEventArgs`. It returns the `Source`'s parent's IndexPath.

**Steps to reproduce the bug**
1. Create a nested scenario within the `SelectionModel`
2. Register for the `ChildrenRequested` callback
2. Select some item that is deeper than the first level
3. Observe the `IndexPath` parameter returned in `SelectionModelChildrenRequestedEventArgs` in contrast to the `Source` parameter.

**Expected behavior**
The `IndexPath` of the `Source` item should be returned

### PR DESCRIPTION
**Pull request by ojhad**
Fixes #1962 

## Description
The incorrect `IndexPath` is being returned when retrieving the `SourceIndex` parameter from `SelectionModelChildrenRequestedEventArgs`. It returns the `Source`'s parent's `IndexPath`.
Updated the args to store and return the source's actual `IndexPath`.

## Motivation and Context
We want the `SourceIndex` to match the actual index of the `Source` object that is being passed through the args object.

## How Has This Been Tested?
Updated API test to expect this behavior

### CODE REVIEW

File: dev/Repeater/SelectionModelChildrenRequestedEventArgs.cpp [hunk 1]
```diff
@@ -33,7 +33,7 @@ winrt::IndexPath SelectionModelChildrenRequestedEventArgs::SourceIndex()
         throw winrt::hresult_error(E_FAIL, L"SourceIndex can only be accesed in the ChildrenRequested event handler.");
     }
```
Comment (StephenLPeters) [inline dev/Repeater/SelectionModelChildrenRequestedEventArgs.cpp]: This isn't used anymore right?

File: dev/Repeater/SelectionNode.cpp [hunk 2]
```diff
@@ -126,7 +126,8 @@ std::shared_ptr<SelectionNode> SelectionNode::GetAt(int index, bool realizeChild
             auto childData = m_dataSource.get().GetAt(index);
             if (childData != nullptr)
             {
-                auto resolvedChild = m_manager->ResolvePath(childData, weak_from_this());
+                auto const childDataIndexPath = winrt::get_self<class IndexPath>(IndexPath())->CloneWithChildIndex(index);
```
Comment (StephenLPeters) [inline dev/Repeater/SelectionNode.cpp]: >class [](start = 64, length = 5)

Is this class identifier needed? what does it do?

**Comment by StephenLPeters** [comment]
I'm a bit confused about why this is necessary.  If we have the node in the SelectionModelChildrenRequestedEventArgs we should be able to get the path from it right? That is broken but I feel like the correct fix is to enable that, not pass along a separate index path.

**Comment by ranjeshj** [comment]
This is a bit confusing because of the nesting. The node happens to be the parent node not the one we are trying to resolve. The data provided is the child's data (which is correct), but the index was pointing to the parent's index path. this is updating it to get to the child's index path. We cannot send the child node yet, because we are in the process of building it.

---
In reply to: [584773110](https://github.com/microsoft/microsoft-ui-xaml/pull/1963#issuecomment-584773110) [](ancestors = 584773110)

File: dev/Repeater/SelectionModelChildrenRequestedEventArgs.cpp (hunk 1 above)
Comment (ranjeshj) [reply dev/Repeater/SelectionModelChildrenRequestedEventArgs.cpp]: The check is to disallow caching the args object and calling these properties on them later. We decided to not allow that because  allocating a new args object for every event which can be a lot of allocations making it a performance issue. Also, not throwing here can cause for some confusing behavior and an error right at the point of usage will help someone from going down that rabbit hole. 

We do not need to use m_sourceNode to do this check though, we can remove it and use a bool or one of the other properties to gate the api call. A comment here describing the reason is warranted i think.

---
In reply to: [377802966](https://github.com/microsoft/microsoft-ui-xaml/pull/1963#discussion_r377802966) [](ancestors = 377802966)

File: dev/Repeater/SelectionNode.cpp (hunk 2 above)
Comment (ojhad) [reply dev/Repeater/SelectionNode.cpp]: This is needed to eliminate confusion between the type and the IndexPath function.

File: dev/Repeater/SelectionModelChildrenRequestedEventArgs.cpp (hunk 1 above)
Comment (ojhad) [reply dev/Repeater/SelectionModelChildrenRequestedEventArgs.cpp]: Replaced m_sourceNode with a bool in order to act as a sentinel
