### PR TITLE
NavigationView not updating UIA users about changed selection and expand state

### LINKED ISSUE #2599: XAML Controls Gallery : Narrator does not announce about the state of "Account", Document options" upon activating the button in Navigation View.
Copied from internal [issue](https://microsoft.visualstudio.com/OS/_workitems/edit/26617896?src=WorkItemMention&src-action=artifact_link).

**Pre-requisite:** 
Install XAML CONTROLS Gallery from Store
Turn on Narrator.
Set narrator to item mode.

**Repro steps :**
Launch XAML Control Gallery app.
Activate "NavigationView" page from All Controls Page.
Navigate to "Hierarchical Navigation View ->Accounts and activate it.
Observe the narrator description .

**Expected result :**
Narrator should announce about the state of "Account", Document options" upon activating the button in Navigation View as expanded.

**Actual result :** 
Narrator does not announce about the state of "Account", Document options" upon activating the button in Navigation View. 

Xaml_narrator

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

For UIA to be register when the selection and expand state changed, we need to raise the appropriate events at the right time.

## Motivation and Context

Closes #2599 
## How Has This Been Tested?

Expand/Collapse: Manually tested
Selection: Manually tested, not working

# Open Questions:
#### Selection updating DOES NOT WORK! I've committed the different variants of what I have tried to get Narrator to read out the new selected item, however those do not work. I haven't found anything else regarding which event/method to use here; TreeView seems to rely on the underlying ListView to handle the selection state.

### CODE REVIEW

File: dev/NavigationView/NavigationViewItem.cpp [hunk 1]
```diff
@@ -240,6 +240,19 @@ void NavigationViewItem::SuggestedToolTipChanged(winrt::IInspectable const& newC
...
 
+void NavigationViewItem::OnIsExpandedPropertyChanged(const winrt::DependencyPropertyChangedEventArgs& args)
+{
+    if (winrt::AutomationPeer peer = winrt::FrameworkElementAutomationPeer::FromElement(*this))
+    {
+        auto navViewItemPeer = peer.as<winrt::NavigationViewItemAutomationPeer>();
+        winrt::get_self<NavigationViewItemAutomationPeer>(navViewItemPeer)->RaiseExpandCollapseAutomationEvent(
+            IsExpanded() ?
+                winrt::ExpandCollapseState::Expanded
+                : winrt::ExpandCollapseState::Collapsed
```
Comment (StephenLPeters) [inline dev/NavigationView/NavigationViewItem.cpp:251]: nit: this formatting is a bit weird, I'd move the colon up a line.

File: dev/NavigationView/NavigationViewAutomationPeer.cpp [hunk 2]
```diff
@@ -50,3 +50,18 @@ winrt::com_array<winrt::Windows::UI::Xaml::Automation::Provider::IRawElementProv
...
+    if (winrt::AutomationPeer::ListenerExists(winrt::AutomationEvents::SelectionPatternOnInvalidated))
+    {
+        //RaiseAutomationEvent(winrt::AutomationEvents::SelectionPatternOnInvalidated);
+        //RaiseAutomationEvent(winrt::AutomationEvents::SelectionItemPatternOnElementSelected);
+
+        // box_value(oldState) doesn't work here, use ReferenceWithABIRuntimeClassName to make Narrator can unbox it.
+        //RaisePropertyChangedEvent(winrt::SelectionPatternIdentifiers::SelectionProperty(),
+        //    box_value(oldSelection),
+        //    box_value(newSelecttion)
+        //);
```
Comment (StephenLPeters) [inline dev/NavigationView/NavigationViewAutomationPeer.cpp:65]: Do we have theories about why this isn't working?

File: dev/NavigationView/NavigationViewItem.cpp (hunk 1 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationViewItem.cpp]: Fixed

File: dev/NavigationView/NavigationViewAutomationPeer.cpp (hunk 2 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationViewAutomationPeer.cpp:65]: Other properties seems to update just fine, the `SelectionPattern.SelectionProperty()` however didn't seem to work. Maybe it could be that we should be returning a specific type here?

The problem is that I haven't found much information on the `SelectionPatter.SelectionProperty` property or on how to use it.

Comment (StephenLPeters) [reply dev/NavigationView/NavigationViewAutomationPeer.cpp:65]: @ojhad thoughts on this?

Comment (ojhad) [reply dev/NavigationView/NavigationViewAutomationPeer.cpp:65]: @chingucoding I believe that you have to raise `SelectionItemPatternOnElementSelected` on the peer of the selected item itself.

So, for example, if you replace the commented out code you have here with the following, you should get the intended result:

```
if (auto nv = Owner().try_as<winrt::NavigationView>())
{
        if (auto nvi = winrt::get_self<NavigationView>(nv)->GetSelectedContainer())
        {
            if (auto peer = winrt::FrameworkElementAutomationPeer::CreatePeerForElement(nvi))
            {
                peer.RaiseAutomationEvent(winrt::AutomationEvents::SelectionItemPatternOnElementSelected);
            }
        }
}
```

Comment (chingucoding) [reply dev/NavigationView/NavigationViewAutomationPeer.cpp]: Thanks for the fix @ojhad !

I was able to fix the change being announced twice through quite bad hack. The issue is that expand/collapse get's changed after selection and is not aware of latest selection changes. That's why we suppress raising selection changed event iff an item has children and will be selected. If an item get's expanded but not selected we raise expand/collapse change and if an item changes selection but has no children, we raise selection changed.

File: dev/NavigationView/NavigationView.cpp [hunk 3]
```diff
@@ -1930,13 +1936,24 @@ void NavigationView::ChangeSelection(const winrt::IInspectable& prevItem, const
         UnselectPrevItem(prevItem, nextItem);
         ChangeSelectStatusForItem(nextItem, true /*selected*/);
 
-        if (winrt::AutomationPeer peer = winrt::FrameworkElementAutomationPeer::FromElement(*this))
+        // Selection changed and we need to notify UIA
+        // HOWEVER expand collapse can also trigger if an item can expand/collapse
+        // There are multiple cases when selectino changes:
```
Comment (Felix-Dev) [inline dev/NavigationView/NavigationView.cpp:1941]: While "selectino" does sound rather cool, I think we should stick with "selection" here 😁

Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp]: Haha good point, updated it.

File: dev/NavigationView/NavigationView.cpp [hunk 4]
```diff
@@ -742,6 +742,12 @@ void NavigationView::OnNavigationViewItemInvoked(const winrt::NavigationViewItem
     if (updateSelection)
     {
         auto ip = GetIndexPathForContainer(nvi);
+
+        // Determine if we will update collapse/expand which will happen on iff the item has children
```
Comment (StephenLPeters) [inline dev/NavigationView/NavigationView.cpp:746]: >will happen on iff [](start = 61, length = 18)

will happen iff

File: dev/NavigationView/NavigationView.cpp [hunk 5]
```diff
@@ -1930,13 +1936,32 @@ void NavigationView::ChangeSelection(const winrt::IInspectable& prevItem, const
...
+        {
+            if (winrt::AutomationPeer peer = winrt::FrameworkElementAutomationPeer::FromElement(*this))
+            {
+                auto navViewItemPeer = peer.as<winrt::NavigationViewAutomationPeer>();
+                winrt::get_self<NavigationViewAutomationPeer>(navViewItemPeer)->RaiseSelectionChangedEvent(
+                    prevItem, nextItem
+                );
+            }
+        }
+        m_shouldIgnoreUIASelectionRaiseAsExpandCollapseWillRaise = false;
```
Comment (StephenLPeters) [inline dev/NavigationView/NavigationView.cpp:1956]: I think  we should GSL scope guard this.

File: dev/NavigationView/NavigationView.cpp (hunk 4 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp]: Fixed

File: dev/NavigationView/NavigationView.cpp (hunk 5 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp]: Fixed

**Comment by chingucoding** [comment]
@StephenLPeters Is there any way we could test these kind of behaviors through an automatic test? I haven't found a way how we could listen to these changes, but maybe I haven't look in the right spots. In the long term of course it would be better to have this be tested automatically and not rely on manual testing.

File: dev/NavigationView/NavigationView.cpp [hunk 6]
```diff
@@ -1930,13 +1936,35 @@ void NavigationView::ChangeSelection(const winrt::IInspectable& prevItem, const
...
+                auto navViewItemPeer = peer.as<winrt::NavigationViewAutomationPeer>();
+                winrt::get_self<NavigationViewAutomationPeer>(navViewItemPeer)->RaiseSelectionChangedEvent(
+                    prevItem, nextItem
+                );
+            }
+        }
+        auto scopeGuard = gsl::finally([this]()
+        {
+            m_shouldIgnoreUIASelectionRaiseAsExpandCollapseWillRaise = false;
+        });
```
Comment (StephenLPeters) [inline dev/NavigationView/NavigationView.cpp:1959]: Sorry I meant something like this:
```
{
        auto scopeGuard = gsl::finally([this]()
        {
            m_shouldIgnoreUIASelectionRaiseAsExpandCollapseWillRaise = false;
        });

        if (!m_shouldIgnoreUIASelectionRaiseAsExpandCollapseWillRaise)
        {
            if (winrt::AutomationPeer peer = winrt::FrameworkElementAutomationPeer::FromElement(*this))
            {
                auto navViewItemPeer = peer.as<winrt::NavigationViewAutomationPeer>();
                winrt::get_self<NavigationViewAutomationPeer>(navViewItemPeer)->RaiseSelectionChangedEvent(
                    prevItem, nextItem
                );
            }
        }
}
```

This way even if a swallowed exception happens in the navigation peer we get back to the rest state correctly.

Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp]: Oh I see. Fixed it now.

**Comment by StephenLPeters** [comment]
@chingucoding could you fix the merge conflict

**Comment by chingucoding** [comment]
> @chingucoding could you fix the merge conflict

Fixed now.

**Comment by ranjeshj** [comment]
> y way we could test these kind of behaviors through an automatic test? I haven't found a way how we could listen to these changes, but maybe I haven't look in the right spots. In the long term of course it would be better to have this be tested automatically and not rely on manual testing.

@kmahone as FYI. This might be something that we are missing in the test framework.
