### PR TITLE
[Accessibility] Fix teaching tip name property in buttons

### LINKED ISSUE #6867: [TeachingTips][Accessibility] Action buttons name not read by narrator
### Describe the bug

When using teaching tips with action buttons, narrator has no property name to read. Tabbing to an action button reads as "- button" instead of the using the defined value of the action button content.

### Steps to reproduce the bug

**Pre-requisites:**
- The code use to repro the bug is the one provided on this [teaching tip guide - add buttons](https://docs.microsoft.com/en-us/windows/apps/design/controls/dialogs-and-flyouts/teaching-tip#add-buttons )
- Turn ON Narrator. (Settings -> Accessibility -> Narrator Toggle ON)

**Repro-Steps:**

1. Trigger TeachingTip
2. Tab into tip (F6)
3. Tab into action button
4. Hear narrator 

### Expected behavior

**Actual Result:** 
When the Focus lands on the action button, Narrator just announces it as button. There is no programmatic name defined for the 'Disable' or the 'Got it!' button.

Expected Result:
The expected result is that there should be a programmatic name defined for the button in the same way a visible name is defined.

### Screenshots

_No response_

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bkudiess**
When using screen readers, teaching tip action and close buttons where reading just "button" instead of text property.

Adding on property changed listener to button's content presenter and updates automation property name with new value to fix the issue.

Fixes internal bug 38395706
Fixes #6867

### CODE REVIEW

**Comment by kmahone** [comment]
Please add a test for this scenario.

File: dev/TeachingTip/TeachingTip.cpp [hunk 1]
```diff
@@ -121,6 +123,9 @@ void TeachingTip::OnApplyTemplate()
     OnIconSourceChanged();
     OnHeroContentPlacementChanged();
 
+    UpdateButtonAutomationProperties(m_actionButton.get(), m_actionButtonContent.get().Content());
```
Comment (kmahone) [inline dev/TeachingTip/TeachingTip.cpp:126]: You don't need to add these new template parts. You can just use ActionButtonContent() and CloseButtonContent() properties.

File: dev/TeachingTip/TeachingTip.cpp [hunk 2]
```diff
@@ -199,9 +199,27 @@ void TeachingTip::OnPropertyChanged(const winrt::DependencyPropertyChangedEventA
...
+        UpdateButtonsState();
+        winrt::IInspectable value = unbox_value<winrt::IInspectable>(args.NewValue());
+        UpdateButtonAutomationProperties(m_closeButton.get(), value);
+    }
 
 }
 
+void TeachingTip::UpdateButtonAutomationProperties(const winrt::Button button, const winrt::IInspectable content)
+{
+    winrt::hstring nameHString = SharedHelpers::TryGetStringRepresentationFromObject(content);
```
Comment (kmahone) [inline dev/TeachingTip/TeachingTip.cpp:219]: Add a null check for 'button' here, since someone could have retemplated and not have the button in their template.

**Review by kmahone — CHANGES_REQUESTED** [review]
:clock1:

File: dev/TeachingTip/TeachingTip.cpp [hunk 3]
```diff
@@ -199,7 +197,28 @@ void TeachingTip::OnPropertyChanged(const winrt::DependencyPropertyChangedEventA
             TeachingTipTestHooks::NotifySubtitleVisibilityChanged(*this);
         }
     }
+    else if (property == s_ActionButtonContentProperty)
+    {
+        UpdateButtonsState();
+        winrt::IInspectable value = unbox_value<winrt::IInspectable>(args.NewValue());
```
Comment (kmahone) [inline dev/TeachingTip/TeachingTip.cpp:203]: >unbox_value [](http://example.com/codeflow?start=36&length=11)

Why the need to call unbox_value here? I think arg.NewValue() is already IInspectable?

File: dev/TeachingTip/InteractionTests/TeachingTipTests.cs [hunk 4]
```diff
@@ -1012,6 +1012,24 @@ void EnableLightDismiss()
...
 
+        [TestMethod]
+        public void VerifyTeachingTipButtonsNameAutomationProperty()
+        {
+            using(var setup = new TestSetupHelper(new[] { "TeachingTip Tests", "TeachingTip Test" }))
+            {
+                elements = new TeachingTipTestPageElements();
+                SetActionButtonContentTo("Small text");
+
+                elements.GetUpdateActionNameButton().Invoke();
```
Comment (kmahone) [inline dev/TeachingTip/InteractionTests/TeachingTipTests.cs:1023]: I don't think this is testing what we want to test.

What we need to verify is:
If ActionButtonContent is set, the AutomationName of the Button matches that. You can use UIA to find the Button in the UIA tree and verify that its Automation Name is as expected.

File: dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs [hunk 5]
```diff
@@ -447,6 +447,11 @@ public void OnBringTargetIntoViewButtonClicked(object sender, RoutedEventArgs ar
             this.targetButton.StartBringIntoView(new BringIntoViewOptions());
         }
 
+        public void OnGetActionButtonAutomationNameButtonClicked(object sender, RoutedEventArgs args)
+        {
+            this.ActionNameTextBlock.Text = getTeachingTip().ActionButtonContent.ToString();
+        }
```
Comment (kmahone) [inline dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs:453]: This event handler is named strangely. And I don't think we need it. See me comment in TeachingTipTests.cs.

File: dev/TeachingTip/InteractionTests/TeachingTipTests.cs [hunk 6]
```diff
@@ -1012,6 +1012,27 @@ void EnableLightDismiss()
...
+                SetActionButtonContentTo("Small text");
+                SetCloseButtonContent(CloseButtonContentOptions.ShortText);
+
+                OpenTeachingTip();
+
+                var actionButton = FindElement.ById("ActionButton");
+                var closeButton = FindElement.ById("CloseButton");
+
+                Log.Comment("Verify that action and close buttons content presenter text will update the buttons name automation property");
+                Verify.AreEqual(actionButton.Name, "A:Short Text.");
```
Comment (kmahone) [inline dev/TeachingTip/InteractionTests/TeachingTipTests.cs:1031]: >"A:Short Text." [](http://example.com/codeflow?start=51&length=15)

Is this not going to be "Small text"?

Comment (bkudiess) [reply dev/TeachingTip/InteractionTests/TeachingTipTests.cs:1031]: No, it sets the content to "A:Short Text." in the code behind
`getTeachingTip().ActionButtonContent = "A:Short Text.";`

**Review by kmahone — APPROVED** [review]
:shipit:
