### PR TITLE
NavigationView PaneFooter Icon Fix

### LINKED ISSUE #4482: NavigationViewItem Icon disappear in NavigationView PaneFooter (2.6 prerelease)
**Describe the bug**

The icon of NavigationViewItems in the PaneFooter disappear.

**Steps to reproduce the bug**

Add some NavigationViewItems with an icon  in a PaneFooter

**Expected behavior**

Icon appear like in MenuItems

**Screenshots**
NoIcon_Close
NoIcon_Open

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml.2.6.0-prerelease.210227001]
[Microsoft.UI.Xaml.2.6.0-prerelease.210217002]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Was working until: 
[Microsoft.UI.Xaml.2.6.0-prerelease.210129001]

### PR DESCRIPTION
**Pull request by karenbtlai**
## Description

NavigationViewItem in PaneFooter is not prepped with an ItemsRepeater, does not have reference to NavigationView, so was not properly binded to `TemplateSettings.IconColumnWidth` and `TemplateSettings.SmallerIconColumnWidth`. This PR Fixes that so the icon in PaneFooter in compact mode shows properly.

- Adds reference in NavigationViewItemBase::OnLoaded if m_navigationView reference is not found
- Move SplitView and ItemsRepeater prep from OnApplyTemplate to OnLoaded
- Add TestPage and tests

## Motivation and Context

Fixes #4482

## How Has This Been Tested?

Added tests

### CODE REVIEW

File: dev/NavigationView/NavigationView.cpp [hunk 1]
```diff
@@ -709,6 +709,7 @@ void NavigationView::OnApplyTemplate()
     UpdatePaneTitleMargins();
     UpdatePaneLayout();
     UpdatePaneOverlayGroup();
+    AddNavigationViewReferenceToPaneFooter();
```
Comment (ranjeshj) [inline dev/NavigationView/NavigationView.cpp:712]: Do you need to call this during ApplyTemplate ?

File: dev/NavigationView/NavigationView.cpp [hunk 2]
```diff
@@ -3999,6 +4000,7 @@ void NavigationView::OnPropertyChanged(const winrt::DependencyPropertyChangedEve
     else if (property == s_PaneFooterProperty)
     {
         UpdatePaneLayout();
+        AddNavigationViewReferenceToPaneFooter();
```
Comment (ranjeshj) [inline dev/NavigationView/NavigationView.cpp:4003]: args.NewValue has the element set as the PaneFooter, so you can just check if that is a NavViewItemBase instead of walking the tree.

**Review by StephenLPeters — APPROVED** [review]
:shipit:
