### PR TITLE
Clear DataContext of cleared elements in ItemsRepeater

### LINKED ISSUE #2384: Error in KernelBase.dll when using nested ItemsRepeater
**Describe the bug**

When scrolling nested repeaters, scrolling them for a certain amount will result in the following error:

```
Exception thrown at 0x00007FF84D16361C in ItemsRepeaterExperiments.exe: 
Microsoft C++ exception: winrt::hresult_error at memory location 0x000000CF37E7A960.
```

**Steps to reproduce the bug**

1. Open the project in #2284
2. Visit the second tab ("Nested selection demo"
3. Scroll down using mousewheel or clicking on the inside and pressing page down key

**Expected behavior**

Not to crash

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

When we set the `DataContext`, we save that fact in the `VirtualizationInformation` for that element, when that element gets cleared, we look up in the `VirtualizationInformation` whether we should need to clear the `DataContext` too, and do that if necessary.

## Motivation and Context

Fixes #2384 
## How Has This Been Tested?

Manually through debugging, added new API test.

### CODE REVIEW

File: dev/Repeater/VirtualizationInfo.h [hunk 1]
```diff
@@ -48,6 +48,9 @@ class VirtualizationInfo : public winrt::implements<VirtualizationInfo, winrt::I
     winrt::IInspectable Data() const { return m_data.get(); }
     winrt::IDataTemplateComponent DataTemplateComponent() const { return m_dataTemplateComponent.get(); }
 
+    bool MustClearDataContext() { return m_mustClearDataContext; }
```
Comment (ranjeshj) [inline dev/Repeater/VirtualizationInfo.h:51]: const to keep it consistent with the other methods in this class.

File: dev/Repeater/ViewManager.cpp [hunk 2]
```diff
@@ -731,6 +752,7 @@ winrt::UIElement ViewManager::GetElementFromElementFactory(int index)
             }();
 
             elementAsFE.DataContext(elementDataContext);
+            virtInfo->MustClearDataContext(true);
```
Comment (ranjeshj) [inline dev/Repeater/ViewManager.cpp:755]: Please add a test. Thanks!

File: dev/Repeater/VirtualizationInfo.h (hunk 1 above)
Comment (chingucoding) [reply dev/Repeater/VirtualizationInfo.h]: Fixed

File: dev/Repeater/ViewManager.cpp (hunk 2 above)
Comment (chingucoding) [reply dev/Repeater/ViewManager.cpp:755]: Yes of course, just wasn't sure how until your latest comment on #2384 .

Comment (chingucoding) [reply dev/Repeater/ViewManager.cpp:755]: Added a test now, unfortunately it has quite a large setup to inject the correct elements and allow the recycling to take place.

File: dev/Repeater/APITests/Common/Mocks/MockRecyclingTestFactory.cs [hunk 3]
```diff
@@ -0,0 +1,29 @@
+﻿using Microsoft.UI.Xaml.Controls;
+using System;
+using System.Collections.Generic;
+using System.Text;
+
+namespace Windows.UI.Xaml.Tests.MUXControls.ApiTests.RepeaterTests.Common.Mocks
+{
+    public class MockRecyclingTestFactory : RecyclingElementFactory
```
Comment (ranjeshj) [inline dev/Repeater/APITests/Common/Mocks/MockRecyclingTestFactory.cs:8]: you can avoid adding this and use MockElementFactory instead.

File: dev/Repeater/APITests/Common/Mocks/MockRecyclingTestFactory.cs [hunk 4]
```diff
@@ -0,0 +1,29 @@
...
+    {
+
+        public List<object> DataContextsInGetElement = new List<object>();
```
Comment (ranjeshj) [inline dev/Repeater/APITests/Common/Mocks/MockRecyclingTestFactory.cs:11]: you can use MockElementFactory instead of creating this new type.

File: dev/Repeater/APITests/ViewManagerTests.cs [hunk 5]
```diff
@@ -759,6 +759,76 @@ public void ValidateFocusMoveOnElementClearedWithUniqueIds()
...
+            int elementClearingRaisedCount = 0;
+            ItemsRepeaterScrollHost scroller = null;
+            Log.Comment("Initialize ItemsRepeater");
+            RunOnUIThread.Execute(() =>
+            {
+                elementFactory = new MockRecyclingTestFactory();
+                elementFactory.RecyclePool = new RecyclePool();
+                elementFactory.Templates["Item"] = (DataTemplate)XamlReader.Load(
+                    @"<DataTemplate xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation'> " + "<Button Content=\"{Binding}\" />" + @"</DataTemplate>");
+
```
Comment (ranjeshj) [inline dev/Repeater/APITests/ViewManagerTests.cs:784]: elementFactory: new MockElementFactory()
                   {
                       GetElementFunc = delegate (int index, UIElement owner)
                       {
                           return XamlReader.Load(...) 
                       },

                       ClearElementFunc = delegate (UIElement element, UIElement owner)
                       {
                           Verify.IsNull(element.DataContext);
                       }
                   },

File: dev/Repeater/APITests/ViewManagerTests.cs [hunk 6]
```diff
@@ -759,6 +759,76 @@ public void ValidateFocusMoveOnElementClearedWithUniqueIds()
...
+                repeater = CreateRepeater(Enumerable.Range(0, 100),
+                    elementFactory);
+
+                repeater.Layout = new StackLayout();
```
Comment (ranjeshj) [inline dev/Repeater/APITests/ViewManagerTests.cs:788]: This is the default, so don't need this line.

File: dev/Repeater/APITests/ViewManagerTests.cs [hunk 7]
```diff
@@ -759,6 +759,76 @@ public void ValidateFocusMoveOnElementClearedWithUniqueIds()
...
+
+            IdleSynchronizer.Wait();
+
+            Log.Comment("Scrolling ItemsRepeater around to clear and recycle elements");
+            RunOnUIThread.Execute(() =>
+            {
+                scroller.ScrollViewer.ChangeView(null, 400, null, true);
+                scroller.ScrollViewer.ChangeView(null, 600, null, true);
+                scroller.ScrollViewer.ChangeView(null, 800, null, true);
+            });
```
Comment (ranjeshj) [inline dev/Repeater/APITests/ViewManagerTests.cs:811]: Set ItemsSource to null, that will clear all the elements synchronously, so you don't need the Wait statements. You can also write this entire test within the same RunOnUIThread.Execute block if you do that.

File: dev/Repeater/APITests/ViewManagerTests.cs (hunk 6 above)
Comment (chingucoding) [reply dev/Repeater/APITests/ViewManagerTests.cs:788]: Not if we use CreateRepeater which uses the MockVirtualizingLayout down the line.

File: dev/Repeater/APITests/ViewManagerTests.cs [hunk 8]
```diff
@@ -759,6 +759,76 @@ public void ValidateFocusMoveOnElementClearedWithUniqueIds()
...
+
+            Log.Comment("Verify ItemsRepeater cleared data contexts correctly");
+            Verify.IsTrue(elementClearingRaisedCount > 0, "ItemsRepeater should have cleared some elements");
+            foreach (object o in elementFactory.DataContextsInGetElement)
+            {
+                // TL;DR; on why we check this:
+                // All DataContexts that are present on our returned ItemTemplate(Shim) get logged inside DataContextsInGetElement.
+                // If one of them is not null, that means the DataContext did not get cleared correctly which is a bug.
+                Verify.IsNull(o, "Datacontext should be null on a recycled ItemTemplate");
+            }
```
Comment (ranjeshj) [inline dev/Repeater/APITests/ViewManagerTests.cs:823]: Don't need these if we add this verification in MockElementFactory.ClearElementFunc delegate above.

File: dev/Repeater/APITests/ViewManagerTests.cs [hunk 9]
```diff
@@ -759,6 +759,76 @@ public void ValidateFocusMoveOnElementClearedWithUniqueIds()
...
+
+            void Repeater_ElementClearing(ItemsRepeater sender, Microsoft.UI.Xaml.Controls.ItemsRepeaterElementClearingEventArgs args)
+            {
+                elementClearingRaisedCount++;
+            }
```
Comment (ranjeshj) [inline dev/Repeater/APITests/ViewManagerTests.cs:828]: can do this increment in ClearElementFunc also to verify that it got called atleast once.

File: dev/Repeater/APITests/ViewManagerTests.cs (hunk 6 above)
Comment (ranjeshj) [reply dev/Repeater/APITests/ViewManagerTests.cs:788]: Good point :) This is okay then. Any layout should be fine as long as atleast one element is realized by the layout.

File: dev/Repeater/APITests/ViewManagerTests.cs (hunk 8 above)
Comment (chingucoding) [reply dev/Repeater/APITests/ViewManagerTests.cs:823]: ClearElement gets called before we are clearing the DataContext of the element, that's why we can't verify it in ClearElement. 

Or should the order of operations change, i.e:
1. Raise ElementClearing
2. Clear DataContext
3. Ask ElementFactory to clear element

File: dev/Repeater/APITests/ViewManagerTests.cs (hunk 5 above)
Comment (chingucoding) [reply dev/Repeater/APITests/ViewManagerTests.cs:784]: Wouldn't that just recreate the data templates everytime we need a new one? In that case, clearing the DataContext won't make a difference since we are not reusing the template.

File: dev/Repeater/APITests/ViewManagerTests.cs (hunk 8 above)
Comment (chingucoding) [reply dev/Repeater/APITests/ViewManagerTests.cs:823]: If we change the order to the above, testing will look quite differently, however with the current order of events:
1. Raise ElementClearing
2. Ask ElementFactory to clear element (DataContext is still known)
3. Clear DataContext
[...]
4. Recycle Template <- If DataContext is still set here, that's a problem

We need to check if a recycled elements DataContext is null before we pass it to the ItemsRepeater.

Comment (ranjeshj) [reply dev/Repeater/APITests/ViewManagerTests.cs:823]: I mean MockElementFactory.ClearElementFunc delegate method, not ItemsRepeater.ClearElement event handler. When the MockElementFactory gets the element after being recycled it should be null. ClearElementFunc happens after (4) in your list.

Comment (chingucoding) [reply dev/Repeater/APITests/ViewManagerTests.cs:823]: MockElementFactory.ClearElementFunc gets called in `RecycleElementCore` which still happens before we are clearing the DataContext. `RecycleElementCore` gets called by the [this line](https://github.com/chingucoding/microsoft-ui-xaml/blob/0664f291ad0cc0bd4e4bc67aea8f9302c0b04a59/dev/Repeater/ViewManager.cpp#L125) while we are clearing the DataContext in [in this line](https://github.com/chingucoding/microsoft-ui-xaml/blob/0664f291ad0cc0bd4e4bc67aea8f9302c0b04a59/dev/Repeater/ViewManager.cpp#L152).

Comment (ranjeshj) [reply dev/Repeater/APITests/ViewManagerTests.cs:823]: I see. I think we can set DataContext before it goes back to the factory by moving 
```
auto virtInfo = ItemsRepeater::GetVirtualizationInfo(element);
    virtInfo->MoveOwnershipToElementFactory();

    // During creation of this object, we were the one setting the DataContext, so clear it now.
    if (virtInfo->MustClearDataContext())
    {
        if (const auto elementAsFE = element.try_as<winrt::FrameworkElement>())
        {
            elementAsFE.DataContext(nullptr);
        }
    }
```
to [this line.](https://github.com/chingucoding/microsoft-ui-xaml/blob/0664f291ad0cc0bd4e4bc67aea8f9302c0b04a59/dev/Repeater/ViewManager.cpp#L112)

Comment (chingucoding) [reply dev/Repeater/APITests/ViewManagerTests.cs]: I've updated the order now and cleaned up the test as you suggested.

File: dev/Repeater/APITests/ViewManagerTests.cs (hunk 9 above)
Comment (chingucoding) [reply dev/Repeater/APITests/ViewManagerTests.cs]: Done.

**Comment by StephenLPeters** [comment]
@ranjeshj I don't think I have a perfect understanding of the change so I'm going to wait for your sign off to merge this.
