### PR TITLE
Reduce default NumberBox precision to 6 digits

### LINKED ISSUE #3959: NumberBox has a precision floating point bug
**Describe the bug**

**Steps to reproduce the bug**

Use the following code:
`<muxc:NumberBox 
    Margin="0, 10, 0, 0"
    Header="Search weight:"
    Value="1"
    SpinButtonPlacementMode="Compact"
    SmallChange=".01"
    LargeChange=".1"
    Minimum="0"
    Maximum="5"
    />`

Then do a small or large change,

**Expected behavior**

Get proper precision, to small / large snap.  Seems like a floating point precision error

**Screenshots**

image

**Version Info**
UWP 6.2.10

NuGet package version: 
Microsoft.UI.Xaml 2.5.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

### PR DESCRIPTION
**Pull request by lhecker**
## Description
printf() defaults to 6 digits. 6 digits are sufficient for most
users under most circumstances, while simultaneously avoiding most
rounding errors for instance during double/float conversion.

Closes #3959

## Motivation and Context
`FLT_DECIMAL_DIG` is 9. With 12 significantly exceeding this,
WinUI is incapable of presenting 32-bit floats. C defaults
to 6 digits for string conversions for this exact reason.

## How Has This Been Tested?
Windows Terminal overrides its NumberBoxes the same way this PR does it.

## Screenshots (if appropriate):
Before:
YraMDjf6wkUTvhKu

After:
bhvRxhZxbeefgMrL

### CODE REVIEW

File: dev/NumberBox/NumberBox.h [hunk 1]
```diff
@@ -98,7 +98,7 @@ class NumberBox :
     bool m_valueUpdating{ false };
     bool m_textUpdating{ false };
 
-    winrt::SignificantDigitsNumberRounder m_displayRounder{};
+    winrt::IncrementNumberRounder m_displayRounder{};
```
Comment (lhecker) [inline dev/NumberBox/NumberBox.h:101]: I initially didn't consider how this would work with >1 integer digit. Switching to a `IncrementNumberRounder` ensures that it always formats it with 6 fractional digits no matter how many integer digits it has.

**Comment by gabbybilka** [comment]
The team will only be taking critical changes into WinUI 2.8 as our current focus is to assist our users in moving from WinUI 2 to WinUI 3. This change did not meet the bar for a WinUI 2.8 servicing release, but is approved to merge into the WinUI 2 main branch for a WinUI 2.9. That being said, at this time, we have no plans for a WinUI 2.9 as we focus on advancing WinUI 3. We will also port this change to WinUI 3 and it will be present for applications that have migrated to WinUI 3 in an upcoming WinAppSDK release. 

Thank you for your contribution!

cc: @bpulliam

**Review by bpulliam — APPROVED** [review]
