### PR TITLE
ProgressBar Indeterminate Animation Update

### LINKED ISSUE #1704: ProgressBar incorrectly runs transition animation when switching between paused and error states
**Describe the bug**
Switching the new indeterminate ProgressBar from `IsError=True` to `ShowPaused=True` causes the thumb(?) to briefly appear and disappear.

**Steps to reproduce the bug**

1. Open Xaml Controls Gallery using new progress UI
2. Toggle between Paused and Error states

**Expected behavior**
Since ProgressBar isn't visible in either Paused or Error state, it probably shouldn't be visible during the transition either.

**Screenshots**
progressbarbug

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.3.191129002 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

### LINKED ISSUE #1745: Indeterminate ProgressBar motion doesn't match design spec
**Describe the bug**

#1169 is done, but the indeterminate animation needs to be tweaked to better match motion comps. Let's leverage @tashatitova's work if possible.

### PR DESCRIPTION
**Pull request by karenbtlai**
## Description
ProgressBar indeterminate animation according to [specifications](https://codepen.io/anon/pen/aQeVOm)

## Motivation and Context

Fixes #1745 
Refactoring also fixes #1704 

## How Has This Been Tested?

- Existing Interaction Tests
- Existing Interaction Tests in VMs RS4 and below for resource down leveling issue

## Screenshots (if appropriate):

**Indeterminate**
ezgif com-video-to-gif (1)

**Indeterminate Error**
ezgif com-video-to-gif (1)

**Indeterminate Paused**
ezgif com-video-to-gif

### CODE REVIEW

File: dev/ProgressBar/ProgressBar.cpp [hunk 1]
```diff
@@ -121,7 +123,16 @@ void ProgressBar::SetProgressBarIndicatorWidth()
 
             if (IsIndeterminate())
             {
-                progressBarIndicator.Width(progressBarWidth * 0.4);
+                determinateProgressBarIndicator.Width(0);
+
+                if (auto&& indeterminateProgressBarIndicator = m_indeterminateProgressBarIndicator.get())
+                {
+                    if (auto&& indeterminateProgressBarIndicator2 = m_indeterminateProgressBarIndicator2.get())
```
Comment (StephenLPeters) [inline dev/ProgressBar/ProgressBar.cpp]: Setting indeterminateProgressBarIndicator's width shouldn't be dependent on the presense of an indeterminateProgressBarIndicator2

File: dev/ProgressBar/ProgressBar.cpp [hunk 2]
```diff
@@ -121,7 +123,16 @@ void ProgressBar::SetProgressBarIndicatorWidth()
 
             if (IsIndeterminate())
             {
-                progressBarIndicator.Width(progressBarWidth * 0.4);
+                determinateProgressBarIndicator.Width(0);
```
Comment (StephenLPeters) [inline dev/ProgressBar/ProgressBar.cpp]: >determinateProgressBarIndicator.Width(0); [](start = 16, length = 41)

Is this needed? we set it's opacity to 0 in the VSM right?

File: dev/ProgressBar/ProgressBar.xaml [hunk 3]
```diff
@@ -107,19 +113,45 @@
...
-                                    contract7Present:RadiusX="{Binding CornerRadius, RelativeSource={RelativeSource TemplatedParent}, Converter={StaticResource TopLeftCornerRadiusDoubleValueConverter}}"
-                                    contract7Present:RadiusY="{Binding CornerRadius, RelativeSource={RelativeSource TemplatedParent}, Converter={StaticResource BottomRightCornerRadiusDoubleValueConverter}}"
-                                    contract7NotPresent:RadiusX="{Binding Source={ThemeResource ControlCornerRadius}, Converter={StaticResource TopLeftCornerRadiusDoubleValueConverter}}"
-                                    contract7NotPresent:RadiusY="{Binding Source={ThemeResource ControlCornerRadius}, Converter={StaticResource BottomRightCornerRadiusDoubleValueConverter}}"
-    >
-                                    <Rectangle.RenderTransform>
-                                        <CompositeTransform/>
-                                    </Rectangle.RenderTransform>
-                                </Rectangle>
+                                <StackPanel Orientation="Horizontal">
```
Comment (StephenLPeters) [inline dev/ProgressBar/ProgressBar.xaml]: >StackPanel [](start = 33, length = 10)

I think you should use a grid instead, that way you wont need to add render transforms to get the children to overlap.

File: dev/ProgressBar/ProgressBar.cpp (hunk 1 above)
Comment (karenbtlai) [reply dev/ProgressBar/ProgressBar.cpp]: @StephenLPeters There are two indicators, `indeterminateProgressBarIndicator` and `indeterminateProgressBarIndicator2`, running simultaneously for indeterminate mode as per design specifications

File: dev/ProgressBar/ProgressBar.cpp (hunk 2 above)
Comment (karenbtlai) [reply dev/ProgressBar/ProgressBar.cpp]: @StephenLPeters It seemed to still be visible during the first frame of each animation if the width is non-zero. Furthermore, this allows a smoother animation as it switches from indeterminate mode back to determinate.

Comment (karenbtlai) [reply dev/ProgressBar/ProgressBar.cpp]: @StephenLPeters the indicator seems to appear for a split second at the beginning of each animation. This also allows a smoother animation switching from indeterminate back to determinate.

File: dev/ProgressBar/ProgressBar.xaml (hunk 3 above)
Comment (karenbtlai) [reply dev/ProgressBar/ProgressBar.xaml]: @StephenLPeters The `RenderTransforms` are for the indeterminate animation where `Storyboard.TargetProperty="(UIElement.RenderTransform).(CompositeTransform.TranslateX)"`

File: dev/ProgressBar/ProgressBar.cpp [hunk 4]
```diff
@@ -159,10 +170,11 @@ void ProgressBar::UpdateWidthBasedTemplateSettings()
             return std::make_tuple(0.0f, 0.0f);
         }();
 
-        const double indicatorWidthMultiplier = -0.4;
+        templateSettings->ContainerAnimationStartPosition(width * -0.4);
```
Comment (tashatitova) [inline dev/ProgressBar/ProgressBar.cpp]: -1.0 per spec

File: dev/ProgressBar/ProgressBar.cpp [hunk 5]
```diff
@@ -159,10 +170,11 @@ void ProgressBar::UpdateWidthBasedTemplateSettings()
...
+        templateSettings->ContainerAnimationEndPosition(width * 1.2);
 
-        templateSettings->ContainerAnimationStartPosition(width * indicatorWidthMultiplier);
-        templateSettings->ContainerAnimationEndPosition(width);
+        templateSettings->ContainerAnimationStartPosition2(width * -1);
```
Comment (tashatitova) [inline dev/ProgressBar/ProgressBar.cpp]: -1.5 per spec

File: dev/ProgressBar/ProgressBar.xaml [hunk 6]
```diff
@@ -47,50 +55,48 @@
...
-                                                </EasingDoubleKeyFrame.EasingFunction>
-                                            </EasingDoubleKeyFrame>
-                                            <EasingDoubleKeyFrame KeyTime="0:0:1" Value="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=TemplateSettings.ContainerAnimationEndPosition}">
-                                                <EasingDoubleKeyFrame.EasingFunction>
-                                                    <CubicEase/>
-                                                </EasingDoubleKeyFrame.EasingFunction>
-                                            </EasingDoubleKeyFrame>
+                                            Storyboard.TargetName="IndeterminateProgressBarIndicator"
+                                            Storyboard.TargetProperty="(UIElement.RenderTransform).(CompositeTransform.TranslateX)">
+                                            <SplineDoubleKeyFrame KeyTime="0" Value="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=TemplateSettings.ContainerAnimationStartPosition}" KeySpline="0.4, 0.0, 0.6, 1.0" />
```
Comment (tashatitova) [inline dev/ProgressBar/ProgressBar.xaml]: <DoubleAnimationUsingKeyFrames Storyboard.TargetProperty="(UIElement.RenderTransform).(TranslateTransform.X)" Storyboard.TargetName="ProgressBarIndeterminateIndicator">
                                                
                                                <DiscreteDoubleKeyFrame KeyTime="0" Value="-400" />
                                                
                                                <SplineDoubleKeyFrame KeyTime="0:0:1.5" Value="1200" />
                                                
                                                <DiscreteDoubleKeyFrame KeyTime="0:0:2.0" Value="1200"/>
                                            </DoubleAnimationUsingKeyFrames>
                                            <DoubleAnimationUsingKeyFrames Storyboard.TargetProperty="Opacity" Storyboard.TargetName="ProgressBarIndeterminateIndicator">
                                                <DiscreteDoubleKeyFrame KeyTime="0" Value="1" />
                                                <DiscreteDoubleKeyFrame KeyTime="0:0:1.5" Value="1" />
                                                <DiscreteDoubleKeyFrame KeyTime="0:0:1.501" Value="0" />
                                                <DiscreteDoubleKeyFrame KeyTime="0:0:2.0" Value="0" />
                                            </DoubleAnimationUsingKeyFrames>

File: dev/ProgressBar/ProgressBar.xaml [hunk 7]
```diff
@@ -47,50 +55,48 @@
...
+                                            <SplineDoubleKeyFrame KeyTime="0:0:1.5" Value="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=TemplateSettings.ContainerAnimationEndPosition}" KeySpline="0.4, 0.0, 0.6, 1.0" />
+                                            <SplineDoubleKeyFrame KeyTime="0:0:2" Value="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=TemplateSettings.ContainerAnimationEndPosition}" KeySpline="0.4, 0.0, 0.6, 1.0" />
                                         </DoubleAnimationUsingKeyFrames>
+                                        <DoubleAnimationUsingKeyFrames
+                                            Storyboard.TargetName="IndeterminateProgressBarIndicator2"
```
Comment (tashatitova) [inline dev/ProgressBar/ProgressBar.xaml]: <DoubleAnimationUsingKeyFrames Storyboard.TargetProperty="(UIElement.RenderTransform).(TranslateTransform.X)" Storyboard.TargetName="ProgressBarIndeterminateIndicator2">
                                                
                                                <DiscreteDoubleKeyFrame KeyTime="0" Value="-600" />
                                                
                                                <DiscreteDoubleKeyFrame KeyTime="0:0:0.2" Value="-400"/>
                                                
                                                <SplineDoubleKeyFrame KeyTime="0:0:2.0" Value="800" KeySpline="0.4,0,0.6,1" />
                                            </DoubleAnimationUsingKeyFrames>
                                            <DoubleAnimationUsingKeyFrames Storyboard.TargetProperty="Opacity" Storyboard.TargetName="ProgressBarIndeterminateIndicator2">
                                                <DiscreteDoubleKeyFrame KeyTime="0" Value="0" />
                                                <DiscreteDoubleKeyFrame KeyTime="0:0:0.49" Value="0" />
                                                <DiscreteDoubleKeyFrame KeyTime="0:0:0.5" Value="1" />
                                                <DiscreteDoubleKeyFrame KeyTime="0:0:2.0" Value="1" />

File: dev/ProgressBar/ProgressBar.cpp (hunk 4 above)
Comment (tashatitova) [reply dev/ProgressBar/ProgressBar.cpp]: also need mid value and end value for both indicators as they are different

Comment (karenbtlai) [reply dev/ProgressBar/ProgressBar.cpp]: I followed the specs exactly as outlined in this [codepen](https://codepen.io/anon/pen/aQeVOm). The translation value for `"bar-infinite-a"` is `-100%`, where the percentage signifies percentage width of the indicator, not the progress bar. As the indicator is spec'd at 40% width of the progress bar, the -0.4 is the correct multiplier.

File: dev/ProgressBar/ProgressBar.cpp (hunk 5 above)
Comment (karenbtlai) [reply dev/ProgressBar/ProgressBar.cpp]: See comment above

File: dev/ProgressBar/ProgressBar.xaml (hunk 6 above)
Comment (karenbtlai) [reply dev/ProgressBar/ProgressBar.xaml]: See comment above

File: dev/ProgressBar/ProgressBar.xaml (hunk 7 above)
Comment (karenbtlai) [reply dev/ProgressBar/ProgressBar.xaml]: See comment above.

Also, specs (linked in comment above) specified -150% as start position, and 166.6% for end position.

File: dev/Common/Common_themeresources.xaml [hunk 8]
```diff
@@ -13,13 +13,15 @@
             <Thickness x:Key="TextControlBorderThemeThickness">1</Thickness>
             <Thickness x:Key="TextControlBorderThemeThicknessFocused">2</Thickness>
             <Thickness x:Key="TextControlThemePadding">10,6,6,5</Thickness>
+            <Color x:Key="SystemErrorTextColor">#FFF000</Color>
```
Comment (StephenLPeters) [inline dev/Common/Common_themeresources.xaml]: ><Color x:Key="SystemErrorTextColor">#FFF000</Color> [](start = 12, length = 51)

I don't think that this is correct, I think it means we will no longer reference the generic.xaml resource and will instead get this copy, which for now is the same value but these could diverge in the future.  @kmahone @ranjeshj I'm not sure what the right pattern here is, something with conditional xaml? Do we need an RS5+ version of this file since the resource was added to generic.xaml in rs5?

Comment (mdtauk) [reply dev/Common/Common_themeresources.xaml]: Using the System Error Text Color will result in a Red colour for Light theme, and Yellow colour for Dark theme.

The Icon badges use Red, Yellow, and Green consistently across themes - and these colours are likely to be used for the In App Status banners being considered #913

Comment (karenbtlai) [reply dev/Common/Common_themeresources.xaml]: @mdtauk Thank you for your insight! The colours used for this update was chosen and approved by the designer who handed me the specs. These colours are already set in the Resource Theme Dictionaries for RS5+, but I added them in Common Themeresources as there were downleveling issues for RS4 and below.

Comment (StephenLPeters) [reply dev/Common/Common_themeresources.xaml]: I still think this is wrong, while this custom color you've added to common_themeresources matches the generic one now, it might not in the future. I think we need to find a way to use this in rs4 and below and use generic.xaml in rs5+

Comment (karenbtlai) [reply dev/Common/Common_themeresources.xaml]: > I still think this is wrong, while this custom color you've added to common_themeresources matches the generic one now, it might not in the future. I think we need to find a way to use this in rs4 and below and use generic.xaml in rs5+. @ranjeshj thoughts?

@kmahone

Comment (ranjeshj) [reply dev/Common/Common_themeresources.xaml]: hardcoding colors here seem incorrect. I assume we do not have any existing keys that match this color? do we need to add a new key or update an existing one ?

---
In reply to: [366998130](https://github.com/microsoft/microsoft-ui-xaml/pull/1759#discussion_r366998130) [](ancestors = 366998130)

File: dev/CommonStyles/ProgressBar_themeresources.xaml [hunk 9]
```diff
@@ -9,6 +9,7 @@
             <x:Double x:Key="ProgressBarIndicatorPauseOpacity">0.6</x:Double>
             <x:Double x:Key="ProgressBarThemeMinHeight">4</x:Double>
             <Thickness x:Key="ProgressBarBorderThemeThickness">0</Thickness>
+            <Color x:Key="SystemControlErrorBackgroundBrush">#33FFFFFF</Color>
```
Comment (ranjeshj) [inline dev/CommonStyles/ProgressBar_themeresources.xaml]: This is a color, but named as brush..
