### PR TITLE
ProgressRing State Transitions Inconsistency Fix

### LINKED ISSUE #2089: Progress Ring state transition inconsistency
**Describe the bug**
Currently when you press the "IsIndeterminate" checkbox in the ProgressRing test page - there is a subtle fade transition from the Determinate state to the animation playing.

But there is none when moving from the Indeterminate state back to a Determinate state.

**Steps to reproduce the bug**
Switch between Determinate and Indeterminate states

**Expected behavior**
The fade transition should work transitioning both ways between states

### PR DESCRIPTION
**Pull request by karenbtlai**
## Description

Adds a fade transition for ProgressRing from `Indeterminate` to `Determinate`.

Turns out `player.stop()` is causing the abrupt jump in animation. Thus,  the OpacityDependency property for LottiePlayer is registered so `player.Stop(`) only runs after the transition animation is complete (ie. is equal to 0)

## Motivation and Context

Fixes #2089 

## How Has This Been Tested?

Manually checking the animation fade transition

### CODE REVIEW

File: dev/ProgressRing/ProgressRing.cpp [hunk 1]
```diff
@@ -116,6 +125,17 @@ void ProgressRing::OnBackgroundColorPropertyChanged(const winrt::DependencyObjec
     }
 }
 
+void ProgressRing::OnOpacityPropertyChanged(const winrt::DependencyObject&, const winrt::DependencyProperty&)
+{
+    if (auto&& player = m_player.get())
```
Comment (ranjeshj) [inline dev/ProgressRing/ProgressRing.cpp]: @simeoncran Would it make sense to add this behavior to AnimatedVisualPlayer?
