### PR TITLE
PipsPager scrolling fix event bubble up

### LINKED ISSUE #4246: PipsPager: sometimes internal scrollviewer makes external scrollviewers scroll
**Describe the bug**

Sometimes when moving from one pip to another (by clicking on it directly or using the navigation arrows), external scroll viewers on the page will scroll as well.
**Steps to reproduce the bug**

1. Create a Vertical Pips Pager inside a scroll viewer.
2. Choose the last Pip.
3. Observe the outside scroll viewer scrolling as well.

**Expected behavior**

External scroll viewers shouldn't scroll. It happens because the inner scroll was not "complete" and the bring into view event is bubbled up causing the external scroll viewers to scroll as well. The way to fix it is to handle the bringintoview event on the internal scroll viewer.
**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6 prerelease]

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

### PR DESCRIPTION
**Pull request by beervoley**
## Description

PipsPager inner ScrollViewer causes outer ScrollViewers scroll if the inner ScrollViewer cannot fully fulfill the scroll request. It happens when offsets are bigger than what ScrollViewer can actually scroll by.
## Motivation and Context

This PR closes #4246. It handles the `BringIntoViewRequested` event and stops its bubbling up.
## How Has This Been Tested?

Manually.

### CODE REVIEW

**Comment by beervoley** [comment]
@gabbybilka FYI

File: dev/PipsPager/PipsPager.cpp [hunk 1]
```diff
@@ -627,6 +635,11 @@ void PipsPager::OnPipsAreaBringIntoViewRequested(const IInspectable& sender, con
     }
 }
 
+void PipsPager::OnScrollViewerBringIntoViewRequested(const IInspectable& sender, const winrt::BringIntoViewRequestedEventArgs& args)
+{
+    args.Handled(true);
```
Comment (RBrid) [inline dev/PipsPager/PipsPager.cpp:640]: I think both PipsPager::OnPipsAreaBringIntoViewRequested and PipsPager::OnScrollViewerBringIntoViewRequested could use some detailed comments.

File: dev/PipsPager/PipsPager.cpp [hunk 2]
```diff
@@ -103,7 +103,15 @@ void PipsPager::OnApplyTemplate()
         }
     }(GetTemplateChildT<winrt::ItemsRepeater>(c_pipsPagerRepeaterName, *this));
 
-    m_pipsPagerScrollViewer.set(GetTemplateChildT<winrt::FxScrollViewer>(c_pipsPagerScrollViewerName, *this));
+    m_scrollViewerBringIntoViewRequestedRevoker.revoke();
+    [this](winrt::FxScrollViewer scrollViewer)
```
Comment (RBrid) [inline dev/PipsPager/PipsPager.cpp:107]: The ItemsRepeater uses 'const' just above.  Can we be const-istent :-)

**Review by RBrid — CHANGES_REQUESTED** [review]

**Review by RBrid — APPROVED** [review]
