### PR TITLE
Fix for numberbox corner radius issues

### LINKED ISSUE #2223: NumberBox doesn't respect ControlCornerRadius theme resource override or CornerRadius property
**Describe the bug**
The NumberBox control currently ignores the *Control.CornerRadius* property and also ignores the *ControlCornerRadius* theme resource in SpinButtonPlacementMode.Inline.

Please see the following XAML (abbreviated to focus on the relevant code):
```xml
<Page
    x:Class="UwpTestApp.MainPage"
    <!-- -->
    <Page.Resources>
        <CornerRadius x:Key="ControlCornerRadius">0</CornerRadius>
        <CornerRadius x:Key="OverlayCornerRadius">0</CornerRadius>
    </Page.Resources>

    <StackPanel Name="RootGrid" HorizontalAlignment="Center" VerticalAlignment="Center">
        <TextBox PlaceholderText="Some text..." />
        <muxc:NumberBox Margin="0,10,0,0" PlaceholderText="Some value..." 
                        SpinButtonPlacementMode="Inline"
                        CornerRadius="0"/>
    </StackPanel>
</Page>
```

Tihis gives us the following result:
image
(Note how the NumberBox still has a corner radius value of '2', ignoring the property and theme resource override.)

**Expected behavior**
NumberBox shoud respect both the Control.CornerRadius property and the ControlCornerRadius theme resource.

**Version Info**

NuGet package version: 
2.4.0-prerelease.200322001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
I would like to fix this.

### PR DESCRIPTION
**Pull request by Felix-Dev**
## Description
This PR 
* fixes two NumberBox corner radius issues: Control.CornerRadius property is now respected, just as the *ControlCornerRadius* theme resource in NumberBox.SpinButtonPlacementMode.Inline
* adds NumberBox examples to the CornerRadius test page of the MUXControlsTestApp
* adds an API test to verify the correct corner radius use for NumberBox

## Motivation and Context
Fixes #2223 

## How Has This Been Tested?
Tested visually.

## Gif:
numberbox_cornerradius_issue_fix

### CODE REVIEW

File: dev/NumberBox/NumberBox.cpp [hunk 1]
```diff
@@ -158,6 +160,20 @@ void NumberBox::OnApplyTemplate()
...
             m_textBoxKeyUpRevoker = textBox.KeyUp(winrt::auto_revoke, { this, &NumberBox::OnNumberBoxKeyUp });
+
+            // Listen to NumberBox::CornerRadius changes so we can change the corner radius of the textbox in code-behind.
+            // Based on corner radius tests, we cannot do this in Visual States as we need to filter some specific corner radii
+            // for the texbox based on the SpinButtonPlacementMode. For example, with SpinButtonPlacementMode::Inline, the T-rule
+            // applies and we should only set the TopLeft and BottomLeft corner radii of the textbox to values > 0. In all other
+            // SpinButtonPlacementModes, we apply NumberBox's corner radius to all textbox corners. Visual States, however, only
+            // set the property when entering the state. Since NumberBox's corner radius can change while in a Visual State
+            // this could potentially lead to incorrect textbox corner radii updates (rounding all four corners with inlined spin buttons
+            // -> breaking T-rule)
```
Comment (StephenLPeters) [inline dev/NumberBox/NumberBox.cpp:171]: I'm not sure I understand the issue here, are you saying there is no way to set up a template binding within a VSM setter?

`contract7Present:CornerRadius="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=CornerRadius, Converter={StaticResource RightCornerRadiusFilterConverter}}"` doesn't this do it?

Comment (Felix-Dev) [reply dev/NumberBox/NumberBox.cpp:171]: @StephenLPeters The issue I was seeing (using the CornerRadius test page of the MUXControlsTestApp) was the following: Using template binding in the style (as you have written above), initially, the corner radius was filtered correctly for the textbox in SpinButtonPlacement.Inline mode. However, as soo as as I used the slider to change the *ControlCornerRadius* value used to validate this addition, the new value corner radius values were consistently applied to *all four* edges of NumberBox' TextBox. In other words, the filtering set in the VisualState *SpinButtonsVisible* was no longer being used, causing the T-rule to be broken. 

I then read the [VisualState.Setters](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.visualstate.setters) documentation and it is my current understanding that the filter set in the visual state is only applied on entering the state. If I assign new CornerRadius values *after* entering this state - which is what I was doing by moving the ControlCornerRadius slider - the value set by the visual state (the filter) would no longer apply.

As such, this lead me to essentially writing this lig in code-behind as you can see. If there is a way to get this working with Visual States alone, I'm all ears. It would certainly be a nicer solution 🙂

File: dev/NumberBox/NumberBox.cpp [hunk 2]
```diff
@@ -642,3 +668,19 @@ bool NumberBox::IsInBounds(double value)
...
+    if (m_isControlCornerRadiusAvailable)
+    {
+        if (auto && textBox = m_textBox.get())
+        {
+            auto value = this->CornerRadius();
+
+            // Respect T-rule in inline mode. Since a spin button borders the textbox to the right
+            // we are not allowed to round the right corners of the textbox.
+            value.BottomRight = value.TopRight = 0;
+            textBox.CornerRadius(value);
```
Comment (JohnnyWestlake) [inline dev/NumberBox/NumberBox.cpp:682]: Ideally we wouldn't want to do it quite like this as if someone retemplates the control to put the inline buttons on the left side (like I have 😅) leaving the TextBox on the right, we're breaking the corners again.

Comment (Felix-Dev) [reply dev/NumberBox/NumberBox.cpp:682]: Yes, I agree. I had this thought as well. If we can put this T-rule enforcement in the control template itself (via a Visual State setter for example) that would be best (as then this could easily be modified to suit the needs of the control redesign).

Comment (Felix-Dev) [reply dev/NumberBox/NumberBox.cpp:682]: @JohnnyWestlake Ok, instead of enforcing the T-rule in code-behind now, I moved that code back into the control template:
```xml
<VisualState x:Name="SpinButtonsVisible">
    <VisualState.Setters>
        <Setter Target="DownSpinButton.Visibility" Value="Visible" />
        <Setter Target="UpSpinButton.Visibility" Value="Visible" />
        <contract7Present:Setter Target="InputBox.CornerRadius" Value="{Binding RelativeSource={RelativeSource TemplatedParent}, Path=CornerRadius, Converter={StaticResource LeftCornerRadiusFilterConverter}}" />
    </VisualState.Setters>
</VisualState>
```

In code-behind, I replaced setting the borer with a call to the *SpinButtonsVisible* visual state *every* time the Numberbox' CornerRadius is changed and we are in the *inline* SpinButtonPlacement mode. If you retemplated your numberbox to have the buttons on the left side of the numberbox, all the corner radius changes you have to do are now solely in the control temlate again.

Comment (Felix-Dev) [reply dev/NumberBox/NumberBox.cpp:682]: And here's a gif with a quick retemplate:
numberbox_cornerradius_issue_retemplate

File: dev/NumberBox/NumberBox.cpp (hunk 1 above)
Comment (Felix-Dev) [reply dev/NumberBox/NumberBox.cpp:171]: @StephenLPeters I replaced T-rule enforcement with a GoToState(...,L"SpinButtonsAvailable",..) call so all the corner radius code is back in the control template again. Commit with these changes not yet uploaded.

**Comment by Felix-Dev** [comment]
What happened here? 😅

**Comment by kmahone** [comment]
We don't know. Looks like an issue with the bot.

File: dev/NumberBox/APITests/NumberBoxTests.cs [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+using WEX.Logging.Interop;
+#else
+using Microsoft.VisualStudio.TestTools.UnitTesting;
+using Microsoft.VisualStudio.TestTools.UnitTesting.Logging;
+#endif
+
+namespace Windows.UI.Xaml.Tests.MUXControls.ApiTests
+{
+    [TestClass]
+    public class NumberBoxTests : ApiTestBase
```
Comment (StephenLPeters) [inline dev/NumberBox/APITests/NumberBoxTests.cs:26]: >ApiTestBase [](start = 34, length = 11)

ApiTestBase gives you access to the Content Property and the Content.UpdateLayout() method. Using these will significantly reduce the complexity of this test. You can see examples in a lot (most?) of our api tests, specifically here is one: [https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Repeater/APITests/LayoutTests.cs](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Repeater/APITests/LayoutTests.cs)

Comment (StephenLPeters) [reply dev/NumberBox/APITests/NumberBoxTests.cs:26]: Using this IdleSynchronizer.Wait() and exiting the UIThread shouldn't be needed

---
In reply to: [405702960](https://github.com/microsoft/microsoft-ui-xaml/pull/2224#discussion_r405702960) [](ancestors = 405702960)

File: dev/NumberBox/NumberBox.cpp (hunk 1 above)
Comment (StephenLPeters) [reply dev/NumberBox/NumberBox.cpp]: @ranjeshj is there someone with better VSM/Binding knowledge than me that could weigh in here? I don't understand why the binding is behaving as Felix-Dev is describing. Its almost as if the TemplateBinding for that property is still active...  @Felix-Dev could you maybe try this...

Comment (Felix-Dev) [reply dev/NumberBox/NumberBox.cpp]: @StephenLPeters It can take a little while longer until I can report back...issue #2221 is really driving me crazy here. I'm wasting soooo much time re-building the entire project that I need a break currently (will have to switch over to the InnerLoop for future PRs).

Comment (StephenLPeters) [reply dev/NumberBox/NumberBox.cpp]: That does sound frustrating :/... Thanks for the awesome work despite that issue!

Comment (Felix-Dev) [reply dev/NumberBox/NumberBox.cpp]: @StephenLPeters Please correct me if I missunderstood your suggestion but here's what I did (only showing the relevant code).

I first created a named binding as a static resource in the template (root grid):
```xml
<Grid.Resources>
    <Binding x:Name="TextBoxCornerRadiusBinding" Path="CornerRadius" RelativeSource="{RelativeSource Mode=TemplatedParent}"/>
</Grid.Resources>
```

In the VSM's setter, I targeted the named binding's converter property:
```xml
<Setter Target="TextBoxCornerRadiusBinding.Converter" Value="{StaticResource LeftCornerRadiusFilterConverter}" />
```

Finally, I replaced the TextBox's template binding with:
```xml
CornerRadius="{StaticResource TextBoxCornerRadiusBinding}"
```

Running this code, I get an unhandled exceptio, with the error text: `Failed to assign to property 'Windows.UI.Xaml.Controls.Control.CornerRadius' because the type 'Windows.UI.Xaml.Data.RelativeSource' cannot be assigned to the type 'Windows.UI.Xaml.CornerRadius'.`

Comment (Felix-Dev) [reply dev/NumberBox/NumberBox.cpp]: I've also created a gif showing the issue we are trying to solve. I'm using template binding without the VisualStateManager.GoToState() call here:

numberbox_cr_issue

Note how initially the VSM's setter is working and the T-rule is respected (only the left corners of the textbox are rounded, not the corners adjacent to the spin buttons). However, as I change the corner radius, the updated values apply to all *four* corners of the textbox, breaking the T-rule. This is the reason why I introduced the VisualStateManager.GoToState(..., L"SpinButtonsAvailable", ...) call above.

Comment (StephenLPeters) [reply dev/NumberBox/NumberBox.cpp]: I see, maybe this isn't supported in xaml markup then...

File: dev/NumberBox/APITests/NumberBoxTests.cs (hunk 3 above)
Comment (StephenLPeters) [reply dev/NumberBox/APITests/NumberBoxTests.cs:26]: @Felix-Dev this is the last comment I have, then I'll sign off :)

Comment (Felix-Dev) [reply dev/NumberBox/APITests/NumberBoxTests.cs:26]: @StephenLPeters There seems to be a timing issue here using this approach in one specific test (code slightly abbreviated to only show relevant part):
```cs
[TestMethod]
public void VerifyNumberBoxCornerRadius2()
{
    var numberBox = SetupNumberBox2();

    RepeatButton spinButtonDown = null;
    TextBox textBox = null;
    RunOnUIThread.Execute(() =>
    {
        // first test: Uniform corner radius of '2' with no spin buttons shown
        numberBox.SpinButtonPlacementMode = NumberBoxSpinButtonPlacementMode.Hidden;
        numberBox.CornerRadius = new CornerRadius(2);

        Content.UpdateLayout();

        textBox = TestUtilities.FindDescendents<TextBox>(numberBox).Where(e => e.Name == "InputBox").Single();
        Verify.AreEqual(new CornerRadius(2, 2, 2, 2), textBox.CornerRadius);

        // second test: Uniform corner radius of '2' with spin buttons in inline mode (T-rule applies now)
        numberBox.SpinButtonPlacementMode = NumberBoxSpinButtonPlacementMode.Inline;

        Content.UpdateLayout();

        spinButtonDown = TestUtilities.FindDescendents<RepeatButton>(numberBox).Where(e => e.Name == "DownSpinButton").Single();

        Verify.AreEqual(new CornerRadius(2, 0, 0, 2), textBox.CornerRadius);
        Verify.AreEqual(new CornerRadius(0, 2, 2, 0), spinButtonDown.CornerRadius);

        // third test: Set uniform corner radius of '4' with spin buttons in inline mode
        // This check makes sure that updating the CornerRadius values of the numberbox in inline mode
        // does not break the T-rule.
        numberBox.CornerRadius = new CornerRadius(4);

        Content.UpdateLayout();

        // TEST FAIL HERE: actual corner radius is <4,4,4,4> so T-rule broken
        // Seems like the visual state we are entering when corner radius changes in Inline mode
        // is not applied yet
        Verify.AreEqual(new CornerRadius(4, 0, 0, 4), textBox.CornerRadius);
        Verify.AreEqual(new CornerRadius(0, 4, 4, 0), spinButtonDown.CornerRadius);
    });
}
```

See the comment for the final test above (setting CornerRadius to 4 in the third test).

The test passes as expected when I write it like this:
```cs
[TestMethod]
public void VerifyNumberBoxCornerRadius3()
{
    var numberBox = SetupNumberBox2();

    RepeatButton spinButtonDown = null;
    TextBox textBox = null;
    RunOnUIThread.Execute(() =>
    {
        // first test: Uniform corner radius of '2' with no spin buttons shown
        numberBox.SpinButtonPlacementMode = NumberBoxSpinButtonPlacementMode.Hidden;
        numberBox.CornerRadius = new CornerRadius(2);

        Content.UpdateLayout();

        textBox = TestUtilities.FindDescendents<TextBox>(numberBox).Where(e => e.Name == "InputBox").Single();
        Verify.AreEqual(new CornerRadius(2, 2, 2, 2), textBox.CornerRadius);

        // second test: Uniform corner radius of '2' with spin buttons in inline mode (T-rule applies now)
        numberBox.SpinButtonPlacementMode = NumberBoxSpinButtonPlacementMode.Inline;

        Content.UpdateLayout();

        spinButtonDown = TestUtilities.FindDescendents<RepeatButton>(numberBox).Where(e => e.Name == "DownSpinButton").Single();

        Verify.AreEqual(new CornerRadius(2, 0, 0, 2), textBox.CornerRadius);
        Verify.AreEqual(new CornerRadius(0, 2, 2, 0), spinButtonDown.CornerRadius);

        // third test: Set uniform corner radius of '4' with spin buttons in inline mode
        numberBox.CornerRadius = new CornerRadius(4);
    });
    IdleSynchronizer.Wait();

    RunOnUIThread.Execute(() =>
    {
         // This check makes sure that updating the CornerRadius values of the numberbox in inline mode
        // does not break the T-rule.
        Verify.AreEqual(new CornerRadius(4, 0, 0, 4), textBox.CornerRadius);
        Verify.AreEqual(new CornerRadius(0, 4, 4, 0), spinButtonDown.CornerRadius);
    });
}
```

Comment (StephenLPeters) [reply dev/NumberBox/APITests/NumberBoxTests.cs:26]: Strange, @ranjeshj I wouldn't expect a behavioral difference here.

Comment (StephenLPeters) [reply dev/NumberBox/APITests/NumberBoxTests.cs:26]: @Felix-Dev I still prefer the updated, working code above.

Comment (Felix-Dev) [reply dev/NumberBox/APITests/NumberBoxTests.cs:26]: @StephenLPeters Updated the test. Please take a look. (I added one more check in the API test.)
