### PR TITLE
RadioButtons layout account for available size.

### LINKED ISSUE #1695: RadioButtons grows wider than its parent container
**Describe the bug**
```xaml
<Border
    Width="260"
    Background="{ThemeResource SystemControlPageBackgroundChromeLowBrush}">
    <muxc:RadioButtons MaxColumns="3">
        <x:Int32>1</x:Int32>
        <x:Int32>2</x:Int32>
        <x:Int32>3</x:Int32>
        <x:Int32>4</x:Int32>
        <x:Int32>5</x:Int32>
        <x:Int32>6</x:Int32>
        <x:Int32>7</x:Int32>
        <x:Int32>8</x:Int32>
        <x:Int32>9</x:Int32>
    </muxc:RadioButtons>
</Border>
```
image
As the image shows, RadioButtons shows 3 columns and gets clipped.

**Expected behavior**
RadioButtons shows 2 columns.

**Version Info**
NuGet package version: 
2.3.191127001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

### PR DESCRIPTION
**Pull request by StephenLPeters**
When there isn't enough space to display the requested number of columns we have layout reduce the number of columns to the maximum that fits in the space.

Fixes #1695

### CODE REVIEW

File: dev/RadioButtons/ColumnMajorUniformToLargestGridLayout.cpp [hunk 1]
```diff
@@ -138,6 +131,19 @@ void ColumnMajorUniformToLargestGridLayout::OnMaxColumnsPropertyChanged(const wi
     InvalidateMeasure();
 }
 
+int ColumnMajorUniformToLargestGridLayout::CalculateColumns(int childCount, float maxItemWidth, float availableWidth)
+{
+    auto const maxColumns = MaxColumns();
+    auto const columnSpacing = ColumnSpacing();
+
+    auto const extraSpaceAfterFirstColumn = availableWidth - maxItemWidth;
+    auto const maxExtraColumns = std::max(0.0, std::floor(extraSpaceAfterFirstColumn / (columnSpacing + maxItemWidth)));
```
Comment (jevansaks) [inline dev/RadioButtons/ColumnMajorUniformToLargestGridLayout.cpp]: I'm a bit lost in this function. Could you add some comments for how the calculation it's doing? From the variable names alone I don't understand the approach.

Comment (StephenLPeters) [reply dev/RadioButtons/ColumnMajorUniformToLargestGridLayout.cpp]: How's this look?

Comment (jevansaks) [reply dev/RadioButtons/ColumnMajorUniformToLargestGridLayout.cpp]: Thanks, the new ascii art is great! :)
