### PR TITLE
Fix issue with selection being raised when selection did not change

### LINKED ISSUE #1642: SelectionModel fires selection changed events when selection hasn't changed
I think that this issue is exclusive to SingleSelect. Selection Model clears selection as the first action whenever you call select on it.

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Add checks for single selection to prevent raising event in case new selection is previous one.
## Motivation and Context

Closes #1642
## How Has This Been Tested?

Add API test

### CODE REVIEW

File: dev/Repeater/SelectionModel.cpp [hunk 1]
```diff
@@ -587,16 +587,32 @@ void SelectionModel::SelectImpl(int index, bool select)
 {
     if (m_singleSelect)
     {
-        ClearSelection(true /*resetAnchor*/, false /* raiseSelectionChanged */);
+        // Check if new index is different to current one
+        if (m_rootNode->SelectedIndex() != index)
+        {
+            ClearSelection(true /*resetAnchor*/, false /* raiseSelectionChanged */);
+            auto selected = m_rootNode->Select(index, select);
```
Comment (StephenLPeters) [inline dev/Repeater/SelectionModel.cpp:594]: Wont this still be an issue in the single select case?

File: dev/Repeater/SelectionModel.cpp [hunk 2]
```diff
@@ -587,16 +587,32 @@ void SelectionModel::SelectImpl(int index, bool select)
...
-    auto selected = m_rootNode->Select(index, select);
-    if (selected)
+    else
     {
-        AnchorIndex(winrt::make<IndexPath>(index));
+        bool alreadySelected = m_rootNode->IsSelected(index);
+        auto selected = m_rootNode->Select(index, select);
+        if (selected)
+        {
+            AnchorIndex(winrt::make<IndexPath>(index));
```
Comment (StephenLPeters) [inline dev/Repeater/SelectionModel.cpp:608]: >AnchorIndex [](start = 12, length = 11)

In the case where this index was already selected why are we updating the anchor?

File: dev/Repeater/SelectionModel.cpp [hunk 3]
```diff
@@ -587,16 +587,32 @@ void SelectionModel::SelectImpl(int index, bool select)
...
+        }
+        // Only raise event if it was not already selected
+        if (!alreadySelected)
+        {
+            OnSelectionChanged();
```
Comment (StephenLPeters) [inline dev/Repeater/SelectionModel.cpp:613]: The code in these branches is very similar, is there a better way to refactor it?

File: dev/Repeater/SelectionModel.cpp [hunk 4]
```diff
@@ -619,32 +635,56 @@ void SelectionModel::SelectWithGroupImpl(int groupIndex, int itemIndex, bool sel
...
+
+        SelectionTreeHelper::TraverseIndexPath(
+            m_rootNode,
+            index,
+            true, /* realizeChildren */
+            [&selected, &select, &selectionChanged](std::shared_ptr<SelectionNode> currentNode, const winrt::IndexPath& path, int depth, int childIndex)
+            {
+                if (depth == path.GetSize() - 1)
+                {
+                    // Node already selected, so we need to raise selection changed
```
Comment (StephenLPeters) [inline dev/Repeater/SelectionModel.cpp:669]: >Node already selected [](start = 23, length = 21)

node is not already selected

File: dev/Repeater/SelectionModel.cpp [hunk 5]
```diff
@@ -619,32 +635,56 @@ void SelectionModel::SelectWithGroupImpl(int groupIndex, int itemIndex, bool sel
 void SelectionModel::SelectWithPathImpl(const winrt::IndexPath& index, bool select, bool raiseSelectionChanged)
 {
     bool selected = false;
+    bool selectionChanged = true;
     if (m_singleSelect)
```
Comment (StephenLPeters) [inline dev/Repeater/SelectionModel.cpp:639]: >m_singleSelect [](start = 8, length = 14)

Why is the single select case handled specially here, wouldn't the multi select path handle this just fine? Is it just a perf optimization?

File: dev/Repeater/SelectionModel.cpp [hunk 6]
```diff
@@ -619,32 +635,56 @@ void SelectionModel::SelectWithGroupImpl(int groupIndex, int itemIndex, bool sel
 void SelectionModel::SelectWithPathImpl(const winrt::IndexPath& index, bool select, bool raiseSelectionChanged)
 {
     bool selected = false;
+    bool selectionChanged = true;
```
Comment (StephenLPeters) [inline dev/Repeater/SelectionModel.cpp:638]: >selectionChanged [](start = 9, length = 16)

This variable seems overloaded, you use it to get into the next block in the single select case and then use it for a different utility after that. Instead use two different variables please.

File: dev/Repeater/APITests/SelectionModelTests.cs [hunk 7]
```diff
@@ -980,6 +980,65 @@ public void SelectRangeRegressionTest()
...
+
+                var selectionModel = new SelectionModel() {
+                    Source = list,
+                    SingleSelect = true
+                };
+
+                // Single select index
+                selectionModel.Select(0);
+                selectionModel.SelectionChanged += SelectionModel_SelectionChanged;
+                selectionModel.Select(0);
```
Comment (StephenLPeters) [inline dev/Repeater/APITests/SelectionModelTests.cs:1000]: I'd suggest wrapping the Select calls that you are testing in Verify.DoesNotThrow() calls so that the test output is a little cleaner if this were to fail.

File: dev/Repeater/SelectionModel.cpp (hunk 2 above)
Comment (chingucoding) [reply dev/Repeater/SelectionModel.cpp:608]: Good point.

File: dev/Repeater/SelectionModel.cpp (hunk 5 above)
Comment (chingucoding) [reply dev/Repeater/SelectionModel.cpp:639]: Yes, this is faster than walking over the actual selection tree. The multi select behavior would also handle this case, but comparing the IndexPaths is faster here.

File: dev/Repeater/APITests/SelectionModelTests.cs (hunk 7 above)
Comment (chingucoding) [reply dev/Repeater/APITests/SelectionModelTests.cs:1000]: According to visual studio `Verify.NoThrow` is not available in project MUXControlsTestApp. Could that potentially be a problem?

Comment (chingucoding) [reply dev/Repeater/APITests/SelectionModelTests.cs:1000]: And it turns out, you can't run the MUXControlsTestApp with Verify.NoThrow. Should we add it now to the MSInterop.cs Verify class?

File: dev/Repeater/SelectionModel.cpp (hunk 6 above)
Comment (chingucoding) [reply dev/Repeater/SelectionModel.cpp]: Added a new variable for that.

File: dev/Repeater/SelectionModel.cpp (hunk 4 above)
Comment (chingucoding) [reply dev/Repeater/SelectionModel.cpp]: Fixed the comment

File: dev/Repeater/SelectionModel.cpp (hunk 3 above)
Comment (chingucoding) [reply dev/Repeater/SelectionModel.cpp]: Yes, good idea.

File: dev/Repeater/APITests/SelectionModelTests.cs (hunk 7 above)
Comment (StephenLPeters) [reply dev/Repeater/APITests/SelectionModelTests.cs:1000]: Nah, I don't think its worth it, what you have is sufficient.

**Comment by StephenLPeters** [comment]
@chingucoding these look like legitimate errors to me, could you take a look? :)

**Comment by chingucoding** [comment]
Sure, will take a look later today. Thanks for the ping @StephenLPeters !

**Comment by chingucoding** [comment]
My previous changes did not account for the fact that those methods also handle deselection. Should work now.

File: dev/Repeater/SelectionModel.cpp [hunk 8]
```diff
@@ -638,7 +638,8 @@ void SelectionModel::SelectWithPathImpl(const winrt::IndexPath& index, bool sele
     // Selection is actually different from previous one, so update.
     if (newSelection)
     {
-        bool changedSelection = false;
+        // If we unselect something, raise event any way, otherwise changedSelection is false
```
Comment (StephenLPeters) [inline dev/Repeater/SelectionModel.cpp:641]: Why? If we end up calling Select(x, false) and x was not selected then we shouldn't raise a selection changed event right?

Comment (chingucoding) [reply dev/Repeater/SelectionModel.cpp:647]: Oh, yes missed the whole deselect scenario. Added tests for that now and fixed any falsely raised selection changed events for deselecting already deselected nodes.

File: dev/Repeater/SelectionModel.cpp [hunk 9]
```diff
@@ -619,32 +620,70 @@ void SelectionModel::SelectWithGroupImpl(int groupIndex, int itemIndex, bool sel
 void SelectionModel::SelectWithPathImpl(const winrt::IndexPath& index, bool select, bool raiseSelectionChanged)
 {
     bool selected = false;
```
Comment (ranjeshj) [inline dev/Repeater/SelectionModel.cpp:622]: this variable can be moved into the if(newSelection) block.

File: dev/Repeater/SelectionModel.cpp [hunk 10]
```diff
@@ -619,32 +620,70 @@ void SelectionModel::SelectWithGroupImpl(int groupIndex, int itemIndex, bool sel
...
+    bool newSelection = true;
+
+    // Handle single select differently as comparing indexpaths is faster
     if (m_singleSelect)
     {
-        ClearSelection(true /*restAnchor*/, false /* raiseSelectionChanged */);
+        if (auto const selectedIndex = SelectedIndex())
+        {
+            // If paths are equal and we want to select, skip everything and do nothing
+            if (selectedIndex.CompareTo(index) == 0 && select)
```
Comment (ranjeshj) [inline dev/Repeater/SelectionModel.cpp:631]: switch the order of the check so we don't have to access and compare the index path if select is false.

File: dev/Repeater/APITests/SelectionModelTests.cs [hunk 11]
```diff
@@ -980,6 +980,118 @@ public void SelectRangeRegressionTest()
...
+                // multi select indexpath
+                selectionModel.SelectAt(IndexPath.CreateFrom(1));
+                selectionModel.SelectAt(IndexPath.CreateFrom(2));
+                testName = "SelectAt(IndexPath index), multiselect";
+                selectionModel.SelectionChanged += SelectionModel_SelectionChanged;
+                selectionModel.SelectAt(IndexPath.CreateFrom(1));
+                selectionModel.SelectAt(IndexPath.CreateFrom(2));
+            });
+
+            void SelectionModel_SelectionChanged(SelectionModel sender, SelectionModelSelectionChangedEventArgs args)
```
Comment (ranjeshj) [inline dev/Repeater/APITests/SelectionModelTests.cs:1036]: Neat!  Just learnt about Nested local functions!

File: dev/Repeater/APITests/SelectionModelTests.cs [hunk 12]
```diff
@@ -980,6 +980,118 @@ public void SelectRangeRegressionTest()
...
+                var list = Enumerable.Range(0, 10).ToList();
+
+                var selectionModel = new SelectionModel() {
+                    Source = list,
+                    SingleSelect = true
+                };
+
+                // Single select index
+                selectionModel.Select(0);
+                selectionModel.SelectionChanged += SelectionModel_SelectionChanged;
```
Comment (ranjeshj) [inline dev/Repeater/APITests/SelectionModelTests.cs:999]: nit: could make this describe what it does better by naming it ThrowIfRaised or something similar.

**Comment by ranjeshj** [comment]
> void SelectionModel::SelectRangeFromAnchorImpl(int index, bool select)

This change is not accounting for no-ops during range selection, but perhaps we can add that support if/when the need arises and avoid the extra complexity.

---
Refers to: dev/Repeater/SelectionModel.cpp:690 in 6b1e4c7. [](commit_id = 6b1e4c74d73e520e11d53cacc65f171015a74e9f, deletion_comment = False)

**Comment by ranjeshj** [comment]
@ojhad @StephenLPeters do we have extra logic in NavigationView to avoid this bug that we could remove after this change ?

File: dev/Repeater/SelectionModel.cpp (hunk 10 above)
Comment (chingucoding) [reply dev/Repeater/SelectionModel.cpp]: Great point! Fixed now

File: dev/Repeater/APITests/SelectionModelTests.cs (hunk 12 above)
Comment (chingucoding) [reply dev/Repeater/APITests/SelectionModelTests.cs]: Yeah, the naming was not great. Fixed.

**Comment by chingucoding** [comment]
> @ojhad @StephenLPeters do we have extra logic in NavigationView to avoid this bug that we could remove after this change ?

The initial report originated during the switch of RadioButtons to ItemsRepeater. But it does not seem that for that, there was a fix deployed in the RadioButtons control: https://github.com/microsoft/microsoft-ui-xaml/pull/1623#discussion_r347573403

If there was a fix for NavView or RadioButtons for this exact, I would be more than happy to remove that.

**Comment by ojhad** [comment]
> @ojhad @StephenLPeters do we have extra logic in NavigationView to avoid this bug that we could remove after this change ?

There is a check, but it shouldn't be removed, as it serves another purpose as well when syncing selection between the NavigationView state and the selection model.
