### PR TITLE
Fix issue with TabPaneFooter Width/MinWidth not being respected

### LINKED ISSUE #1615: TabView: Change TabStripFooter's MinWidth when app started with a narrow window is not take effect
**Describe the bug**
 After extend TabView into the title bar, we need to change the TabStripFooter's MinWidth to keep off the title bar buttons. But change TabStripFooter's MinWidth when app started with a narrow window is not take effect

**Steps to reproduce the bug**
1. Extend the TabView into the TitleBar, and change the TabStripFooter's MinWidth when "OnTitleBarLayoutMetricsChanged" event is invoked.
2. Add 3 or more tabitems in the TabView.
3. Close the app with a narrow window state.
4. Open the app with the narrow window, the OnTitleBarLayoutMetricsChanged is invoked and the TabStripFooter's MinWidth is changed, but the TabView still mixed with the TitleBar's buttons until drag the window to a wide state.

**Expected behavior**
TabView shoud keep away from the TitleBar's buttons.

**Screenshots**
批注 2019-11-15 000540
批注 2019-11-15 000428
批注 2019-11-15 000350

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.2.190917002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

The layout of the TabView didn't take into account changes of the Width/MinWidth property of the TabPaneFooter. This PR changes that and listens to changes made to those two properties.

## Motivation and Context

Closes #1615 , not sure if would close issue #3280
## How Has This Been Tested?

Add new API test, also checked in the tear out sample of the XCG for future testing of that scenario (e.g. new titlebar api for TabView)

### CODE REVIEW

File: dev/TabView/TabView.cpp [hunk 1]
```diff
@@ -227,6 +237,20 @@ void TabView::OnSelectedItemPropertyChanged(const winrt::DependencyPropertyChang
...
+void TabView::OnTabStripFooterPropertyChanged(const winrt::DependencyPropertyChangedEventArgs& args)
+{
+    if (const auto oldFooter = args.OldValue().try_as<winrt::FrameworkElement>())
+    {
+        oldFooter.UnregisterPropertyChangedCallback(winrt::FrameworkElement::MinWidthProperty(), m_footerMinWidthProperyChangedToken);
+        oldFooter.UnregisterPropertyChangedCallback(winrt::FrameworkElement::WidthProperty(), m_footerWidthProperyChangedToken);
+    }
+    if (const auto newFooter = args.NewValue().try_as<winrt::FrameworkElement>())
+    {
+        m_footerMinWidthProperyChangedToken = newFooter.RegisterPropertyChangedCallback(winrt::FrameworkElement::MinWidthProperty(), { this,&TabView::OnComponentSizeChanged });
```
Comment (ranjeshj) [inline dev/TabView/TabView.cpp:249]: can these be done using a revoker ?

Comment (ranjeshj) [inline dev/TabView/TabView.cpp:249]: >OnComponentSizeChanged [](start = 150, length = 22)

nit: Component sounds very generic. perhaps OnFooterSizeChanged ?

Comment (chingucoding) [reply dev/TabView/TabView.cpp:249]: I don't think that's possible. We need to listen to more or less generic dependency property changes, there is no dedicated (Min)WidthPropertyChanged event, so we need to use that route. Unfortunately, RegisterPropertyChangedCallback only works through tokens.

Comment (chingucoding) [reply dev/TabView/TabView.cpp]: Good idea, changed the name to OnFooterSizeChanged.

File: dev/TabView/TabView.cpp [hunk 2]
```diff
@@ -68,6 +68,16 @@ TabView::TabView()
     }
 }
 
+TabView::~TabView()
+{
+    UnhookEventsAndClearFields();
+    if (const auto footer = TabStripFooter().try_as<winrt::FrameworkElement>())
+    {
+        footer.UnregisterPropertyChangedCallback(winrt::FrameworkElement::MinWidthProperty(), m_footerMinWidthProperyChangedToken);
```
Comment (StephenLPeters) [inline dev/TabView/TabView.cpp:76]: >m_footerMinWidthProperyChangedToken [](start = 94, length = 35)

Do we need to check to see if this token is not 0?

Comment (chingucoding) [reply dev/TabView/TabView.cpp:76]: I don't think it can be 0 if we actually get in there since that would require us to have a footer, yet not having registered to said footer. Anytime the footer changes, we update the tokens so we would need to get here with footer changes being unnoticed by the TabView.

File: dev/TabView/TabView.cpp (hunk 1 above)
Comment (StephenLPeters) [reply dev/TabView/TabView.cpp]: @chingucoding please use the cpp winrt helper RegisterPropertyChanged [https://github.com/microsoft/microsoft-ui-xaml/blob/cc0d193295964fc0a94d78e39acacf4cb1f0e033/dev/inc/CppWinRTHelpers.h#L280](https://github.com/microsoft/microsoft-ui-xaml/blob/cc0d193295964fc0a94d78e39acacf4cb1f0e033/dev/inc/CppWinRTHelpers.h#L280)

---
In reply to: [528202327](https://github.com/microsoft/microsoft-ui-xaml/pull/3531#discussion_r528202327) [](ancestors = 528202327)

Comment (chingucoding) [reply dev/TabView/TabView.cpp]: Sure, wish I knew that existed earlier. Is fixed now.

I also noticed that a lot of the code uses the token pattern to do this, should we updated all occurrences to the helper instead of a token?

**Review by ojhad — APPROVED** [review]
