### PR TITLE
NavigationView: Fix issue where disabling settings would still show gap

### LINKED ISSUE #3771: [NavigationView] FooterMenuItems show unwanted scrollbar
**Describe the bug**
NavigationView FooterMenuItems show unwanted scrollbar

**Steps to reproduce the bug**
1. Add a `NavigationView `and add some `NavigationViewItem`s
2. Hover with the mouse over the right area of the FooterMenuItems area

**Expected behavior**
No Scrollbar when there's enough space

**Screenshots**
image

NuGet package version: 
Microsoft.UI.Xaml 2.5.0

**Additional context**
Might have been introduced here: https://github.com/microsoft/microsoft-ui-xaml/issues/3447

### LINKED ISSUE #3900: NavigationView's Settings menu item space is still present when `IsSettingsVisible` set to false
**Describe the bug**
In a `NavigationView`, when the Settings `NavigationViewMenuItem` is hidden with `IsSettingsVisible="False"`, the spacing for that menu item still exists.

**Steps to reproduce the bug**
<details>
<summary> Sample Code</summary>

```xml
<Page
    x:Class="WinUIPlayground.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:WinUIPlayground"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d">
    <Page.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
    </Page.Resources>

    <muxc:NavigationView
        IsSettingsVisible="True">
        <muxc:NavigationView.MenuItems>
            <muxc:NavigationViewItem>Menu Item 1</muxc:NavigationViewItem>
            <muxc:NavigationViewItem>Menu Item 2</muxc:NavigationViewItem>
            <muxc:NavigationViewItem>Menu Item 3</muxc:NavigationViewItem>
            <muxc:NavigationViewItem>Menu Item 4</muxc:NavigationViewItem>
        </muxc:NavigationView.MenuItems>

        <muxc:NavigationView.PaneFooter>
            <muxc:NavigationViewItem>
                <muxc:NavigationViewItem.Icon>
                    <FontIcon Glyph="&#xE713;" />
                </muxc:NavigationViewItem.Icon>
                <muxc:NavigationViewItem.Content>
                    Custom Settings Menu Item
                </muxc:NavigationViewItem.Content>
            </muxc:NavigationViewItem>
        </muxc:NavigationView.PaneFooter>
    </muxc:NavigationView>
</Page>

```
</details>

1. Create a muxc:NavigationView with a PaneFooter and `IsSettingsVisible="False"` (see sample code above)
2. Launch the sample app

**Expected behavior**
The `PaneFooter` should be flush with the bottom of the NavigationView.

**Screenshots**
NavigationViewPaneFooterBug

**Version Info**
NuGet package version: 
[Microsoft.UI.Xaml.2.5.0-prerelease.201202003]

**NOTE:** This did not exist in [Microsoft.UI.Xaml.2.5.0-prerelease.200609001]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Remove min-height setters as those didn't do anything and update layouting logic to handle cases where one of the collections is empty correctly. 

@carlos-zamora FYI :)
## Motivation and Context

Closes #3900 
Closes #3771
## How Has This Been Tested?

Add two new interaction tests. The test page has also been updated to have the tests run a bit faster since we hit "breaking" conditions earlier. As part of that, I needed to adjust some numbers in existing tests.
## Screenshots (if appropriate):

Image showing NavigationView with overfull list of menuitems and settings being disabled showing no gap at the bottom.

### CODE REVIEW

File: dev/NavigationView/NavigationView.cpp [hunk 1]
```diff
@@ -1461,9 +1461,14 @@ void NavigationView::UpdatePaneLayout()
...
             if (const auto &paneContentRow = m_itemsContainerRow.get())
             {
-                // 20px is the padding between the two item lists
-                if (const auto &paneFooter = m_leftNavFooterContentBorder.get())
+                // We have 9px margin at the bottom, that's why we subtract 9 everywhere
+                if (m_menuItemsSource && m_footerItemsSource && m_menuItemsSource.Count() * m_footerItemsSource.Count() == 0 && !IsSettingsVisible())
                 {
+                    // Either of these collections has no items, let it take all of the available space then.
+                    return paneContentRow.ActualHeight() - 9;
+                }else if (const auto &paneFooter = m_leftNavFooterContentBorder.get())
```
Comment (ranjeshj) [inline dev/NavigationView/NavigationView.cpp:1469]: nit: newline

File: dev/NavigationView/NavigationView.cpp [hunk 2]
```diff
@@ -1490,7 +1495,25 @@ void NavigationView::UpdatePaneLayout()
                         {
                             const auto footersActualHeight = footerItemsRepeater.ActualHeight();
                             const auto menuItemsActualHeight = menuItems.ActualHeight();
-                            if (totalAvailableHeight > menuItemsActualHeight + footersActualHeight)
+
+                            if (m_footerItemsSource.Count() == 0 && !IsSettingsVisible())
+                            {
+                                footerItemsScrollViewer.MaxHeight(0);
+                                if (const auto& separator = m_visualItemsSeparator.get())
```
Comment (ranjeshj) [inline dev/NavigationView/NavigationView.cpp:1502]: I'm wondering if there is a simpler logic to determine when to show the separator so we can avoid duplicating this code in each block. Could we do just one check at the end to determine visible/collapsed ?

Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp:1502]: I don't really think there is a simpler way of determining this. We could introduce a function for setting the visibility, at least we would save on the if case. What do you think?

**Comment by ranjeshj** [comment]
@chingucoding can you merge with master ?

**Comment by chingucoding** [comment]
Merged now @ranjeshj (same for #3860).

File: dev/NavigationView/NavigationView.cpp [hunk 3]
```diff
@@ -1465,9 +1465,15 @@ void NavigationView::UpdatePaneLayout()
         const auto totalAvailableHeight = [this]() {
             if (const auto &paneContentRow = m_itemsContainerRow.get())
             {
-                // 20px is the padding between the two item lists
-                if (const auto &paneFooter = m_leftNavFooterContentBorder.get())
+                // We have 9px margin at the bottom, that's why we subtract 9 everywhere
+                if (m_menuItemsSource && m_footerItemsSource && m_menuItemsSource.Count() * m_footerItemsSource.Count() == 0 && !IsSettingsVisible())
                 {
+                    // Either of these collections has no items, let it take all of the available space then.
+                    return paneContentRow.ActualHeight() - 9;
```
Comment (StephenLPeters) [inline dev/NavigationView/NavigationView.cpp:1472]: this hurts to look at.. but it seems like we were already doing it..  (can we get this value from the Margin property instead of blindingly subtracting 9?)

File: dev/NavigationView/NavigationView.cpp [hunk 4]
```diff
@@ -1494,7 +1500,25 @@ void NavigationView::UpdatePaneLayout()
...
+                            }
+                            else if (m_menuItemsSource.Count() == 0)
+                            {
+                                footerItemsScrollViewer.MaxHeight(totalAvailableHeight);
+                                if (const auto& separator = m_visualItemsSeparator.get())
+                                {
+                                    separator.Visibility(winrt::Visibility::Collapsed);
+                                }
+                                return 0.0;
+                            }else if (totalAvailableHeight > menuItemsActualHeight + footersActualHeight)
```
Comment (StephenLPeters) [inline dev/NavigationView/NavigationView.cpp:1521]: nit: new line for else statement.

File: dev/NavigationView/NavigationView.cpp [hunk 5]
```diff
@@ -1494,7 +1500,25 @@ void NavigationView::UpdatePaneLayout()
                         {
                             const auto footersActualHeight = footerItemsRepeater.ActualHeight();
                             const auto menuItemsActualHeight = menuItems.ActualHeight();
-                            if (totalAvailableHeight > menuItemsActualHeight + footersActualHeight)
+
+                            if (m_footerItemsSource.Count() == 0 && !IsSettingsVisible())
+                            {
+                                footerItemsScrollViewer.MaxHeight(0);
```
Comment (StephenLPeters) [inline dev/NavigationView/NavigationView.cpp:1506]: I think it would be better to add a new state to the NavigationView's VSM and call GoToState, instead of setting these layout properties from code.

File: dev/NavigationView/NavigationView.xaml [hunk 6]
```diff
@@ -463,10 +463,10 @@
                                         <!-- "Non header" content -->
                                         <Grid x:Name="ItemsContainerGrid" Grid.Row="6" Margin="0,0,0,8">
                                             <Grid.RowDefinitions>
-                                                <RowDefinition Height="Auto" MinHeight="{ThemeResource NavigationViewItemOnLeftMinHeight}"/> <!-- MenuItems -->
+                                                <RowDefinition x:Name="MenuItemsRow" Height="Auto"/> <!-- MenuItems -->
                                                 <RowDefinition Height="*" MinHeight="21"/> <!-- Fill spacing -->
                                                 <RowDefinition Height="Auto" /> <!-- PaneFooter -->
-                                                <RowDefinition Height="Auto" MinHeight="{ThemeResource NavigationViewItemOnLeftMinHeight}"/> <!-- FooterItems -->
+                                                <RowDefinition x:Name="FooterItemsRow" Height="Auto"/> <!-- FooterItems -->
```
Comment (StephenLPeters) [inline dev/NavigationView/NavigationView.xaml:469]: Why do these row definitions need names?

Comment (chingucoding) [reply dev/NavigationView/NavigationView.xaml]: Removed now.

File: dev/NavigationView/NavigationView.cpp (hunk 5 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp:1507]: Added a VisualState for the separator, however left the max height setting as is since I am not sure how overriding the VisualState's setter would work and I want to prevent ending in a bad state.

Comment (beervoley) [reply dev/NavigationView/NavigationView.cpp:1525]: @chingucoding I don't think we need maxHeight setter for the bottom footer. If there are no items - it naturally will have height 0 :)

File: dev/NavigationView/NavigationView.cpp (hunk 3 above)
Comment (beervoley) [reply dev/NavigationView/NavigationView.cpp:1491]: +1, that would be nicer

Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp]: Fixed now.

File: dev/NavigationView/NavigationView.cpp (hunk 5 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp]: Good point, removed that setter.

File: dev/NavigationView/NavigationView.cpp [hunk 7]
```diff
@@ -1483,14 +1485,28 @@ void NavigationView::UpdatePaneLayout()
...
+                }();
+
+                // We have 9px margin at the bottom, that's why we subtract 9 everywhere
+                if (m_menuItemsSource && m_footerItemsSource && m_menuItemsSource.Count() * m_footerItemsSource.Count() == 0 && !IsSettingsVisible())
                 {
-                    return paneContentRow.ActualHeight() - 29 - paneFooter.ActualHeight();
+                    // Either of these collections has no items, let it take all of the available space then.
+                    return paneContentRow.ActualHeight() - bottomMargin;
+                }
+                else if (const auto &paneFooter = m_leftNavFooterContentBorder.get())
```
Comment (beervoley) [inline dev/NavigationView/NavigationView.cpp:1502]: this if statement will always be true. I think we first have to see if PaneFooter() property is set. If it is - then we execute the clause. If there's no panefooter set by the user, why would we reserve 20 pixels?

File: dev/NavigationView/NavigationView.xaml [hunk 8]
```diff
@@ -506,10 +525,10 @@
                                         <!-- "Non header" content -->
                                         <Grid x:Name="ItemsContainerGrid" Grid.Row="6" Margin="0,0,0,8">
                                             <Grid.RowDefinitions>
-                                                <RowDefinition Height="Auto" MinHeight="{ThemeResource NavigationViewItemOnLeftMinHeight}"/> <!-- MenuItems -->
+                                                <RowDefinition x:Name="MenuItemsRow" Height="Auto"/> <!-- MenuItems -->
                                                 <RowDefinition Height="*" MinHeight="21"/> <!-- Fill spacing -->
```
Comment (beervoley) [inline dev/NavigationView/NavigationView.xaml:529]: I think we need to remove these 21 px from here as well. If there's no footer items and no pane footer - main menu items should have all the space given.

File: dev/NavigationView/NavigationView.cpp (hunk 7 above)
Comment (beervoley) [reply dev/NavigationView/NavigationView.cpp:1502]: As well as bottom margin is not 9, it's 8?
image
The entire calculation of actual height here could be something like this:
image

Comment (beervoley) [reply dev/NavigationView/NavigationView.cpp:1502]: We're also missing PaneFooter() property changed. So if PaneFooter is dynamically set - it wouldn't properly update the layout

Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp:1502]: That's a good point. It looks like that you already have the code for some of this. Would you like to push the changes first and I'll handle the rest after your push @beervoley ?

Comment (beervoley) [reply dev/NavigationView/NavigationView.cpp:1502]: @chingucoding yup, 5 min

Comment (beervoley) [reply dev/NavigationView/NavigationView.cpp]: @chingucoding, I've updated the code and refactored this:
image
a little bit so it's easier to read. Please feel free to refactor it if it doesn't feel right to you :)

File: dev/NavigationView/NavigationView.xaml [hunk 9]
```diff
@@ -71,7 +71,13 @@
...
                             <VisualStateGroup x:Name="TogglePaneGroup">
-                                <VisualState x:Name="TogglePaneButtonVisible" />
+                                <VisualState x:Name="TogglePaneButtonVisible">
+                                    <VisualState.Setters>
+                                        <!-- Might not need this setter when all the margins/paddings will be adequately set. -->
+                                        <!-- This MinHeight setter is only here to ensure that AutoSuggestBox doesn't draw over ToggelButton. -->
+                                        <Setter Target="PaneContentGridToggleButtonRow.MinHeight" Value="{StaticResource NavigationViewPaneHeaderRowMinHeight}"/>
+                                    </VisualState.Setters>
+                                </VisualState>
                                 <VisualState x:Name="TogglePaneButtonCollapsed" />
```
Comment (karenbtlai) [inline dev/NavigationView/NavigationView.xaml:81]: nit: the default visual state should be the first one in the group

File: dev/NavigationView/NavigationView.xaml [hunk 10]
```diff
@@ -158,6 +164,19 @@
                                     </VisualState.Setters>
                                 </VisualState>
                             </VisualStateGroup>
+
+                            <VisualStateGroup x:Name="PaneSeperatorStates">
```
Comment (karenbtlai) [inline dev/NavigationView/NavigationView.xaml:168]: Typo: should be `PaneSeparatorStates`

Comment (karenbtlai) [inline dev/NavigationView/NavigationView.xaml:168]: @beervoley can you also start an email thread to review the new VisualStateGroup and state names?

File: dev/NavigationView/NavigationView.xaml [hunk 11]
```diff
@@ -158,6 +164,19 @@
...
+                                <VisualState x:Name="SeparatorVisible">
+                                    <VisualState.Setters>
+                                        <Setter Target="VisualItemsSeparator.Visibility" Value="Visible"/>
```
Comment (karenbtlai) [inline dev/NavigationView/NavigationView.xaml:171]: The separatorVisible should be the default state, so should not have additional setters.

File: dev/NavigationView/NavigationView.cpp (hunk 7 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp]: Code looks good to me, thank you so much for helping out @beervoley!

File: dev/NavigationView/NavigationView.xaml (hunk 11 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationView.xaml:172]: Default state is SeparatorCollapsed, not the visible state. Fixed now and removed the setter for that.

File: dev/NavigationView/NavigationView.xaml (hunk 10 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationView.xaml]: Thanks, fixed now.

File: dev/NavigationView/NavigationView.xaml (hunk 9 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationView.xaml]: Fixed now.

File: dev/NavigationView/NavigationView.cpp [hunk 12]
```diff
@@ -1483,15 +1485,34 @@ void NavigationView::UpdatePaneLayout()
         const auto totalAvailableHeight = [this]() {
             if (const auto &paneContentRow = m_itemsContainerRow.get())
             {
-                // 20px is the padding between the two item lists
-                if (const auto &paneFooter = m_leftNavFooterContentBorder.get())
+                const double itemsContainerMargin = [this]() {
+                    if (const auto itemsContainer = m_itemsContainer.get())
+                    {
+                        auto const margin = itemsContainer.Margin();
```
Comment (karenbtlai) [inline dev/NavigationView/NavigationView.cpp:1491]: nit: should be const auto to be consistent with the others?

File: dev/NavigationView/NavigationView.cpp [hunk 13]
```diff
@@ -1483,15 +1485,34 @@ void NavigationView::UpdatePaneLayout()
...
+                        return margin.Top + margin.Bottom;
+                    }
+                    return 0.0;
+                }();
+                auto availableHeight = paneContentRow.ActualHeight() - itemsContainerMargin;
+
+                if (PaneFooter())
+                {
+                    availableHeight -= 21;
```
Comment (karenbtlai) [inline dev/NavigationView/NavigationView.cpp:1500]: Comment on what this value means or add a static constexpr?

Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp:1501]: Added a comment, good idea.

File: dev/NavigationView/NavigationView.cpp (hunk 12 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp]: Good idea, fixed

File: dev/NavigationView/NavigationView.xaml [hunk 14]
```diff
@@ -435,7 +450,7 @@
                                         <Grid.RowDefinitions>
                                             <RowDefinition Height="Auto"/>
                                             <RowDefinition Height="0"/> <!-- above button margin + back button space -->
-                                            <RowDefinition x:Name="PaneContentGridToggleButtonRow" Height="Auto" MinHeight="{StaticResource NavigationViewPaneHeaderRowMinHeight}"/>
+                                            <RowDefinition x:Name="PaneContentGridToggleButtonRow" Height="Auto"/>
```
Comment (StephenLPeters) [inline dev/NavigationView/NavigationView.xaml:453]: >PaneContentGridToggleButtonRow [](start = 67, length = 30)

Why is this named?

File: dev/NavigationView/NavigationView.xaml [hunk 15]
```diff
@@ -506,10 +521,10 @@
                                         <!-- "Non header" content -->
                                         <Grid x:Name="ItemsContainerGrid" Grid.Row="6" Margin="0,0,0,8">
                                             <Grid.RowDefinitions>
-                                                <RowDefinition Height="Auto" MinHeight="{ThemeResource NavigationViewItemOnLeftMinHeight}"/> <!-- MenuItems -->
-                                                <RowDefinition Height="*" MinHeight="21"/> <!-- Fill spacing -->
+                                                <RowDefinition x:Name="MenuItemsRow" Height="Auto"/> <!-- MenuItems -->
```
Comment (StephenLPeters) [inline dev/NavigationView/NavigationView.xaml:524]: >MenuItemsRow [](start = 71, length = 12)

Why is this named?

File: dev/NavigationView/NavigationView.cpp [hunk 16]
```diff
@@ -1483,15 +1485,35 @@ void NavigationView::UpdatePaneLayout()
...
+                        return margin.Top + margin.Bottom;
+                    }
+                    return 0.0;
+                }();
+                auto availableHeight = paneContentRow.ActualHeight() - itemsContainerMargin;
+
+                // The -21 below is to account for the separator height that we need to subtract.
+                if (PaneFooter())
+                {
+                    availableHeight -= 21;
```
Comment (StephenLPeters) [inline dev/NavigationView/NavigationView.cpp:1501]: >21 [](start = 39, length = 2)

Is there a way to get this value programmatically instead using a magic number?

File: dev/NavigationView/NavigationView.xaml (hunk 14 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationView.xaml:472]: For VSM in line 52 of that file.

File: dev/NavigationView/NavigationView.cpp (hunk 16 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp:1496]: I'm afraid not really, I wasn't able to "find" this in the layout, (actual)height of the separator is 6, however it still takes up that place.

File: dev/NavigationView/NavigationView.xaml (hunk 15 above)
Comment (chingucoding) [reply dev/NavigationView/NavigationView.xaml]: Because we forgot to remove that name, fixed now.

File: dev/NavigationView/NavigationView.cpp (hunk 16 above)
Comment (StephenLPeters) [reply dev/NavigationView/NavigationView.cpp:1496]: At the very least we should use a named constant

**Review by beervoley — APPROVED** [review]

**Comment by beervoley** [comment]
@chingucoding thanks for your help!!!

**Comment by chingucoding** [comment]
Pleasure helping out! Thank you @beervoley in assisting this PR!
