### PR TITLE
Teaching Tip Fixes

### LINKED ISSUE #643: TeachingTip tests fail in Helix
I found out while working on #642 that TeachingTip tests currently aren't being run in Helix, and it looks like they're all failing on at least some run.  See for example this test run:

https://dev.azure.com/ms/microsoft-ui-xaml/_build/results?buildId=13416&_a=summary&view=ms.vss-test-web.build-test-results-tab

I'll disable them for now, but they should be re-enabled once they're passing.

### LINKED ISSUE #747: Teaching Tip does not respect animations settings
Teaching Tip's ExpandToOpen and ContractToClose animations do not respect the ShowAnimationsInWindows user setting.

### PR DESCRIPTION
**Pull request by KevinTXY**
The following fixes to teaching tips are included:

**Product Bugs**
- TeachingTips now respect the "Show Animations In Windows" setting on the user's machine

**Test Case Bugs**
- TipsWhichDoNotFitDoNotOpen test case fixed.
- VerifyTheming test case functions correctly even when the developer has a non-default Windows theme set (dark mode is the best mode 💯  )

Fixes #747

### CODE REVIEW

File: dev/TeachingTip/InteractionTests/TeachingTipTests.cs [hunk 1]
```diff
@@ -448,6 +448,7 @@ public void TipsWhichDoNotFitDoNotOpen()
                     UseTestWindowBounds(10, 10, 10, 10);
 
                     elements.GetShowButton().Invoke();
+                    Wait.ForIdle();
```
Comment (llongley) [inline dev/TeachingTip/InteractionTests/TeachingTipTests.cs]: We have an extension method InvokeAndWait() that you can call that does this in one line.

**Comment by StephenLPeters** [comment]
>             elements.GetBringTargetIntoViewButton().Invoke();

Chaning this to InvokeAndWait() as well makes sense.

---
Refers to: dev/TeachingTip/InteractionTests/TeachingTipTests.cs:625 in 21d2d54. [](commit_id = 21d2d5498ca172daa3189b41fba72eabd35ce62b, deletion_comment = False)

**Comment by StephenLPeters** [comment]
>             elements.GetIsLightDismissEnabledButton().Invoke();

The Invokes which are not followed by waits may be a cause for some test instability, while your in here could you update these types of Invokes to ensure the action waits appropriately?

---
Refers to: dev/TeachingTip/InteractionTests/TeachingTipTests.cs:716 in 21d2d54. [](commit_id = 21d2d5498ca172daa3189b41fba72eabd35ce62b, deletion_comment = False)

File: dev/TeachingTip/InteractionTests/TeachingTipTests.cs (hunk 1 above)
Comment (KevinTXY) [reply dev/TeachingTip/InteractionTests/TeachingTipTests.cs]: Gave it a run - strangely this actually breaks the test case (outside of debug mode at least) despite the fact that the Wait.ForIdle() statement inside InvokeAndWait is executed correctly. 

Irrespective of which method is used there is a suspicion of some level of unreliability regarding this test case.

Comment (jevansaks) [reply dev/TeachingTip/InteractionTests/TeachingTipTests.cs]: How does the test case fail? Some of these I left disabled because there seemed to be a logic error in the product (the test was expecting the right result but the product code wasn't producing it). Maybe the test is catching a bug now.

Comment (KevinTXY) [reply dev/TeachingTip/InteractionTests/TeachingTipTests.cs]: Hard to say - after adding a wait to every invoke I no longer can replicate the same failures that show up in the tests run in the pipeline ("Works on my machine 🤷‍♂ "). Every test was re-enabled except for autoPlacement because it has completely separate problems. It's possible there's another issue.

**Comment by jevansaks** [comment]
@KevinTXY looks like these re-enabled tests aren't passing. Maybe discuss with @StephenLPeters and go over the failure logs?

I'm wondering if "IsIdle" checkbox doesn't change correctly when animations are disabled?

**Comment by KevinTXY** [comment]
> I'm wondering if "IsIdle" checkbox doesn't change correctly when animations are disabled?

It's possible. I'm cosistently able to replicate test failures now and it's always in WaitForCheckBoxUpdated because the state of the checkboxes isn't changing properly. I don't have reason to suspect it's related to animations though.

**Comment by jevansaks** [comment]
> I don't have reason to suspect it's related to animations though - I've tried tracking the checkbox states and haven't been able to explain this behavior yet.

I agree, I don't think it's related. I also see the failures are only on RS3 and RS4 so I suspect that it's something to do with TeachingTip's behavior changing on downlevel versions of windows, or possibly an OS bug. @StephenLPeters, any thoughts on where to start debugging?

**Comment by jevansaks** [comment]
I see the bug now (we skip calling `StartExpandToOpen()` when on RS4 and older). I'll add an update to PR #568 and then we can merge that in here to have this change be only about your bug fix.

**Comment by jevansaks** [comment]
@KevinTXY can you merge in master to this PR branch?
