### PR TITLE
Fix bug where NavView in top mode would still open pane with gamepad

### LINKED ISSUE #1353: GamepadView button opens empty pane when PaneDisplayMode is set to Top
**Describe the bug**
NavigationView.PaneDisplayMode is Set to NavigationViewPaneDisplayMode.Top
I'm pressing View button on gamepad.
NavigationView opens it's pane which is empty (because of NavigationViewPaneDisplayMode.Top).

Screenshot_2019-09-19_04-09-13

### PR DESCRIPTION
**Pull request by chingucoding**
## Summary
Fixed a bug where the SplitPane would open despite the NavigationView being in display mode "Top" when the user hits the view button on the gamepad.

## Motivation
Fixes #1353 

## Testing Methodolgy
Tested manually.

### CODE REVIEW

File: dev/NavigationView/NavigationView.cpp [hunk 1]
```diff
@@ -1600,7 +1600,7 @@ void NavigationView::OnKeyDown(winrt::KeyRoutedEventArgs const& e)
     switch (key)
     {
     case winrt::VirtualKey::GamepadView:
-        if (!IsPaneOpen())
+        if (!IsPaneOpen() && !IsTopNavigationView())
```
Comment (licanhua) [inline dev/NavigationView/NavigationView.cpp]: Is it possible to add test case? There are a some existing test cases which is using gamepad in ScrollViewerTestsWithInputHelper.cs.

Comment (chingucoding) [reply dev/NavigationView/NavigationView.cpp]: I have added the appropriate test case.

File: dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs [hunk 2]
```diff
@@ -742,7 +769,7 @@ public void VerifyNavigationViewItemResponseToClickAfterBeingMovedBetweenFrames(
                 var myLocationButton = FindElement.ByName<Button>("MyLocation");
                 var switchFrameButton = FindElement.ByName<Button>("SwitchFrame");
                 var result = new TextBlock(FindElement.ByName("MyLocationResult"));
- 
+
```
Comment (licanhua) [inline dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs]: Any reason format is changed a lot in this file?

Comment (chingucoding) [reply dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs]: Oh I must have used auto format on that file and forgot to unstage the reformatted lines. Should I "revert" that?  :sweat_smile:

Comment (jevansaks) [reply dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs]: Most of the reformatting looks fine to me. The lambda changing to multiple lines is a little weird but i'm fine with that too.
