### PR TITLE
fix for uniformgrid property changed handler

### LINKED ISSUE #788: UniformGridLayout uses assignment instead of comparison
**Describe the bug**

On this line: https://github.com/microsoft/microsoft-ui-xaml/blob/61ea8fb19e84504a909cbe7bfa40202d2dc09090/dev/Repeater/UniformGridLayout.cpp#L270

That should be a comparison, not an assignment,

**Version Info**

Current master

**Additional context**

Apologies for not filling in more of the sections, but I think this describes the issue sufficiently.

### PR DESCRIPTION
**Pull request by ranjeshj**
Typo '=' instead of '=='
Fixes #788

### CODE REVIEW

File: dev/Repeater/APITests/FlowLayoutTests.cs [hunk 1]
```diff
@@ -146,6 +146,15 @@ public void ValidateGridLayout()
                         ((UniformGridLayout)panel.Layout).MinColumnSpacing = minColumnSpacing;
                         Content.UpdateLayout();
                         ValidateGridLayoutChildrenLayoutBounds(om, (i) => panel.Children[i], itemMinorSize, itemMajorSize, minRowSpacing, minColumnSpacing, panel.Children.Count, panel.DesiredSize);
+
+                        minRowSpacing = 5;
+                        minColumnSpacing = 10;
+                        ((UniformGridLayout)panel.Layout).MinRowSpacing = minRowSpacing;
```
Comment (chrisglein) [inline dev/Repeater/APITests/FlowLayoutTests.cs]: If this were product code I'd be asking you to fetch and dynamically cast that once. Reduce reuse recycle. And I try to hold test code to product code standards as much as possible. So... I'm guess I'm saying fix this too? :)

File: dev/Repeater/APITests/FlowLayoutTests.cs [hunk 2]
```diff
@@ -146,6 +146,15 @@ public void ValidateGridLayout()
                         ((UniformGridLayout)panel.Layout).MinColumnSpacing = minColumnSpacing;
                         Content.UpdateLayout();
                         ValidateGridLayoutChildrenLayoutBounds(om, (i) => panel.Children[i], itemMinorSize, itemMajorSize, minRowSpacing, minColumnSpacing, panel.Children.Count, panel.DesiredSize);
+
+                        minRowSpacing = 5;
```
Comment (chrisglein) [inline dev/Repeater/APITests/FlowLayoutTests.cs]: It'd be helpful to have a comment (or log statement) that describes what this block is trying to validate.
