### PR TITLE
[ProgressRing] Remove ProgressRing from UIA tree when it is not active

### LINKED ISSUE #2741: ProgressRing: Narrator issue when ring is not visible (IsActive set to false)
**Describe the bug**

Narrator announces "0% ProgressRing" when opacity is set to 0. 

**Expected behavior**

When the ProgressRing has IsActive set to false, opacity should be set to 0 and the visibility should be collapsed so narrator will not announce the ProgressRing. 

**Version Info**

This issue was found in WinUI 2.4. 

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

### PR DESCRIPTION
**Pull request by chingucoding**
## Description

Removing ProgressRing from UIA tree when it is not active.

## Motivation and Context

Closes #2741 

## How Has This Been Tested?

Tested with narrator, control does not get announced anymore.

### CODE REVIEW

File: dev/ProgressRing/ProgressRing.cpp [hunk 1]
```diff
@@ -341,7 +341,8 @@ void ProgressRing::UpdateStates()
             // Swap player source to determinate.
             SetAnimatedVisualPlayerSource();
             UpdateLottieProgress();
-        }   
+        }
+        winrt::AutomationProperties::SetAccessibilityView(*this, winrt::AccessibilityView::Content);
```
Comment (chingucoding) [inline dev/ProgressRing/ProgressRing.cpp:345]: We have to do this here since VSS setters can't set this on the "root" control

File: dev/ProgressRing/ProgressRing.xaml [hunk 2]
```diff
@@ -25,6 +25,7 @@
                                 <VisualState x:Name="Inactive">
                                     <VisualState.Setters>
                                         <Setter Target="LayoutRoot.Opacity" Value="0" />
+                                        <Setter Target="LottiePlayer.(AutomationProperties.AccessibilityView)" Value="Raw" />
```
Comment (chingucoding) [inline dev/ProgressRing/ProgressRing.xaml:28]: Setting this since we don't want the animation to still exist in the UIA tree.

File: dev/ProgressRing/ProgressRing.cpp (hunk 1 above)
Comment (ranjeshj) [inline dev/ProgressRing/ProgressRing.cpp:345]: Can we add a quick test ?

**Review by StephenLPeters — APPROVED** [review]

File: dev/ProgressRing/ProgressRing.cpp (hunk 1 above)
Comment (chingucoding) [reply dev/ProgressRing/ProgressRing.cpp:345]: Added an API test for this now (and the missing API tests project for the ProgressRing)

**Review by StephenLPeters — APPROVED** [review]
